### ISSUE TITLE
Unable to do a test direct debit with my bank account

### ISSUE THREAD

**Issue by inbaz** [nemiah/phpFinTS#1]
Hi nemiah,

thanks for looking into it and get it working with mtan. I just set up all the stuff and tried your sample directDebit.php file. For me it's not working. It recognizes no 901 tan mechanism, but a 942 tan mechanism. Do you have a list which number represents which mechanism? After that the communication failes.

Do you have a skype contact or email address? I would like to provide some more information for the key version. I'm getting a complete trace of the communication with the banking server but I don't want to put this trace online here.

Cheers
Andi

**Comment by nemiah** [comment]
Hi @inbaz,

I'm not sure that the numbers are the same for all banks.
But you can request the available TAN mechanisms with the variables.php example.

Yes, you can reach me at nena@furtmeier.it. I'm german by the way :smiley: 

Best wishes
Nena

**Comment by inbaz** [comment]
You got mail. :D
