### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#109]
Es wäre sinnvoll sich auf einen Coding Style zu einigen, z.B.
https://symfony.com/doc/current/contributing/code/standards.html

Als erste Schritt sollte die Einrückung vereinheitlicht werden.

Vlt können @Philipp91 und @nemiah dazu hier bescheid geben wenn keine großen Änderungen in der Pipeline sind.

**Comment by Philipp91** [comment]
Habe mir die mal durchgelesen. Es gibt ein paar Punkte, die derzeit abweichen, und wo ich den Mehrwert nicht sehe:

- Use Yoda conditions
- Add a blank line before return statements
- Use braces to indicate control structure body regardless of the number of statements it contains; Also kein `if (wrong) return false;`
- Declare public methods first, then protected ones and finally private ones.
- Declare all the arguments on the same line as the method/function name, no matter how many arguments there are;
- Suffix interfaces with Interface;
- Prefix all abstract classes with Abstract (wäre `Base...` auch erlaubt?)
- Don't inline PHPDoc blocks

Habt ihr speziell mit diesen Regeln auch gute Erfahrungen gemacht?

**Comment by nemiah** [comment]
Ich persönlich schreibe immer `if(wrong) return false;`, weil ich sehe keinen Sinn in den Klammern. Die Reihenfolge der Methoden ist mir egal, das wird eh von der IDE zusammengefasst.
Den Yoda Stil finde ich eher unschön. Ich weiß, warum es günstig ist, es "falsch" rum zu schreiben, aber das war bei mir noch selten ein Problem.

Ich würde es auf jeden Fall einfach halten. Sowas wie https://www.php-fig.org/psr/psr-2/ finde ich übertrieben.

**Comment by ampaze** [comment]
Ich sehe den großen Vorteil nicht so sehr in den konkreten Details sondern darin, dass man sich viel schneller zurecht findet wenn alles einheitlich (und dann gewohnt) ist. Man kann das ja vlt eher als Richtlinie sehen.

Yoda conditions machen wir z.B. tatsächlich auch nicht so häufig, manchmal bricht mein Kollege bei sehr vielen Parametern diese dann doch um 😉 

Aber was die Kontrollstrukturen angeht, kommt m.M. wieder die Einheitlichkeit ins Spiel
 ```
if (statement) {
    $var = 10;
}
```
vs
```
if (statement) $var = 10;
```

Ist für mich schneller erfassbar, weil es aussieht wie alle andere If-Blöcke. Sehe da keinen Vorteil an Klammern zu sparen.

Will mich aber daran wirklich nicht aufhängen. Wenn man nicht seine eigenen Standards ausarbeiten und aufschreiben will, ist es halt einfacher auf Vorhandene zu verweisen, die von großen Projekten erfolgreich eingesetzt werden.

**Comment by nemiah** [comment]
Von meiner Seite können wir https://symfony.com/doc/current/contributing/code/standards.html auch verwenden, ich finde nix kürzeres :wink:

**Comment by ampaze** [comment]
Dann geht es wohl als nächstes darum einen guten Zeitpunkt für die einmalige Entfernung der Tabs zu finden.

**Comment by ampaze** [comment]
Ich mache jetzt einfach einen Pull Request dafür ... müssen jetzt alle durch 😉

**Comment by nemiah** [comment]
:+1: :blush:

**Comment by fbett** [comment]
Da die Library aktuell stark überarbeitet wird (siehe z.B. #71), würde ich vorschlagen hiermit noch zu warten.
Sonst wäre zu erwarten, dass es bei neuen Pull-Requests wieder zu vielen Commits für kleine Änderungen kommt.

**Comment by ampaze** [comment]
Ich mache meine Branches / Pull Requests auch immer ausgehend vom aktuellen master. D.h. man muss dann eben rebasen oder mergen. Das ist dann leider nötig, da es hier sonst nie voran geht. 🤷‍♂

**Comment by fbett** [comment]
Soweit ich es verstanden habe, arbeitet @Philipp91 an ziemlich vielen Klassen und hat wohl noch einige uncommited Changes. Ich würde vorschlagen zumindest noch vier Wochen zu warten oder zumindest sein OK hierzu abzuwarten. 
Alles andere würde nur zu vielen Commits führen, die @nemiah nicht so bevorzugt und nur zu unnötigen Diskussionen führt.

**Comment by ampaze** [comment]
So wie ich es verstanden hab, hat @Philipp91 hauptsächlich neue Klassen wie z.B. eine FinTsNew.

So wie es jetzt ist, ist es genauso nervig, jedesmal an die Tabs von geänderte Zeilen zu denken.

Ich warte gerne noch auf seinen Kommentar dazu.

**Comment by Philipp91** [comment]
Mittlerweile habe ich genug hochgeladen, dass ich keine offenen Änderungen mehr in alten Dateien mit Tabs habe.

Wie wäre es, wenn wir so vorgehen:

- Wir basteln einen Shell-Befehl der automatisch alle Tabs am Zeilenanfang durch 4 Leerzeichen ersetzt.
- @nemiah holt sich den `master`, führt den Befehl aus und pusht den "großen Commit". Ohne Merge-Commit, also eine gerade Historie.
- Wenn jemand beim Rebasen Probleme kriegt, kann er vorab `git rebase -i` für alle seine Commits machen, alle auf `edit` stellen und pro Commit den Shell-Befehl ausführen und ggf. die "lokalen Änderungen" nehmen. Das ist kein echter Merge-Konflikt, weil man pro Commit weiß, dass sich außer den Tabs an den "remote Änderungen" nichts geändert hat. Also kann man sie verwerfen und mit dem Shell-Befehl die Tabs wieder rauskriegen. Danach dürfte es gegen `master` dann keine Merge-Konflikte mehr geben.

**Comment by nemiah** [comment]
klingt gut, machen wir so :+1: :relaxed:

**Comment by ampaze** [comment]
Top!

**Comment by ampaze** [comment]
Bin jetzt nicht so der Shell Bastler. Kann den Befehl jemand beisteuern?

**Comment by nemiah** [comment]
Ich hätte ein PHP-Script gemacht, das per Konsole ausgeführt werden kann :grin:

**Comment by dennobaby** [comment]
Anmerkung: Vorsicht mit tab-replacement. Macht das nicht auch mit dem .git-Verzeichnis.

**Comment by BenjaminRehn** [comment]
Für Bash/Shell 
sed -i 's/^\t/    /' *.php
TAB an jedem Zeilenanfang mit 4 Leerzeichen ersetzen, in allen .php dateien im aktuellen Verz.

**Comment by fbett** [comment]
Ich hatte es neulich auch mal mit einem ähnlichen Befehl gemacht, aber wie wäre es mit dem CS-Fixer?
https://github.com/FriendsOfPHP/PHP-CS-Fixer

Dann könnte man auch gleich sicherstellen, dass die Line-Endings immer gleich sind. 
Oder sogar noch weitergehend: dass der gesamte Code den Coding Styles entspricht.

**Comment by ampaze** [comment]
Das klingt ja sogar noch besser

**Comment by nemiah** [comment]
Ok, ich habe mal "/home/nemiah/Programme/php-cs-fixer.phar" "fix" "/home/nemiah/NetBeansProjects/phpFinTS/lib" "--rules=@Symfony" "--ansi" "--no-interaction" laufen lassen.
Er hat einiges geändert…

**Comment by Philipp91** [comment]
Gibt es da eine maximale Zeilenlänge?

Mit den Leerstellen bei den `@param`s ist das so ein Problem, die führen dazu, dass man später einen Diff auf Parametern hat, die man gar nicht angefasst hat. Dadurch wird `git blame` schwerer zu durchschauen und es führt zu mehr Merge-Konflikten.

Und wollen wir wirklich keine Leerstellen um den `.` Operator? Ich kenne mich mit PHP nicht wirklich aus, aber es ist doch einfach ein binärer Operator wie `+` oder so, wo man auch Leerstellen drum herum hat?

**Comment by Philipp91** [comment]
Falls noch Änderungen vorgenommen werden, wäre es gut, wenn man die in den Commit 
a727eb0 squashen könnte (force push), das führt dann hoffentlich zu weniger Merge-Konflikten wenn ich andere Commits rebasen muss.

**Comment by Philipp91** [comment]
Und wenn ich jetzt neue Dateien habe, wie formatiere ich die dann genauso? `/home/nemiah/` existiert bei mir natürlich nicht.

Vielleicht können wir:

- den Commit a727eb0 doch nochmal aus dem Repository rausnehmen,
- nochmal über die Style-Regeln drüber gehen, die wir automatisch angewendet haben wollen
- ein Skript submitten, das es automatisch ausführt
- ein Skript für Travis einbauen, das es neue Commits automatisch überprüft
- und dann den Commit machen, der es überall wirklich ausführt.

**Comment by nemiah** [comment]
Ich habe einfach den integrierten Symfony-Regelsatz drüberlaufen lassen, sonst müssen wir doch unsere eigenen Regeln erstellen. Dafür fehlt mir persönlich leider die Zeit. Weil da müsste ich mich auch erst in den cs-fixer einlesen, wie man die Regeln erstellt bzw. anpasst.

Man sollte es auch mit ins Repository übernehmen können, ja.

**Comment by Philipp91** [comment]
Ok, also verstehe ich das richtig, dass ich einfach den php-cs-fixer installieren muss (den tue ich am besten in die `composer.json`, oder) und dann kann ich den Symfony-Regelsatz anwenden?

Wenn ja, und wenn du den bisherigen Commit wieder rausnimmst, dann würde ich das mal probieren, und dann darauf aufbauend Änderungen am Regelsatz vorschlagen und zusammmen mit einem Skript/Travis-Test hochladen.

**Comment by Philipp91** [comment]
Hat geklappt, die Konfiguration ist jetzt hier: https://github.com/nemiah/phpFinTS/pull/143

Also könntest du den Commit rückgängig machen, den PR mergen, und dann einen frischen Commit erstellen. Einfach `composer install` und dann `composer cs-fix` ausführen.

**Comment by ampaze** [comment]
Endlich 🎉

**Comment by Philipp91** [comment]
Es gibt wohl noch zwei offene Fragen:

1. Leerzeile vor `return`.
2. Leerzeile zwischen phpDoc-Tags.

Beide sind für mich okay, wenn man sie mit anderen Regeln kombiniert (kein else nach return, und keine redundanten phpDoc-Tags).

Ich schlage vor, dass wir zunächst mit #143 fortfahren, wo alle fraglichen Regeln deaktiviert sind. Dann schicke ich separate PRs für (1.) und (2.), wo ich sie jeweils aktiviere. Dann kann man den Unterschied isoliert betrachten.

**Comment by ampaze** [comment]
Dein Vorschlag mit den PHP 7 in https://github.com/nemiah/phpFinTS/commit/a727eb0afebefdbd7f56c94539449096067c6031#r36114784 finde ich sehr gut.

Leerzeile vor return, ist mir nicht so wichtig, wenn es dafür schnell weiter geht ;)

**Comment by Philipp91** [comment]
Ok. Letzteres ist ja dann in #143 schon im richtigen Zustand. Ersteres braucht vermutlich etwas länger, weil die Regel die `@param` zu PHP7-Typdeklarationen konvertiert als "experimentell" markiert ist. Laut Dokumentation muss man ggf. von Hand ein bisschen nacharbeiten. Kann ich gerne machen, aber das sollten wir dann vertagen. Man sollte danach auch gut testen, gerade in den alten Klassen sind einige `@param`s auch schlicht falsch. Und wenn PHP es dann zur Laufzeit prüft, führt das zu neuen Fehlern.

Sprich #143 ist schon fertig für den Moment, oder?

**Comment by nemiah** [comment]
https://github.com/nemiah/phpFinTS/issues/109#issuecomment-557941390 ist ausgeführt :blush:

**Comment by Philipp91** [comment]
Danke. Wenn man übrigens noch eine Branch mit Änderungen hat, die noch umformatiert werden müssen, dann kann man sie so nachziehen:

1. Rebase auf master, wobei alle eigenen Änderungen übernommen werden (Achtung: Wenn es andere Änderungen im master gibt, die _nicht_ einfach die Formatierung betreffen, dann würden sie hierbei verloren gehen. Das funktioniert also nur, wenn HEAD keine Merge-Konflikte gegenüber master _vor_ der Umformatierung auf master hatte.)
```
# Das Upstream-Repository heißt nemiah.
git fetch nemiah
git rebase nemiah/master -Xtheirs
```
2. Alle Commits zwischen master und HEAD nachbearbeiten:
```
git filter-branch --tree-filter 'composer cs-fix && rm -f .php_cs.cache && git diff' nemiah/master..HEAD
```

**Comment by nemiah** [comment]
Ich arbeite immer auf master, das gibt den extra Kick :stuck_out_tongue_winking_eye:

**Comment by ampaze** [comment]
Kann doch eigentlich zu hier oder?
