### ISSUE TITLE
Neuer Release möglich?

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#11]
Wäre es möglich einen neuen Release / neue Version zu machen, damit man via Composer nicht die Minimum Stability überschreiben muss?

**Comment by nemiah** [comment]
Ok, v1.1 ist draußen ;)

**Comment by ampaze** [comment]
Vielen Dank,

aber https://packagist.org/packages/nemiah/php-fints kennt es leider nicht und damit findet es composer es auch nicht.

**Comment by nemiah** [comment]
Ok, jetzt sollte es klappen…

**Comment by ampaze** [comment]
Sorry für die Verspätung. Es klappt jetzt! Lieben Dank 👍 

Könnte ich dich bitten noch eine neue Version machen, mit den MT940 Änderungen? 
Besteht Interesse die MT940 Dialekte die ich gebaut habe zu integrieren? Wäre die Frage wie genau das aussehen kann.

**Comment by ampaze** [comment]
Danke :)

Ja es geht um das Abholen der Umsätze, die Dialekte von denen ich spreche sind eigentlich eher Workarounds für Banken die sich nicht an die MT940 Specs halten. 

Ich habe jetzt z.B. die Klasse SpardaMT940 und kann diese bei mir händisch für die Abrufe von Sparda nutzen. Allerdings würde phpFinTS bei Abrufen von Sparda natürlich diese Klasse nicht automatisch nutzen, dafür fehlt dann ein Mechanismus zu erkennen das ein abweichender MT940 Parser genutzt werden müsste. Wie der aussehen könnte, wäre die Frage.

**Comment by nemiah** [comment]
Ich könnte mir vorstellen, dass die "Dialekte" automatisch in der getStatementOfAccount() über die BLZ verwendet werden.
Weil sonst müssten wir die Auswahl letztlich dem Benutzer überlassen und er wird auch nichts anderes tun, als den "Dialekt" für seine Bank zu verwenden.

**Comment by ampaze** [comment]
Leider hat die Sparda nicht nur eine BLZ und auch nicht nur ein BIC. Aber vlt könnte man es über die FinTS Url mappen. 
Aber ich weiß natürlich nicht ob nur Sparda die URL nutzt (fints.bankingonline.de) oder ob jede andere Bank die auch diese URL nutzt dieselben Workarounds benötigt. 😞

**Comment by nemiah** [comment]
Also ich habe gerade durch die fints_insitute.csv durchgeschaut. Nur bei Sparda-Banken ist fints.bankingonline.de eingetragen. Ich würde es daher einfach mal an der URL festmachen. Ich persönlich schätze die Wahrscheinlichkeit hoch ein, dass es bei allen Sparda-Banken mit dieser URL gleich ist.

**Comment by ampaze** [comment]
Okay 👍, dann werde ich dazu einen Pull Request machen. Kann aber noch ein paar Tage dauern.

**Comment by ampaze** [comment]
Hab einen Pull-Request dazu gemacht, was meinst du?

**Comment by nemiah** [comment]
Sorry, war viel los die letzten Tage.
Habs mir gerade angesehen und sieht gut aus, finde ich :smiley:

**Comment by ampaze** [comment]
Ja dachte mir schon sowas 😀 
Danke!

Wenn du noch Zeit hast die nächsten Tage, würde ich mich auch noch über eine neue Version / Release freuen.

**Comment by nemiah** [comment]
Ist erledigt :wink:

**Comment by ampaze** [comment]
Ganz vergessen den Fall zu schließen :)
Danke!
