### ISSUE TITLE
Postbank Fehler: Request Failed: Inhalt syntaktisch ungültig. (9130); Teilweise fehlerhaft. (9050) 

### ISSUE THREAD

**Issue by js1963** [nemiah/phpFinTS#111]
Hi,

der Zugriff auf die Postbank funktioniert leider auch nicht.

Aus dem Log:
[2019-11-01 09:33:51] NULL.DEBUG: Fhp\FinTs:getVariables called [] []
[2019-11-01 09:33:51] NULL.DEBUG: New Dialog constructed [] []
[2019-11-01 09:33:51] NULL.INFO:  [] []
[2019-11-01 09:33:51] NULL.INFO: SYNC initialize [] []
[2019-11-01 09:33:51] NULL.DEBUG: > HNHBK:1:3+000000000384+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20191101:093351+2:2:13:@8@00000000:5:1+280:443:20010020:V:0:0+0'HNVSD:999:1+@228@HNSHK:2:4+PIN:1+999+7677490+1+1+1::0+1+1:20191101:093351+1:999:1+6:10:16+280:443:20010020:S:0:0'HKIDN:3:2+280:443+20010020+0+1'HKVVB:4:3+0+0+0+xxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxxxxxxxx'HKSYN:5:3+0'HNSHA:6:2+7677490++xxxxxxxxxxxx''HNHBS:7:1+1' [] []
[2019-11-01 09:33:51] NULL.DEBUG: < HNHBK:1:3+000000000137+300+0+1+0:1'HIRMG:2:2+9050::Teilweise fehlerhaft.'HIRMS:3:2:998+9130:8,2:Inhalt syntaktisch ungültig.'HNHBS:4:1+1' [] []
[2019-11-01 09:33:51] NULL.ERROR: [HIRMG] 9050: Teilweise fehlerhaft. [] []
[2019-11-01 09:33:51] NULL.ERROR: [HIRMS] 9130: Inhalt syntaktisch ungÃ¼ltig. [] []
[2019-11-01 09:33:51] NULL.ERROR: Request Failed: Inhalt syntaktisch ungÃ¼ltig. (9130); Teilweise fehlerhaft. (9050) [] []
[2019-11-01 09:33:51] NULL.CRITICAL: Request Failed: Inhalt syntaktisch ungÃ¼ltig. (9130); Teilweise fehlerhaft. (9050) [] []

lg.

**Comment by ampaze** [comment]
Postbank funktioniert bei mir mit dem Master.

Was rufst du genau auf?

**Comment by js1963** [comment]
Ich rufe getVariables() auf. Das scheint schon nicht zu funktionieren. Sowohl bei der Postbank als auch bei der Haspa nicht. Die Fehlermeldungen sind allerdings unterschiedlich

**Comment by js1963** [comment]
Was mir noch eingefallen ist: meine Pin enthält Sonderzeichen wie '!' und '='. Evtl. führt das zu dem Synthax Fehler

**Comment by ampaze** [comment]
! und = sind keine Sonderzeichen für das FinTs Protokoll. Die Pin wird escaped

`$this->pin = self::escapeString($pin);`

Hab mal probiert, bei meiner PIN ! oder = voranzustellen. Es kommt in beiden Fällen

>[error] [HIRMG] 9800: Dialogabbruch.
[error] [HIRMS] 9942: PIN ungültig

Darf ich fragen welche URL du verwendest? Hat Postbank evtl. mehrere?

**Comment by ampaze** [comment]
Hast du eigentlich mal die Beispiele in /Samples ausprobiert?

**Comment by js1963** [comment]
Ich bin jetzt ein Stück weiter. Ich hatte noch den Port in der Initialisierung mit übergeben, dann stimmt die Reihenfolge der Parameter natürlich nicht mehr.
Allerdings scheitere ich jetzt daran, dass inzwischen an mehreren Stellen PHP 7 Syntax verwendet wird, und ich auf dem Testsystem und (leider) auch auf dem Produktivsystem noch PHP 5.6 am Start habe.
Zumindest treten die vorherigen Fehler nicht mehr auf.

**Comment by js1963** [comment]
Jetzt - auf einem PHP 7 System - bekomme ich folgenden Fehler, es wird eine Exception geworfen
Expected first segment to be HNSHK:

#0 vendor\nemiah\php-fints\lib\Fhp\Dialog\Dialog.php(504): Fhp\Protocol\Message::parse('HNHBK:1:3+00000...') 
#1 \vendor\nemiah\php-fints\lib\Fhp\FinTs.php(237): Fhp\Dialog\Dialog->syncDialog() 
#2 Fhp\FinTs->getVariables() #3 {main}

Wenn ich das Werfen der Exception auskommentiere, werden die TAN Mechanismen geholt, allerdings kann ich die Sepa Accounts dann nicht abrufen:
Auftrag ausgeführt. (0020); BPD nicht mehr aktuell. Aktuelle Version folgt. (1040); Meldung unterstützter Ein- und Zwei-Schritt-Verfahren (930) (3920); UPD nicht mehr aktuell. Aktuelle Version folgt. (1050); Neue Institutsnachrichten verfügbar. (3020); Name des TAN-Medium erforderlich. (9210); Keine starke Authentifizierung erforderlich. (3076); Teilweise fehlerhaft. (9050)

Mit Haspa funktioniert es. Postbank leider (noch) nicht.

**Comment by fbett** [comment]
Ist ausgeschlossen, dass dies durch #66 ausgelöst wird?

**Comment by ampaze** [comment]
Bzgl. der Exception: Die Postbank arbeitet an der Stelle nicht nach Spezifikation, dafür hab ich einen Workaround gemacht, siehe #116. 

Für das zweite Problem:
Du musst via $fints->setTanMechanism den Namen des Tan-Mediums angeben, bevor du $fints->getSEPAAccounts aufrufst. Den Namen erfährst (momentan) du via $fints->getTANDevices()

**Comment by js1963** [comment]
Ich rufe getVariables() bevor ich die SepaAccount hole. Und zwar in zwei getrennt laufenden AJAX Scripten. Der Aufruf von getVariables() liefert die TAN Mechanismen, die dann in einer Selectbox abgelegt werden.
Lasse ich den vorherigen Aufruf von getVariables() weg, erhalte ich folgenden Fehler:

Gewähltes Zwei-Schritt-Verfahren nicht unterstützt. (9200); Dialogabbruch. (9800) Fehler

lasse ich den Aufruf von setTANMechanism weg, schlägt der Aufruf fehl:

Information fehlerfrei entgegengenommen. (0020); BPD nicht mehr aktuell. Aktuelle Version folgt. (1040); Meldung unterstützter Ein- und Zwei-Schritt-Verfahren (930) (3920); UPD nicht mehr aktuell. Aktuelle Version folgt. (1050); Neue Institutsnachrichten verfügbar. (3020); Name des TAN-Medium erforderlich. (9210); Keine starke Authentifizierung erforderlich. (3076); Teilweise fehlerhaft. (9050)

**Comment by js1963** [comment]
Ich habe es jetzt hinbekommen. Der Aufruf funktioniert jetzt sowohl mit der Postbank als auch mit der Haspa.
Vielen Dank für eure Hilfe!

**Comment by Philipp91** [comment]
Für's Protokoll, die entschlüsselte Fehlermeldung:

```
HIRMS:3:2:998+9130:8,2:Inhalt syntaktisch ungültig.'
```

Das Bezugssegment ist `998`, also das `HNVSK` aus der Anfrage.

```
HNVSK:998:3+PIN:1+998+1+1::0+1:20191101:093351+2:2:13:@800000000:5:1+280:443:20010020:V:0:0+0'HNVSD:999:1+@228@HNSHK:2:4+PIN:1+999+7677490+1+1+1::0+1+1:20191101:093351+1:999:1+6:10:16+280:443:20010020:S:0:0'HKIDN:3:2+280:443+20010020+0+1'HKVVB:4:3+0+0+0+xxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxxxxxxxx'HKSYN:5:3+0'HNSHA:6:2+7677490++xxxxxxxxxxxx''
```

Bezugselement darin ist `8,2`, also das zweite Gruppenelement in der achten Datenelementgruppe. Datenelementgruppen werden durch Plus getrennt (wobei die in `@`-Datenblöcken natürlich nicht zählen). Das achte ist also:

```
280:443:20010020:V:0:0
```

Und darin das zweite ist `443`, das ist `Kik::$kreditinstitutionscode`. Das passt aber nicht, denn `20010020` sollte der Kreditinstitutions-Code sein. Was macht die `443` da?
