### ISSUE TITLE
getSEPAAccounts

### ISSUE THREAD

**Issue by pbwissen** [nemiah/phpFinTS#112]
Wie kann man bei getSEPAAccounts eine TAN mit eingeben? Bei mir wird die TAN erzeugt, aber ich sehe nicht, wo ich diese übergeben kann. 
Nutze die HVB als Bank.

**Comment by ampaze** [comment]
Momentan nur via $tanCallback - Parameter.

Ich arbeite an einer anderen Möglichkeit. Siehe #71

**Comment by pbwissen** [comment]
Hi, Danke, aber leider funktioniert das bei mir nicht, da ich bereits beim initDialog eine TAN abfrage bekomme. Aber nach dem initDialog noch eine Message geschickt wird und dies failed. 

Response from initDialog:

HNHBK:1:3+000000006406+300+20191106094405277137TP0xasWra5+1+20191106094405277137TP0xasWra5:1'HNVSK:998:3+PIN:1+998+1+2::201911060944046815640018808968+1:20191106:094405+2:2:13:@3@;-):5:1+280:70020270:xxxxxxxxxx:V:0:0+0'HNVSD:999:1+@6155@HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:4+1040::BPD nicht mehr aktuell. Aktuelle Version folgt.+3920::Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:903'HIRMS:5:2:5+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich'HIBPA:6:3:4+70+280:70020270+HypoVereinsbank+0+1+220:300+0+0+0'HIKOM:7:4:4+280:70020270+1+2:hbci.hypovereinsbank.de+3:https?://hbci-01.hypovereinsbank.de/bank/hbci'HISHV:8:3:4+N+RDH:1:3:5:9:10+RAH:9:10+PIN:1'HIKPV:9:1:4+6:1:1:1'HIPINS:10:1:4+1+1+1+6:10:6:Onlinenummer:Onlinenummer:HKPAE:J:DKPAE:J:HKPSP:N:DKPSP:N:HKTLF:J:DKTLF:J:HKTSP:N:DKTSP:N:HKTAZ:N:DKTAZ:N:HKPRO:N:HKKAZ:J:HKSAL:J:HKVDB:J:HKKDM:J:HKAUB:J:BKTAB:N:BKTAL:N:BKTAS:J:BKXTA:J:HKWPD:N:XKDAT:N:XKDOB:N:HKTAN:N:XKDTB:N:XKDTD:J:XKDTF:J:XKDTL:J:HKSPA:N:HKCCS:J:HKCSE:J:HKCSB:N:HKCSL:J:HKCCM:J:HKCME:J:HKDME:J:HKBME:J:HKCUB:N:HKCUM:J:HKDSB:N:HKDSW:J:HKCDE:J:HKCDB:N:HKCDL:J:HKCDN:J:HKCDU:J:XKMIB:N:HKDMC:J:HKCSU:J:XKDPB:N'DIPINS:11:1:4+1+1+DKPAE:J:DKPSP:N:DKTLF:J:DKTSP:N:DKTAZ:N:HKPRO:N:HKKAZ:J:HKSAL:J:HKVDB:J:HKKDM:J:HKAUB:J:BKTAB:N:BKTAL:N:BKTAS:J:BKXTA:J:HKWPD:N:XKDAT:N:XKDOB:N:HKTAN:N:XKDTB:N:XKDTD:J:XKDTF:J:XKDTL:J:HKSPA:N:HKCCS:J:HKCSE:J:HKCSB:N:HKCSL:J:HKCCM:J:HKCME:J:HKDME:J:HKBME:J:HKCUB:N:HKCUM:J:HKDSB:N:HKDSW:J:HKCDE:J:HKCDB:N:HKCDL:J:HKCDN:J:HKCDU:J:XKMIB:N:HKDMC:J:HKCSU:J:XKDPB:N'HIPAES:12:1:4+1+1+1'DIPAES:13:1:4+1+1'HIPSPS:14:1:4+1+1+1'DIPSPS:15:1:4+1+1'HITLFS:16:1:4+1+1+1+2'DITLFS:17:1:4+1+1+J'HITSPS:18:1:4+1+1+1+0'DITSPS:19:1:4+1+1+N'HITAZS:20:1:4+1+1+1'DITAZS:21:1:4+1+1'HIPROS:22:2:4+999+1'HIPROS:23:3:4+999+1'HIPROS:24:4:4+999+1+1'HIKAZS:25:4:4+999+1+370:N'HIKAZS:26:5:4+999+1+370:N:N'HIKAZS:27:6:4+999+1+1+370:N:N'HISALS:28:3:4+999+1'HISALS:29:4:4+999+1'HISALS:30:5:4+999+1'HISALS:31:6:4+999+1+1'HIVDBS:32:1:4+999+1+2:Verrechnungsscheck ohne Talon:N:3:Verrechnungsscheck mit Talon:N:4:Barscheck ohne Talon:N:5:Barscheck mit Talon:N:6:Orderscheck ohne Talon:N:7:Orderscheck mit Talon:N'HIVDBS:33:2:4+999+1+2:Verrechnungsscheck ohne Talon:N:3:Verrechnungsscheck mit Talon:N:4:Barscheck ohne Talon:N:5:Barscheck mit Talon:N:6:Orderscheck ohne Talon:N:7:Orderscheck mit Talon:N'HIVDBS:34:3:4+999+1+1+2:Verrechnungsscheck ohne Talon:N:3:Verrechnungsscheck mit Talon:N:4:Barscheck ohne Talon:N:5:Barscheck mit Talon:N:6:Orderscheck ohne Talon:N:7:Orderscheck mit Talon:N'HIKDMS:35:2:4+999+1+350'HIKDMS:36:3:4+999+1+350'HIKDMS:37:4:4+999+1+350'HIKDMS:38:5:4+999+1+1+350'HIAUBS:39:3:4+999+1+1'HIAUBS:40:4:4+999+1+1'HIAUBS:41:5:4+999+1+1'HIAUBS:42:6:4+999+1+1+1'BITABS:43:1:4+999+1+14:HKAUB:HKCCS:HKCCM:HKCSE:HKCME:HKCDD:HKDME:HKBME:XKDTD:XKDTF:HKCUM:HKDSW:HKCDE:HKCDL:HKCDN:HKCDU:HKDMC:HKCSU'BITALS:44:1:4+999+1'BITASS:45:1:4+999+1'HIWPDS:46:5:4+999+1+N:N:N'HIWPDS:47:6:4+999+1+1+N:N:N'XIDATS:48:1:4+999+1+1'XIDOBS:49:1:4+999+1+30:N:Zweitschrift:Reklamation:Nachforschung'HITANS:50:1:4+1+1+1+N:N:1:0:900:1:01:iTAN-Verfahren(indizierte TAN):6:1:indizierte TAN:256:1:N:N:903:2:03:mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1::N:N:905:2:MS1.0.0:photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1::N:N'HITANS:51:4:4+1+1+1+N:N:1:900:1:01:::iTAN-Verfahren(indizierte TAN):6:1:indizierte TAN:256:1:N:4:0:N:N:N:N:N:00:0::903:2:03:::mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1::N:1:0:N:N:N:N:N:00:0::905:2:MS1.0.0:::photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1::N:1:0:N:N:N:N:N:00:0:'HITANS:52:5:4+1+1+1+N:N:1:900:1:01:::iTAN-Verfahren(indizierte TAN):6:1:indizierte TAN:256:1:N:4:0:N:0:0:N:N:00:0::903:2:03:::mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1::N:1:0:N:0:0:N:N:00:0::905:2:MS1.0.0:::photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1::N:1:0:N:0:0:N:N:00:0:'HITANS:53:6:4+1+1+1+N:N:1:900:1:01:::iTAN-Verfahren(indizierte TAN):6:1:indizierte TAN:256:N:4:N:0:0:N:N:00:0:N::903:2:03:::mobileTAN-Verfahren:6:1:Freigabe durch mobileTAN:1:N:1:N:0:0:N:N:00:0:N::905:2:MS1.0.0:::photoTAN-Verfahren:6:1:Freigabe durch photoTAN:1:N:1:N:0:0:N:N:00:0:N:'XIDTBS:54:2:4+999+1+1+J:J'XIDTDS:55:1:4+999+1+1+15:60'XIDTFS:56:1:4+999+1+1+15:60'XIDTLS:57:1:4+999+1+1'HISPAS:58:1:4+1+1+1+N:N:J:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:swift?:xsd?:$pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HICCSS:59:1:4+999+1+1'HICSES:60:1:4+999+1+1+1:90'HICSBS:61:1:4+999+1+1+N:N'HICSLS:62:1:4+999+1+1+J'HICCMS:63:1:4+999+1+1+5000:J:J'HICMES:64:1:4+999+1+1+1:60:5000:J:J'HIDMES:65:1:4+999+1+1+1:60:1:60:5000:J:J'HIDMES:66:2:4+999+1+1+0;0;1;120000:0;0;60:5000:J:J::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HIBMES:67:1:4+999+1+1+1:60:1:60:5000:J:J'HIBMES:68:2:4+999+1+1+0;1;120000:0;60:5000:J:J::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HICUBS:69:1:4+999+1+1+N'HICUMS:70:1:4+999+1+1+ACCT:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03'HIDSBS:71:1:4+999+1+1+N:J:56'HIDSWS:72:1:4+999+1+1+J'HICDES:73:1:4+999+1+1+2:1:365:0102030612:0102030405060708091011121314151617181920212223242526272829303199'HICDBS:74:1:4+999+1+1+N'HICDLS:75:1:4+999+1+1+1:365:N:J'HICDNS:76:1:4+999+1+1+0:1:365:J:J:J:J:N:N:N:N:J:0102030612:0102030405060708091011121314151617181920212223242526272829303199'HICDUS:77:1:4+999+1+1+1:1:365:1:N:N'XIMIBS:78:1:4+999+1+1+999'HIDMCS:79:1:4+999+1+1+5000:J:J:1:60:1:60::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HICSUS:80:1:4+999+1+1+ACCT:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03'XIDPBS:81:1:4+999+1+1'HITAN:82:6:5+4++#3750482645594099YPLFQF#KfoV9HsOrxE+Die SMS mit der ID 395 wurde versandt. Bitte überprüfen Sie die in der SMS übermittelten Auftragsdaten. Sind diese Auftragsdaten korrekt, geben Sie die mobileTAN ein.++20191106:095905''HNHBS:83:1+1'

**Comment by ampaze** [comment]
Die Möglichkeit $tanCallback bei setTanMechanism mit anzugeben und somit nicht mehr bei jeder Methode einzeln, ist in Arbeit. Die TAN-Behandlung ohne Callback ist ebenfalls noch in Arbeit.

In der Zwischenzeit kannst du dir den $tanCallback Parameter aber einfach analog zu syncDialog einbauen und dann bei sendMessage verwenden.

**Comment by ampaze** [comment]
Dies sollte mittlerweile funktionieren. Kannst du es nochmal probieren?

**Comment by Philipp91** [comment]
Dieser Issue kann vermutlich geschlossen werden.
