### ISSUE TITLE
Probleme mit Installation

### ISSUE THREAD

**Issue by opa-rudi** [nemiah/phpFinTS#115]
Ich bin gerade dabei, die nicht mehr funktionierende Markus-Schindler- PHP-FinTS-Lib mit dieser geforkten Version zu ersetzen, habe nun aber ein Problem mit der Installation. Die aktuelle Version 1.6 habe ich heruntergeladen. Im Ordner selbst habe ich dann mittels "composer install" die Abhängigkeiten (vendor) zugeladen und danach den gesamten Ordner auf den Server übertragen. Die Ordnerstruktur ist nun:

phpFinTS-1.6
- lib
- Samples
- vendor

Nun wollte ich das SampleScript variables.php ausführen, leider passiert nichts. Scheinbar funktioniert der Autoloader nicht korrekt? Hast jmd eine Idee, was ich prüfen könnte?

**Comment by D3vJust** [comment]
> Problem gelöst.

Immer die geilsten Antworten, wenn man selber das Problem hat..

**Comment by ampaze** [comment]
Eigentlich übernimmt Composer das herunterladen und erstellt den Autoloader für das Projekt.
D.h. man hat eine eigene composer.json und trägt dort (aktuell noch den master)

> "nemiah/php-fints": "dev-master@dev",

ein, bzw. zukünftig dann die Version die man will. Dann stimmt auch der Pfad zum Autolader in den Beispielen. (aka vendor/autoload.php)
