### ISSUE TITLE
Error while getSEPAAccounts 

### ISSUE THREAD

**Issue by LCD344** [nemiah/phpFinTS#119]
Hi, I'm owrking on a project and am following the instructions to get the sepa accounts and getting the next error

>  [9050] => Die Nachricht enthält Fehler.
>  [9800] => Dialog abgebrochen
>  [9078] => Software nicht als FinTS-Produkt registriert. Bitte an Her steller wenden.

I am pretty sure the product registration key is correct (I copy pasted it from the email forwarded to me by the client) - but I'm not sure about the software version, is that important? are there any steps I can take to make sure?

here is my code

```
define('FHP_BANK_URL', 'https://hbci-pintan.gad.de/cgi-bin/hbciservlet');                # HBCI / FinTS Url can be found here: https://www.hbci-zka.de/institute/institut_auswahl.htm (use the PIN/TAN URL)
define('FHP_BANK_CODE', '********');               # Your bank code / Bankleitzahl
define('FHP_ONLINE_BANKING_USERNAME', '******'); # Your online banking username / alias
define('FHP_ONLINE_BANKING_PIN', '******************');      # Your online banking PIN (NOT! the pin of your bank card!)
define('FHP_REGISTRATION_NO', '*************************');
define('FHP_SOFTWARE_VERSION', '1');     # Your own Software product version

	$fints = new FinTs(
		FHP_BANK_URL,
		FHP_BANK_CODE,
		FHP_ONLINE_BANKING_USERNAME,
		FHP_ONLINE_BANKING_PIN,
		FHP_REGISTRATION_NO,
		FHP_SOFTWARE_VERSION
	);


	$accounts = $fints->getSEPAAccounts();
```

**Comment by fbett** [comment]
Hi, we have seen this problem, if it's a new registration. 
It could help to try it again after 1-2 days.

My registration numbers match the format [A-Z0-9] and have a length of 25 characters.
Software-Version seems not important. We use (1.0 or 1.1).

**Comment by LCD344** [comment]
The email was sent on the 23 Oct 2019 - and the registration Number is in the format [A-Z0-9] indeed.

I will try debugging some more

**Comment by ampaze** [comment]
We also have a bank using **hbci-pintan.gad.de** and it is working fine. So I am pretty confident that it is not a problem in the library.

**Comment by LCD344** [comment]
Thanks, I still haven't managed to resolve; and have no news, I will if I get anything

**Comment by mmeinesz** [comment]
same problem here. I have contacted the registration authorities - see what they say.

**Comment by Philipp91** [comment]
Is there any update on this?

We could catch the error code `9078` in the library and output a more useful error message that says something like "depending on the bank it may take up to X weeks for the registration key to be recognized."

**Comment by mmeinesz** [comment]
For me (Volksbank Emmerich Rees) it took about 2 month until it was acceptence was actually implemented in the banks local db. You get the accepence in a few days, but the bank doesn't update its local db.

**Comment by Philipp91** [comment]
I've reinforced the warning in the README. Let's close this.
