### ISSUE TITLE
Segmentnummer HKTAN zu hoch

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#120]
Ich bekomme die Fehlermeldung "Request Failed: Nachricht nicht erwartet. (9120)", weil die Segmentnummer im HKTAN falsch ist.
Wenn ich 36fc282 mache, dann klappt es.
Kann da @ampaze oder @Philipp91 was dazu sagen?

**Comment by ampaze** [comment]
Ah mist, ich hatte das gesehen und dann aber vergessen noch zu fixen.

es müsste glaube ich generell 3 sein. Also, 

```php
$segments[] = $this->createHKTAN(count($segments) + 3);
```

**Comment by nemiah** [comment]
Ok, machen wir so :relaxed:

**Comment by Philipp91** [comment]
Ich kann dazu nichts sagen außer dass ich eine neue Message-Klasse habe
(schon hochgeladen? oder nicht?), die die Segmentnummern intern automatisch
vergibt, dann muss sich der Aufrufer nicht darum kümmern, und sie sind
immer korrekt.

Nena Furtmeier <notifications@github.com> schrieb am Do., 7. Nov. 2019,
14:54:
