### ISSUE TITLE
Hypovereinsbank fun fact

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#128]
Hallo zusammen,

ich habe heute herausgefunden, dass die Hypovereinsbank nur mit phpFinTS funktioniert, wenn als BLZ 70020270 angegeben wird. Die einzelnen BLZ der Filialen sorgen nur für eine Fehlermeldung.

Ich würde daher direkt einbauen, dass bei der Server-Adresse https://hbci-01.hypovereinsbank.de/bank/hbci immer die BLZ 70020270 verwendet wird.

**Comment by ampaze** [comment]
lol und ich dachte Postbank wäre schlimm ...

**Comment by nemiah** [comment]
jop… :woman_facepalming:
