### ISSUE TITLE
photoTAN-Bild anzeigen

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#129]
@fbett, ich habe #125 vorhin manuell germergt, damit der PR mal zu ist :relaxed: 

Wie komme ich denn jetzt an das photoTAN-Bild, wenn ich z.B. `executeSEPATransfer()` mache?

**Comment by fbett** [comment]
Ok, nice! Aber das wird dir jetzt nicht gefallen, wenn ich jetzt einen Pull-Request erstelle, kommen die ganzen Commits erneut und habe dazu noch Konflikte :D

(Es könnte ein Konflikt mit #127 geben.)

Vielleicht kannst du dir auch ein paar Commits picken.
Die Änderungen sind alle hier:
https://github.com/fbett/phpFinTS/commits/develop

Durch das manuelle Mergen hast du alle wichtigen Commits bis zum Ende vom Tag 09.11.
Weitere für dich wichtige Commits sind:
- New Segment: HITAN\HITANv6
- Response\GetTANRequest extended to get "Challenge" and "Challenge Image" (PhotoTan)
- Response\GetTanRequest should be serializable; Restorable DialogState introduced
- FinTS::finishSEPATANFromSerialized() introduced to use if a GetTanRequest is serialized
- Dialog::sendMessage should not interrupt or wait for a user input, this is application logic and could be implemented in the tanCallback-Closure (für asynchronen Zugriff)

Alternativ würde ich mal den Develop-Branch auschecken, so hat es glaube ich @Philipp91 erfolgreich testen können.

**Comment by fbett** [comment]
Ich bin ja durchaus bereit, die Anpassungen nochmal zu mergen, aber so wie ich @Philipp91 verstanden habe, wird er die Änderungen ohnehin einbringen.

**Comment by nemiah** [comment]
Schick, was du meinst, ich merge dann schon manuell, bis wir wieder auf dem gleichen Stand sind :wink:

**Comment by ampaze** [comment]
Ich finde nicht, dass die ganzen Serialisierungssachen (restoreFromState, DialogState, finishSEPATANFromSerialized) in FinTs sein sollte. Die Serialisierung kann jede Anwendung gern selber machen.

**Comment by nemiah** [comment]
@ampaze, da stimme ich dir zu, dafür brauchen wir keine eigene Methode.

**Comment by fbett** [comment]
Das Problem ist, dass doch nur die Library weiß welche Variablen sie braucht um einen Dialog weiterzuführen. 
Wenn hier in der Zukunft weitere Variablen notwendig wären, müsste jede Applikation unnötigerweise angepasst werden um wieder kompatibel zu sein, statt einfach die Library upzudaten.

Dazu kommt, dass die Sichtbarkeit von privaten/protected Parametern, z.B. in der Dialog-Klasse explizit public deklariert werden müssen (z.B. $messageNumber). 
Was zu vielen Problemen führt, weil nur die Library kontrollieren sollte, wann welcher Parameter gesetzt werden darf. 

Schaut euch einfach mal die `Dialog::restoreFromState` im oben genannten Branch an.

**Comment by fbett** [comment]
Darüberhinaus gibt es für mich keinen Grund warum eine Applikation steuern könnte sollte, welche Variablen für einen Dialog-Restore benötigt sein sollten, weil die Applikation hier auch nichts verändern darf (z.B. durch Übermittlung einer anderen DialogID oder MessageNumber)

**Comment by ampaze** [comment]
Aber damit zwingst du der Applikation auf sich um ein Session-Management zu kümmern. Was ist wenn sich zwei Benutzer bei TAN-Geschäftsvorfällen überschneiden? Wie kommt der richtige serialisierte Status wieder an die richtige Stelle?

Außerdem ist es zwar Nobel dem Anwender alles abnehmen zu wollen, aber man macht es dadurch teils komplizierter und schreibt gleichzeitig mehr vor. Die Anwender sind in diesem Falle aber auch Programmierer und können durchaus erfassen selbst Aufgaben übernehmen.

**Comment by fbett** [comment]
Ich verstehe das Problem nicht.

1. Fall: Du möchtest Umsätze eines Kontos abfragen:
- Du hast ein Objekt zum Thema "SepaAccount", lass es uns "BankAccount" nennen.
- Die Library wirft eine TanExpected-Exception
- Du speicherst die notwendigen Informationen in diesem Objekt "BankAccount".

2. Fall: Du möchtest einen Auftrag ausführen:
- Du hast ein Objekt zum Thema "Auftrag", lass es uns "DebitDirectRequest" nennen.
- Die Library wirft eine TanExpected-Exception
- Du speicherst die notwendigen Informationen in diesem Objekt "DebitDirectRequest".

Nein, es nicht "nobel", es ist notwendig. Und es wird dadurch für alle einfacher!

**Comment by fbett** [comment]
Vielleicht verstehe ich es nur nicht.

Bitte skizziere mir einen Use Case, bei dem es einfacher wäre, die vielen einzelnen (DialogID, MessageNumber, etc...) Variablen irgendwo zu speichern, statt einen einzelnen base64 codierten String zu speichern?

> Aber damit zwingst du der Applikation auf sich um ein Session-Management zu kümmern. Was ist wenn sich zwei Benutzer bei TAN-Geschäftsvorfällen überschneiden? Wie kommt der richtige serialisierte Status wieder an die richtige Stelle?

Nebenbei angemerkt, das wirst du ohnehin machen müssen. 
Wenn ich hier etwas übersehe, bitte erkläre es mir.

**Comment by ampaze** [comment]
> Nein, es nicht "nobel", es ist notwendig. Und es wird dadurch für alle einfacher!

Aber wenn es notwendig ist warum kann ich dann jetzt schon TANs einreichen für Lastschriften, Überweisungen oder für PSD2 Gründe? Und ja auch mit Unterbrechung der Verbindung und ganz ohne Serialisierung von Objekten.

Wenn man es ganz runter bricht, reicht es für das Übermitteln einer TAN völlig aus eine Nachricht mit der richtigen System-ID, Dialog-ID, Nachrichtennummer und Prozess-ID zu schicken. Man bräuchte dazu nicht mal Dialog::sync oder Dialog::init oder ähnliches.

Ich komme ohne Session-Management aus, weil ich eben nichts speichere 😀 .
Ist eine TAN fällig, wird der Nutzer direkt an die URL für die TAN-Eingabe weitergeleitet. 
Und dafür sind maximal die oben genannten 4 Werte nötig, je nach Bank reicht sogar die Prozess-ID allein aus. Wenn das ausreicht, warum den ganzen Aufwand?

Ich verstehe, dass das Ziel ist unbedingt Geschäftsvorfälle weiterführen zu können, es ist aber eigentlich nie nötig. Sollte ein Umsatzabruf unterbrochen werden, übermittelt man die TAN und wiederholt den Vorgang. Überweisung wird in jedem Falle unterbrochen, hat aber keine Rückgabewerte genauso wie Lastschrift. (Philipp hat andere Fälle skizziert, dass es vorkommen kann das keine TAN benötigt wird, aber dann wird halt nicht unterbrochen)
Das trifft meines Wissens auf die anderen Geschäftsvorfälle die FinTs implementiert auch zu.

Daher versuche ich etwas zu bremsen wenn jetzt alles in FinTs landet, was eigentlich nicht jeder in der Form braucht.

**Comment by fbett** [comment]
Nun, so kann das ja durch auch weiter funktionieren. Ich verstehe das Problem nicht.

Du hättest dann halt statt diesen vier oben genannten URL-Parametern (Dialog-ID, etc..) nur noch **einen Einzigen**. Das ist doch viel einfacher.
 Und wenn hier später mal ein anderer Parameter dazukommt muss oder entfernt wird, dann wird der String einfacher etwas länger oder kürzer, aber deine Applikation muss nicht angepasst werden.

Wenn es dir darum geht, dass der bisherige base64 encodete String so lang ist, dass er für eine URL zu lange sein könnte, dann liegt das daran, dass darin z.B. auch die PhotoTan ist, die halt nunmal nur binär vorliegt.

Du könntest dann einfach einen POST-Request, statt einen GET-Request verwenden und hättest im Formular für die Tan-Eingabe sogar die PhotoTan zur Verfügung.

Zum Rest bitte vergleiche einfach Dialog::finishSEPATan mit Dialog::finishSepaTanSerialized aus meinem Branch:
Außer dem Dialog-Restore sind diese identisch. Niemand hat behauptet, dass man außer den "benötigten" Informationen noch weitere benötigt.

Zu den weiteren Informationen im "DialogState", darin befindet sich aus folgenden Gründen diese Daten:
- Die Segmente: um die Challenge bzw. das Challenge Image zu erhalten
- die "SupportedTanMethods", weil die Deutsche Bank dermaßen pingelig ist stets die konkrete TanMethode zu erhalten und in einem Test, die Library hier nicht in der Lage, wenn diese Parameter nicht übergeben wurden.

Darüberhinaus habe ich dies auch schon im Thread #117 gesagt:
Ich wusste nicht welche Parameter wirklich benötigt werden und habe erstmal alles reingepackt. Wenn jemand hierzu weitere Informationen hat, kann man diese Informationen ja bequem entfernen.

**Comment by fbett** [comment]
> Ich verstehe, dass das Ziel ist unbedingt Geschäftsvorfälle weiterführen zu können, es ist aber eigentlich nie nötig. Sollte ein Umsatzabruf unterbrochen werden, übermittelt man die TAN und wiederholt den Vorgang. Überweisung wird in jedem Falle unterbrochen, hat aber keine Rückgabewerte genauso wie Lastschrift. (Philipp hat andere Fälle skizziert, dass es vorkommen kann das keine TAN benötigt wird, aber dann wird halt nicht unterbrochen)

Ich weiß nicht, das hatte ich nicht im Sinn und meiner Meinung nach in keinem Zusammenhang, ob man nun die Informationen serialisiert oder nicht.

**Comment by nemiah** [comment]
Ihr seid ein bisschen OT. Wie komme ich an die photoTAN? @fbett, kannst du bitte einen PR machen?
