### ISSUE TITLE
Composer Abhängig nemiah/php-sepa-xml 

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#15]
Die Abhängigkeit zu **nemiah/php-sepa-xml** wird ja nur für die Beispiele benötigt. 

Könnte man die Abhängigkeit in der composer.json in **suggest** verschieben? 

Aufgrund minimum-stability = stable, lässt sich **nemiah/phpFint** momentan nur installieren wenn man auch

`"nemiah/php-sepa-xml": "dev-master@dev"`

mit angibt.

**Comment by ampaze** [comment]
Vielen Dank. Könntest du noch eine neue Version für composer machen dafür?

**Comment by nemiah** [comment]
:heavy_check_mark:
