### ISSUE TITLE
DKB - Keine Verbindung / Kontoaufruf möglich

### ISSUE THREAD

**Issue by MartinWeidner** [nemiah/phpFinTS#154]
HI,

hat jemand erfahrungen mit der DKB gemacht, ich bekomme lediglich:

> Fhp\Dialog\Exception\FailedRequestException Object
> (
>     [summary:protected] => Array
>         (
>             [3079] => Bitte wenden Sie sich an den Hersteller des Banking-Programms.
>             [9078] => Dialog abgebrochen - Banking-Programm ist nicht registriert.
>             [9010] => Der Auftrag wurde nicht ausgefÃ¼hrt.(Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.)
>             [9050] => Die Nachricht enthÃ¤lt Fehler.
>             [9800] => Dialog abgebrochen
>         )

In Hibiscus habe ich DKB sowie comdirekt zum laufen bekommen, bin aber beim Versuch gescheitert die Logs zu vergleichen...

Hat jemand ein funktionierendes Beispiel wie und in welchen Reihenfolge welche Funktionen aufgerufen werden müssen?

Danke schon mal im Voraus

LG
Martin

**Comment by ampaze** [comment]
Hast du dir eine Registrierungsnummer besorgt?

https://www.hbci-zka.de/register/hersteller.htm

Wenn ja, wie lange ist das her?

**Comment by MartinWeidner** [comment]
Hallo,

ja habe ich Mitte September beantragt und wenige Tage später bekommen... Aktuell wird diese aber gar nicht übermittelt:

```
define('FHP_REGISTRATION_NO', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx');     
    # The number you receive after registration / FinTS-Registrierungsnummer

$fints = new FinTs(
        FHP_BANK_URL,
        FHP_BANK_CODE,
        FHP_ONLINE_BANKING_USERNAME,
        FHP_ONLINE_BANKING_PIN,
        FHP_PRODUCT_NAME,
        FHP_PRODUCT_VERSION
    );
```

**Comment by ampaze** [comment]
Diese FHP_ Defines sind nur für die Beispiele, und dort steht überall FHP_REGISTRATION_NO soweit ich sehen kann. Hast du den aktuellsten Stand?

**Comment by MartinWeidner** [comment]
Im Contructor ist es aber gar nicht vorgesehen:

```
/**
     * FinTs constructor.
     * @param string $server
     * @param string $bankCode
     * @param string $username
     * @param string $pin
     * @param string $productName
     * @param string $productVersion
     */
    public function __construct(
        $server,
        $bankCode,
        $username,
        $pin,
        $productName,
        $productVersion
    ) {
```
Quelle: [https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/FinTs.php](https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/FinTs.php)

Ich habe heute morgen ein composer update ausgeführt. Composer show zeigt:

> nemiah/php-fints dev-master ddef4a9 PHP Library for the protocols fints and hbci

Habe ich den richtigen Stand?

**Comment by ampaze** [comment]
$productName ist die Registrierungsnummer, zugegebenermaßen nicht so gut benannt.

**Comment by MartinWeidner** [comment]
Perfekt. Als nächstes kam die Exception, dass ich einen gültigen TanMediaName übergeben soll und jetzt geht es... DKB funktioniert!

Danke für den Support!
