### ISSUE TITLE
3079, 9078 - Banking-Programm nicht registriert 

### ISSUE THREAD

**Issue by nQk2** [nemiah/phpFinTS#156]
Seit dem Update erhalte ich:

"Fatal error: Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Bitte wenden Sie sich an den Hersteller des Banking-Programms. (3079); Dialog abgebrochen - Banking-Programm ist nicht registriert. (9078); Der Auftrag wurde nicht ausgeführt.(Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.) (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)..."

1. SetTanMechanisms gibt's ja nicht mehr - muss ich das trotzdem irgendwo setzen? Benutze pushTAN.
2. Den construct-Parameter Registrierungsnummer gibt's auch nicht mehr - muss ich die Reg.-Nummer nicht angeben?

**Comment by ampaze** [comment]
Statt `->setTanMechanism `jetzt `->login`.

Die Registrierungsnummer muss du angeben, als 5ten Parameter im Constructor, der Parameter heißt aber eigentlich schon die ganze Zeit `$productName.` Oder was meinst du mit gibt es nicht mehr?
