### ISSUE TITLE
FinTS registration

### ISSUE THREAD

**Issue by RiRe** [nemiah/phpFinTS#16]
All FinTS products are required to register for a product number, which have to be sent in the dialog:

https://www.hbci-zka.de/register/register_faq.htm

**FinTS integration will be unusable after 2019-08-01!**

Are there plans to integrate the possibility to set the product ID into the library?

**Comment by nemiah** [comment]
Yes, I am aware of this "issue". If nobody else does it, I will eventually add the functionality.

**Comment by ampaze** [comment]
Wäre es eventuell sinnvoll "phpFinTS" einfach als Produktname zu registrieren? Jetzt muss es scheinbar jeder Anwender selber machen?

**Comment by nemiah** [comment]
Ich habe darüber nachgedacht und würde es so lassen, da es ja nur eine Bibliothek ist. Der Anwender muss es ja nicht machen, nur einmal der Anwendungsentwickler.

**Comment by ampaze** [comment]
@nemiah Alles klar. Mittlerweile verstehe ich das Ansinnen der Registrierung auch so, die gesamte Anwendung zu erfassen, selbst wenn FinTS nur ein kleiner Teil davon ist.
Danke.

**Comment by js1963** [comment]
Mit der Registrierung erhält man folgenden Hinweis:
"HINWEIS: Ab dem 14.09.2019 stellen die Mehrzahl der Kreditinstitute neben der FinTS-Schnittstelle eine weitere Schnittstelle nach den Regularien der PSD2-Richtlinien bereit. Zahlungsauslösedienste und Kontoinformationsdienste bedürfen dann einer Zulassung der deutschen (BaFin) oder einer anderen europäischen Regulierungsbehörde. Detaillierte Hinweise sowie Informationen zu Testzugängen finden sie auf den Web-Seiten der Institute, bzw. deren IT-Dienstleister oder unter nisp.online.

Die bisherige FinTS-Schnittstelle darf durch diese Dienste bei Zugriffen auf Zahlungskonten dann nicht mehr genutzt werden."

Was bedeutet das genau? Muss eine PHP Applikation, die z.B. Kontobewegungen abfragt, dann zugelassen werden?

**Comment by nemiah** [comment]
@ampaze super, dann lassen wir es so :)

@js1963 Dazu kann ich leider nichts sagen, warten wir es mal ab ;)

Liebe Grüße
Nena

**Comment by js1963** [comment]
Hi,

ich hatte eine Anfrage an registrierung@hbci-zka.de gestellt, und nun die Antwort erhalten.

"...die Deutsche Kreditwirtschaft plant nicht, den FinTS-Zugang generell abzuschalten (einzelne Institute könnten hier aber eigene Entscheidungen treffen), Ob sie eine "Kontoinformationsdienst" nach PSD2 sind, kann ich nicht beantworten. Entscheidend dürfte sein, ob ihr System auf Rechnern der "Kontoinhaber" läuft, oder ob sie eine Dienstleistung in Namen der Kontoinhaber erbringen.

Sogenannte Drittdienste dürfen allerdings nach dem 14.09. nicht mehr über FinTS auf Zahlungskonten zugreifen, sonder müssen die "regulierte" neue Schnittstelle (siehe nisp.online) nutzen."

Das verstehe ich so, dass es einerseits vom Kreditinstitut abhängt, ob die die FinTS Schnittstelle weiter unterstützen. Da ich die Abfrage der Kontobewegungen nicht im Namen des Kontoinhabers sondern *für* den Kontoinhaber, denke ich, dass die PHP Software eher behandelt wird wie z.B. Starmoney oder andere Programme, die der Kontoinhaber selber nutzt. 

Grüße Jürgen

**Comment by nemiah** [comment]
Hallo Jürgen,

das hört sich ja schon mal gut an.

Liebe Grüße
Nena

**Comment by js1963** [comment]
Hi,
ich habe  noch etwas recherchiert. Unter https://www.finapi.io/finapi-psd2-lizenz/ findet man: "Dies betrifft Ihr Unternehmen, wenn Verbrauchern oder Unternehmen online ein Dienst bereitgestellt wird, der Bankkontodaten anzeigt oder verarbeitet und/oder Zahlungen von Bankkonten eines Nutzers ermöglicht und Zugangsdaten zu Bankkonten entgegengenommen werden, die einen Online-Zugriff auf die Bankkonten ermöglichen und mit den Zugangsdaten auch Zugriff auf Zahlungskonten insb. Girokonten erlangt werden kann."
Wenn die Software lokal beim Anwender läuft, dann stellt man wohl keinen Dienst zur Verfügung und fällt nicht unter das Gesetzt. Stellt man eine webbasierte Plattform zur Verfügung, würde man wohl unter die neue Richtlinie fallen. :-(


Viele Grüße
Jürgen

**Comment by ampaze** [comment]
Hallo Jürgen,

meine Interpretation ist die folgende:
Es gibt den Unterschied ob man sein eigenes Konto mit einer entsprechende FinTS-Software benutzt oder ständig die Zugangsdaten anderer abfragt und diese benutzt um auf deren Konto zu kommen. So wie es z.B. Sofortüberweisung ja macht.

Den normalen Anwendungsfall von phpFinTS sehe ich eher in der Abwicklung von Zahlungen für das eigene (Unternehmens/Vereins/etc.)-Konto in Form von Überweisungen, Lastschriften oder einfach Umsatzabrufe.

Somit betrifft diese PSD2 Richtlinie meiner Meinung nach Projekte mit phpFinTS in den seltensten Fällen.

Gruß
Tim

**Comment by js1963** [comment]
Hallo Tim,

ich denke auch, dass die Abfrage des eigenen Kontos nicht unter die PSD2 fällt, auch wenn die Software auf einem Webserver im Internet läuft. Fraglich ist, ob über die Software mehrere Konten für verschiedene Inhaber abgerufen werden können. Eingeben würden immer die Kontoinhaber die Zugangsdaten. Die Zugangsdaten werden nirgends gespeichert.

Klar ist bis jetzt wohl nur, dass der Zugriff auf alle Fälle nur mit ProduktID funktioniert, man sich also registrieren muss. Zudem muss sich der Zugriff mindestens einmal innerhalb von 90 Tagen gesondert ausweisen, vermutlich per TAN o.ä.. Unklar ist, ob das für den Zugriff auf dieses Konto gilt - egal mit welcher Software man darauf zugreift, oder ob sich die Software ausweisen muss, also ob die Bank die ProduktID mit heranzieht. Dann müsste ich den Abruf der Transkationen umbauen, um dem Benutzer die Möglichkeit zu geben eine TAN einzugeben.

Gruß
Jürgen

**Comment by js1963** [comment]
Hallo zusammen,
was mir noch eingefallen ist: wenn die Bank gelegentlich eine Authentifizierung verlangt, wie implementiert man das? Liefert der normale Abruf der Transkationen dann einen entsprechenden Fehlercode, den man auswertet und dann den Abruf nochmal startet, diesmal mit TAN o.ä,?

Gruß
Jürgen

**Comment by nemiah** [comment]
Hallo Jürgen,

bei einer Überweisung kommt eine TAN-Anfrage zurück, die dann entsprechend bearbeitet werden muss. Ich denke mal, das wird dann beim Abfragen der Umsätze auch so sein. Das müssen wir dann noch berücksichtigen, sobald es eine Möglichkeit gibt, es auch zu testen.

Liebe Grüße
Nena

**Comment by ampaze** [comment]
@nemiah Apropos TAN: Ich hatte eine alternative TAN-Behandlung implementiert, die ohne Endlosschleife und Callback auskommt. Die Verbindung kann ohne Probleme bis zur Übermittlung der TAN beendet werden solange man die Prozess-ID hat.
Evtl. besteht daran Interesse sich das mal anzugucken?

Das Problem sehe ich eher darin, wenn die TAN-Abfrage nicht immer kommt sondern gleiche Aufruf mal eine TAN braucht und mal nicht. Bislang weiß man ja welcher Aufruf eine TAN erfordert. We will see.

**Comment by nemiah** [comment]
@ampaze Es funktioniert schon ohne callback ;)
Es muss nur die Antwort von executeSEPATransfer zwischengespeichert und dann finishSEPATAN mit der Antwort und der TAN aufgerufen werden.

**Comment by ampaze** [comment]
@nemiah Stimmt, die Callback muss man nicht benutzen, irgendeine Form von Endlosschleife mit Polling o.ä. bleibt aber solange man alles in einem PHP-Prozess machen will.

Ich wollte darauf hinaus dass man die Verbindung zur Bank auch komplett beenden kann und damit auch die aktuelle PHP-Verarbeitung. Somit ist die TAN-Abfrage beim Nutzer komplett unabhängig von irgendeinem laufenden PHP-Prozess der irgendwie die TAN übermittelt bekommen muss.

Aber das war jetzt Off-Topic :sweat:

**Comment by dennobaby** [comment]
Meine Bank hat mich heute bezüglich der PSD2 im Online-Banking folgendermaßen informiert:

> Zum 14. September 2019 setzen Sparkassen und andere Finanzinstitute die neue EU-Richtlinie PSD2 (Payment Services Directive 2) um. Dadurch ergeben sich für Sie Veränderungen und Verbesserungen im Zahlungsverkehr und Online-Banking. Das Wichtigste für Sie im Überblick:
> 
> Mehr Sicherheit:
> Zum Login ins Online-Banking geben Sie künftig alle 90 Tage eine TAN ein. Die automatische Abmeldung aus dem Online-Banking erfolgt künftig nicht mehr nach zwölf Minuten, sondern bereits nach fünf Minuten.
> Da Sie nun regelmäßig eine TAN für Ihren Online-Banking Login benötigen, sollten Sie sicherstellen, kontinuierlich Zugang zu Ihrem TAN Verfahren zu haben - auch wenn Sie unterwegs sind.

**Comment by Philipp91** [comment]
Für's Protokoll: Die Consorsbank stellt ab heute das neue "SecurePlus" TAN-Verfahren zur Verfügung. Bevor man darauf umstellt, funktioniert phpFinTS wie gehabt. Nach der Umstellung gibt's den Fehler "HIRMG:2:2:+9800::Der Dialog wurde abgebrochen. Bitte melden Sie sich erneut an.'HIRMS:3:2:3+0020::Angemeldet.+0901::PIN gültig.'HIRMS:4:2:4+9160:5:**Ein erforderliches Datenelement fehlt**." wenn man nicht die `productName` und `productVersion` Parameter setzt.

Mit den neuen Parametern kommt man zwar einen Schritt weiter, aber man kann sich nicht einloggen, weil jeder Login nun eine TAN braucht. Ich eröffne dazu einen separaten GitHub-Issue.
