### ISSUE TITLE
Diskussion: Behandlung von FinTs Fremdformaten wie MT940 und SEPA-XML

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#165]
> Man könnte zusätzlich noch philosophieren ob MT490 parsen überhaupt Teil von FinTs ist, aber natürlich ist es schön direkt an brauchbare Daten ranzukommen.

_Originally posted by @ampaze in https://github.com/nemiah/phpFinTS/pull/157#issuecomment-560000864_

> Kann man in der Tat diskutieren. Vor allem, weil ja diese "PAIN" XML Nachrichten, die man zum Überweisen braucht, nicht Bestandteil der Bibliothek sind. Auch da wäre es schön, wenn man eine direkte API im Model hätte, aber die Entkopplung spricht wiederum für zwei separate Bibliotheken.

> Wir können gerne einen neuen GitHub-Issue aufmachen, um diese Diskussion weiterzuverfolgen, wo die Parser/Serialisierer für XML/MT940 implementiert sein sollten und wo welche Umwandlungen stattfinden sollten.

_Originally posted by @Philipp91 in https://github.com/nemiah/phpFinTS/pull/157#issuecomment-560011714_

**Comment by nemiah** [comment]
Also ich habe ja eine Bibliothek geschrieben, um die XML-Formate für die Lastschriften und Überweisungen zu erstellen und es ist ein ziemliches gefummel gewesen. Wir können das im Prinzip schon übernehmen, aber ich denke mal, viele werden es nicht brauchen, weil sie sowieso nur die Umsätze abholen. Ich finde es ist erstmal eine gute Schnittstelle, wenn dann nur die XML an phpFinTS übergeben wird. Ich könnte mir auch vorstellen, dass jemand die XML aus einer anderen Quelle bekommt.

Die Frage, wie wir Daten ausgeben, würde ich davon abhängig machen, ob die Nutzer von phpFinTS dann nicht sowieso mit hoher Wahrscheinlichkeit immer wieder die gleiche Funktionalität schreiben und ob sie zum Parsen Wissen brauchen, wie das Protokoll aufgebaut ist. Weil dann würde ich eine Kapselung in Klassen/Arrays bevorzugen.

**Comment by ampaze** [comment]
Ich stimme zu, dass man den XML-Payload unabhängig von FinTs erstellen/liefern muss.

Insbesondere bei Sachen wie SEPA-Überweisung oder SEPA-Lastschrift sollte man auch etwas über SEPA(-XML) wissen, z.B. was `MsgId`, `PmtInfId` und `EndToEndId` ist oder was IBAN-only ist.

Zudem ändern sich da ja auch öfter Sachen, z.B. ist COR1 mittlerweile obsolet.

Ähnlich sieht es mit dem Umsatzabruf via XML aus. Da würde ich auch sagen, das man das XML selber parsen muss und nicht phpFinTs vorgibt welche Daten verworfen werden.

Bliebe noch Umsatzabruf ohne XML d.h. via MT490, was sicher die meisten ausschließlich nutzen. Es wäre Interessant zu wissen wieviele Banken keinen XML Abruf anbieten. Ich weiß nur, dass es bei GLS geht, bei Sparda und Postbank nicht.

Wenn man davon ausgeht, dass die meisten Banken kein XML anbieten und alle ihren eigenen Pseudo Standard MT490 folgen, wäre es eigentlich ganz cool eine MT490 Bibliothek zu haben die viele Banken berücksichtigt wie wir es mit den MT490 Dialekten schon angefangen haben.

Aber dafür bräuchte es auch den Bedarf und Leute die es für ihre Bank umsetzen.

**Comment by Philipp91** [comment]
Mit welchen Banken funktioniert denn dieses XML? In den Integration-Tests sind doch die BPD hartkodiert, oder? Dort finde ich `HICAZS` nur bei der DKB, nicht bei Consors, IngDiba oder Postbank.

**Comment by ampaze** [comment]
Ich verwende es bei der GLS, die teilen ihren Rechenzentrum mit einigen anderen Banken. Also die sollten das dann auch können.

Es scheint mir aber leider trotzdem recht wenig verbreitet zu sein.
