### ISSUE TITLE
Login mit Tan und TanToken schlägt fehl

### ISSUE THREAD

**Issue by fjogeleit** [nemiah/phpFinTS#170]
Hallo,

ich versuche gerade die neue Login Logik für die Deutsche Bank und Ostsächsische Sparkasse zu implementieren.

Bei dem initialen Login ohne TAN bekomme ich bei der Sparkasse folgenden Fehler:
(pushTAN verfahren, tanMediaName: "handy")

```
Call to a member function tanRequiredForRequest() on null
(.../vendor/nemiah/php-fints/lib/Fhp/FinTsInternal.php:104)
```

der Code dazu sieht wie folgt aus:

```
                $variables = $finTS->getVariables();
                $tanMode = null;
                $mediaName = null;

                if (false === empty($variables->tanModes)) {
                    $tanMode = array_keys($variables->tanModes)[0];
                    $devices = $finTS->getTANDevices($tanMode);

                    if (false === empty($devices)) {
                        $mediaName = $devices[0];
                    }
                }

                $finTS->login($tanMode, $mediaName);
```

Wenn der gleiche Code für die Deutsche Bank ausgeführt wird gibt es keine Probleme beim initialen login Aufruf.
(Deutsche Bank: photoTAN App)

Jedoch bekomme ich beim 2. Request in dem ich das FinTS::submitTanForToken mit dem zwischengespeicherten Token und der Tan aus der photoTAN App ausführe einen Fehler:

```
[9999]=>string(27) "Dialog bereits geschlossen."
[9800]=>string(27) "Dialog ungueltig/unbekannt."
[9050]=>string(21) "Teilweise fehlerhaft."
```

Der Code dazu ist nur das erzeugen der FinTS3 Instanz und der Aufruf der Funktion:

```
$finTS3 = new FinTS3(...)
$finTS3->submitTanForToken($tanToken, $tan);
```

Ich habe mich an den Samples orientiert und alle Funktionsaufrufe analog aufgerufen.

**Comment by ampaze** [comment]
Denke das liegt an dem `->getTANDevices` Aufruf. 
Der dürfte ohne vorheriges `->login` bzw. `$dialog->initDialog` gar nicht funktionieren.

Probier doch mal bitte nur `->login`.

Bzgl. Deutsche Bank, hast du vlt. nach der TANRequiredException noch `$fints->end()` oder `$dialog->endDialog();` aufgerufen?

**Comment by fjogeleit** [comment]
Der Hinweis zu `$fints->end()` ist gut, das schau ich mir nochmal an.

Zu dem Problem der Sparkasse, ich habe das `getTANDevices` erst im Nachhinein eingefügt da ich vorher den Fehler bekam den "tanMediaName" angeben zu müssen. Wenn ich die Methode vor dem Login nicht aufrufen kann - wie soll ich dann ermitteln welchen `tanMediaName` ich nehmen muss? Der Wert für meinen Zugang muss ja nicht zwangsweise immer gelten?

**Comment by ampaze** [comment]
Den Namen des Mediums vergibst du ja selber, der sollte sich daher nicht einfach so ändern. 
`FinTs::login` sollte dir in der Exception eine Liste von Namen angeben wenn einer benötigt ist.

Guck am besten mal die Implementation von `FinTs::login` an.

**Comment by fjogeleit** [comment]
Aus der Methode `FinTs::login` habe ich ja die Logik mit dem Aufruf von `$finTs->getTANDevices` entnommen um den Namen zu ermitteln und dynamisch zu setzen. Deshalb die Frage ob ich den Namen auch fest vergeben kann wenn ich die Logik nicht nutzen kann bevor der login erfolgreich war.

**Comment by ampaze** [comment]
Ich hatte es so gedacht, dass man den TAN-Mechanismus und ggf. TAN-Medium-Namen immer direkt als Parameter übergibt, d.h. fest vergibt.

**Comment by fjogeleit** [comment]
Die Sparkasse funktioniert nun mit einem festen TAN-Medium-Namen. Deutsche Bank kann ich leider erst am Montag testen.

**Comment by fjogeleit** [comment]
Schließe den Issue ersteinmal. Sparkasse funktioniert und Deutsche Bank werd ich nochmal prüfen. Gehe aber davon aus das es ein Fehler von mir war.
