### ISSUE TITLE
FinTsNew::selectTanMode sollte nicht vor ::login schon mit der Bank kommunizieren

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#179]
Kann man die Prüfung auf einen gültigen TanMode nicht erst bei `::login` machen?

Jetzt findet schon beim Konfigurieren der Instanz eine Kommunikation mit der Bank statt. Alternativ wäre evtl. `::login` die Parameter `$tanMode, $tanMedium = null` zu geben und dann eben nicht `::selectTanMode` aufzurufen.

**Comment by ampaze** [comment]
PS: @Philipp91

**Comment by Philipp91** [comment]
Beides gute Vorschläge. Die `selectTanMode()` habe ich hinzugefügt bevor es `login()` überhaupt gab, deshalb habe ich es damals nicht bedacht.

**Comment by Philipp91** [comment]
In meiner Anwendung werden beide Funktionen direkt nacheinander aufgerufen, es würde also nicht stören, wenn sie zusammengefügt werden. Trotzdem kommt es mir wie ein eher seltsames Design vor. Ich könnte mir auch Anwendungen vorstellen, die nur ein einziges Mal pro User `new FinTs()` ohne `$persistedInstance` und gleich `selectTanMode()` aufrufen, und danch ewig lang dieselbe Instanz verwenden (dank `persist()`). Eine solche Anwendung würde immer wieder `login()` aufrufen ohne den TAN-Modus neu angeben zu wollen. Das Gegenteil von `login()` ist `close()` oder `forgetDialog()` -- und die löschen ja beide auch den gewählten TAN-Modus nicht. Also wäre es irgendwie asymmetrisch.

Die andere Alternative ist, dass `selectTanMode()` nicht `resolveTanMode()` aufruft, sodass `FinTs::$selectedTanMode` zu `TanMode|int` wird. Dann müsste man überall dort, wo es gelesen wird, den int auflösen. Das sind so 3-4 Stellen, ist also gut machbar. Wenn niemand widerspricht, mache ich das.

**Comment by ampaze** [comment]
Ich bin dafür :P 

Allerdings würde ich gerne selectTanMode beibehalten, oder es evtl. zu den FinTsOptions hinzufügen. Der Hintergrund ist, dass ich ja für verschiedene Banken vorkonfigurierte Instanzen erzeugen muss und diese dann im eigentlichen Geschäftsvorfall-Code benutzt werden, d.h. erst dort dann ::login aufgerufen wird, ich aber an der Stelle dann nicht mehr TanMode oder MediaName kenne.

**Comment by Philipp91** [comment]
`selectTanMode()` beizubehalten ist ja durchaus Teil des Plans, nur die Implementierung davon ändert sich. Sprich es ändert sich nichts daran, wie eine Anwendung die Bibliothek verwendet, nur die erste Serveranfrage wird später ausgeführt.

Diese TAN-Infos kann man nur schwer in `FinTsOptions` packen, weil `FinTsOptions` an sich schon benötigt wird, um die verfügbaren TAN-Modus/Medien abzurufen, was man ja können muss, bevor man sich für einen/s entscheidet.

**Comment by Philipp91** [comment]
Siehe #184

**Comment by ampaze** [comment]
Danke.

**Comment by v-bubar** [comment]
Wurde dieses Issue gemerged? 
Ich nutze `dev-master` und `login()` wirft immer noch `selectTanMode() must be called before executing business transactions`. 
Oder verstehe ich irgendwas grundsätzlich nicht?

**Comment by Philipp91** [comment]
Ja, die Lösung dafür wurde gemergt. Hier ging es nur darum, dass `selectTanMode()` noch nicht zu ausgehenden Verbindungen zur Bank führt.

> Oder verstehe ich irgendwas grundsätzlich nicht?

`selectTanMode()` vor `login()` aufgerufen werden. Ich werde die Fehlermeldung genauer formulieren.
