### ISSUE TITLE
Instanceof Fehlermeldung

### ISSUE THREAD

**Issue by JarvisHome** [nemiah/phpFinTS#18]
Hallo, 
bin gerade dabei das Original von mschindler83 (wegen diverser Probleme) durch diese Version zu ersetzen - sieht bisher sehr viel besser aus - danke dafür!

Folgendes ist mir noch aufgefallen; 
Fehlermeldung: E_WARNING: preg_match() expects parameter 2 to be string, object given in /var/www/test3/evyn/core/vendor/nemiah/php-fints/lib/Fhp/Response/Response.php line 394

Hab es wie folgt gelöst:
Zeile 38 von Response.php
`if ($rawResponse instanceof Initialization) {`
ersetzt durch:
`if ($rawResponse instanceof Response) {`

Viele Grüße!

**Comment by nemiah** [comment]
Danke :)
