### ISSUE TITLE
FinTsNew BaseAction::isError vs ServerException::detectAndThrowErrors

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#181]
@Philipp91

Wie hast du das gedacht? Ich hatte jetzt so gedacht
```
$fints->execute($action);
if ($action->isError()) {
}
```

Aber es wird eine Exception geworfen.

**Comment by ampaze** [comment]
Es ist wohl so gedacht, dass du die Fehler die zur Action gehören an die Action schreibst. In FinTsNew::sendRequestForAction

Allerdings gibt es ja dann immer auch den Globalen Fehler 
> 9050 (global): Die Nachricht enthält Fehler.

Also ist zwar der Fehler der zur Action gehört dorthin kopiert, die Exception wird aber trotzdem geschmissen.

**Comment by Philipp91** [comment]
> Es ist wohl so gedacht, dass du die Fehler die zur Action gehören an die Action schreibst.

Genau. Das Design ist so gestaltet, dass man prinzipiell mehrere Actions gleichzeitig ausführen kann und jede ihre Fehler zugewiesen bekommt. Auch wenn wir in der Praxis nur eine Action unterstützen, halte ich es für hilfreich, diesen Grundgedanken im Hinterkopf zu behalten. Fehler wie eine `CurlException` sind zum Beispiel nie die Schuld von einer Action. Wenn `execute()` eine solche Exception wirft, kann man es gleich nochmal versuchen -- die Action ist ja nicht fehlgeschlagen. Bei globalen Fehlern würde ich generell auch in die Richtung tendieren (z.B. wenn man ein falsches Passwort angibt oder so).

`9050` scheint ein Spezialfall zu sein, der eben genau bedeutet, dass ein Fehler "enthalten" ist. Zumindest in den Integration Tests, wo `9050` drei Mal vorkommt, ist dann 2x auch noch `9800` drin ("Dialog abgebrochen").

Ich würde sagen, `9050` sollten wir unter den Tisch fallen lassen (da steht eh nie was Interessantes drin) und `9800` auch, aber dann noch die `$dialogId` zurücksetzen.

**Comment by ampaze** [comment]
Super!
