### ISSUE TITLE
Vorzeitiges Dialogende bei  BTV-Bank

### ISSUE THREAD

**Issue by JarvisHome** [nemiah/phpFinTS#19]
Vorweg: das Problem tritt bei uns nur bei der BTV-Bank auf (BLZ: 72012300) - die anderen Banken gehen einwandfrei. Außerdem geht der Abruf mit der Ursprungsversion von diesem Fork auch ohne Fehlermeldung.

Meldung (Zugangsdaten stimmen):
Request Failed: Die Nachricht enthält Fehler. (TRE) (9050); Anmeldung nur noch mit Alias oder VR-Kennung zulässig (TRP) (9150); Dialog abgebrochen (TRE) (9800); Auftrag abgelehnt. (TRE) (9340).

Ich konnte es soweit eingrenzen: FinTs.php - Zeile 142
`$dialog->endDialog();`

Der endDialog wird wohl ausgeführt bevor alle Dialoge beendet sind (alternativ: der Init danach geht schief). Jedenfalls geht der weitere Dialog nach dem Aufruf von endDialog(); nicht weiter.

Wenn ich diese Zeile auskommentiere dann Läuft der Abruf komplett erfolgreich durch.
Ich kenne jedoch die Architektur der Klasse zu wenig um die eigentliche Ursache näher einzugrenzen.

**Comment by nemiah** [comment]
Hallo,

ich kann leider im Moment auch nicht sagen, warum das $dialog->endDialog(); da drin ist. Weil die Verbindung wurde ja gerade erst aufgebaut. Ich nehme es mal raus.

Liebe Grüße
Nena

**Comment by tobias-dietz** [comment]
Hallo Nena,

es scheint so, als sei durch die Änderung im Commit

https://github.com/nemiah/phpFinTS/commit/4c6ee6a52db7da8e6605ec6d76143c0e1a02c081

die Kommunikation mit der/einer Volksbank / Fiducia (BLZ 60069378) in die Brüche gegangen:

```
SYNC initialize
[HIRMG] Bitte beachten Sie die enthaltenen Warnungen/Hinweise.
[HIRMS] Auftrag ausgeführt.
Received system id: XXXXXXXXXXXXXXXXXXXXXXXXXX
Received dialog id: XXXXXXXXXXXXXX
Supported TAN mechanisms: 942
SYNC end
DIALOG initialize
[HIRMG] Die Nachricht enthält Fehler.
[HIRMG] Dialog abgebrochen
[HIRMG] Die angegebene Bankreferenz ist nicht gültig.
Request Failed: Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Die angegebene Bankreferenz ist nicht gültig. (9010)
```

Mein Code sieht so aus:

```
$fintsConnector = new Fhp\FinTs($fints->server, $fints->port, $fints->bank_code, '1234567890', 'VRNetkeypasswort', $psr3log, 'Produktname', '1.0');
foreach ($fintsConnector->getSEPAAccounts() as $sepaAccount) {
    // usw.
}
```
- (OT: Produkt Name und Version sind bei dieser Bank seit 10.06.2019, 03:45 Pflichtfelder, ohne die geht es nicht mehr)
- Sobald ich das Raute-Zeichen in lib/Fhp/FinTs.php Zeile 142 entferne (#$dialog->endDialog(); //probably not required), funktioniert es wieder.
- die Methode getAccounts() (also ohne SEPA) hat weiterhin funktioniert, habe aber nicht weiter gegraben, warum.
- Ich habe leider keine andere Volksbank-BLZ zum testen zur Hand... 
- HBCI Server: https://hbci11.fiducia.de/cgi-bin/hbciservlet

Viele Grüße,
Tobi

**Comment by nemiah** [comment]
Hallo Tobi,

hmm, ich habe das gleiche Problem mit meinem Konto.
Die Frage ist, wie wir erkennen können, wann endDialog() erforderlich ist und wann nicht.

Hat jemand eine Idee?

**Comment by JarvisHome** [comment]
jup, sieht gut aus - so geht es bei mir auch.

Wollte vorher schon schreiben dass das Original funktioniert hatte,...

Herzliche Grüße
Christian

**Comment by nemiah** [comment]
Super, dann lassen wir es mal so und warten ab :)

Liebe Grüße Nena
