### ISSUE TITLE
Man kann keine eigenen Segmente implementieren, da der Parser auf den Fhp\ Namespace hardcoded ist

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#193]
Und wenn man in den eigenen Segmenten den Fhp Namespace benutzt und bei Composer angibt dann kommt

`Fatal error: Cannot declare class Fhp\Segment\DDE\HIDDESv1, because the name is already in use in <PRIVAT>/FinTs/Segment/DDE/HIDDESv1.php on line 11`

@Philipp91

**Comment by Philipp91** [comment]
Habe es nicht eingehend getestet, aber es scheint bei mir zu funktionieren. Ich habe neben meinen `src/` und `vendor/` Verzeichnissen ein neues Verzeichnis `fints-segments/` angelegt und dann `fints-segments/TES/HKTESv1.php` erstellt:

```
<?php
namespace Fhp\Segment\TES;
use Fhp\Segment\BaseSegment;
class HKTESv1 extends BaseSegment {}
```

Dann in `composer.json`:

```
"autoload": {
    "psr-4": {
      "Fhp\\": "vendor/fints-temp/lib/Fhp/", // Das brauche ich nur, weil ich von `master` lade.
      "Fhp\\Segment\\": "fints-segments/",
      "App\\": "src/"
    }
  },
```

Jetzt sind sowohl `class_exists('Fhp\\Segment\\TES\HKTESv1')` als auch `class_exists('Fhp\\Segment\\TAN\HKTANv1')` wahr.

**Comment by ampaze** [comment]
Danke. Das lag dann wohl an meiner Verzeichnisstruktur. Die neuen Segment dürfen nicht innerhalb der Verzeichnisstruktur eines eigentlich anderen Namespaces liegen. Hatte da wohl von Composer/PHP zu viel erwartet, zumal die Fehlermeldung von PHP völlig nutzlos ist.
