### ISSUE TITLE
Bug in Parser/MT940.php

### ISSUE THREAD

**Issue by Magellanth** [nemiah/phpFinTS#199]
Hallo,

wir hatten zum Jahreswechsel einige Buchungen bei denen ein Buchungsdatum 2018-12-30 generiert wurde welches natürlich 2019-12-30 sein müsste.

Ich habe die Zeile : 61 aus den Rohdaten angesehen:
'2001011230CR0,00N066NONREF'
Dies entspricht im folgenden Code dem Inhalt der Variable $transaction.

In der MT940.php aktuellste Version ab Zeile 100 lautet der Code:
```php
 // if valuta date is earlier than booking date, then it must be in the new year.
                        $year = substr($transaction, 2, 2) < substr($transaction, 6, 2) ? --$year : $year;
                        if (substr($transaction, 2, 2) == '12' && substr($transaction, 6, 2) == '01') {
                            ++$year;
                        } elseif (substr($transaction, 2, 2) == '01' && substr($transaction, 6, 2) == '12') {
                            --$year;
                        }
```

In besagtem Fall wird das Jahr "20" also zwei Mal um eins erniedrigt (erste Zeile und nochmal im elseif).

Einer der beiden Teile muss imho entfernt werden.

**Comment by ampaze** [comment]
Gibt es dazu evtl. andere Implementationen? Und was sagt die Spezifikation?

> // if valuta date is earlier than booking date, then it must be in the new year.

Das ist imho keine gültige Aussage. Das Wertstellungsdatum kann durchaus vor dem Buchungsdatum sein.

**Comment by Magellanth** [comment]
Das kann ich nicht sagen, in meinem Fall "2001011230" ist ja das Wertstellungsdatum der 01.01.2020 und das Buchungsdatum der 30.12, da ist sicher nicht der 30.12.2020 gemeint sondern offenbar 2019 insofern erscheint die Logik aus dem if/elseif schlüssig.

Der if/else Teil würde ja eine umgekehrte Reihenfolge zulassen, nur nicht mit einem Jahr Differenz, die einzelne Zeile hingegen scheint mir fragwürdig, das würde ja bei jedem Monatswechsel greifen.

Was aber definitiv falsch ist, ist dass eine ähnliche Logik zwei Mal stattfindet so dass am Ende 2018 herauskommt - ich vermute bei einer Änderung des Codes wurde da schlicht vergessen den alten Teil zu löschen.

**Comment by ampaze** [comment]
Das ist unbestritten ein Fehler. Ich überlege nur wie man es gleich robuster implementiert.

Danke für den Link, laut https://www.kontopruef.de/mt940s.shtml ist das Jahr ja immer das der Wertstellung. 

Man könnte also das Datum der Wertstellung mit drei möglichen Buchungsdatums (Jahr-1, Jahr, Jahr + 1) vergleichen, und das nehmen welches am dichtesten dran ist. Das wäre aus meiner Sicht das robusteste.

**Comment by ampaze** [comment]
> gibt es in Zeile : 60 ein Buchungsdatum inkl. Jahreszahl, könnte man nicht einfach dieses auslesen?

Habe mal in ein Paar Datensätze von uns geguckt, dort fehlt das Buchungsdatum in :61 und in dem Falle wird dann das Datum aus :60 genommen. Hängt also von der Bank ab ob man in diesem Problem läuft.

**Comment by Magellanth** [comment]
Das robusteste wäre wohl ein Datetime mit der gegebenen Jahreszahl zu erstellen, also zb:
2020-01-01 und 2020-12-30
und dann die Differenz zu betrachten, wenn die größer ist als ein halbes Jahr (ab 183 Tage) dann kann man das Jahr entsprechend der Richtung der Differenz anspassen.

Ich habe eben meine Datenbank mit etwas über 100.000 Buchungen angesehen, die maximale Differenz sind bei mir 48 Tage (Kontoabschlüsse), dann gibts noch Storno und Zinsen bis zu 40 Tage, normale Transaktionen haben max 7 Tage.
Mit besagtem halben Jahr wäre man also weit im sicheren Bereich.

**Comment by ampaze** [comment]
Kannst du mal folgendes ausprobieren? Hab aktuell keine Datensätze mit dem Fall.

```php
if (preg_match('/^\d{4}$/', $bookingDate) === 1) {
    // try to guess the correct year of the booking date

    $valutaDateTime = new \DateTime($valutaDate);

    // the booking day can be before or after the value day
    // and one of them can be in another year
    $bookingDateCandidates = [
        $this->getDate($year . $bookingDate),
        $this->getDate(($year - 1) . $bookingDate),
        $this->getDate(($year + 1) . $bookingDate),
    ];

    $bookingDateCandidateDiffs = [];

    // Calculate the difference of the dates in days
    foreach ($bookingDateCandidates as $bookingDateCandidate) {
        $days = $valutaDateTime->diff(new \DateTime($bookingDateCandidate))->format("%a");
        $bookingDateCandidateDiffs[$days] = $bookingDateCandidate;
    }

    // Sort, lowest day difference first
    ksort($bookingDateCandidateDiffs, SORT_NUMERIC);

    $bookingDate = reset($bookingDateCandidateDiffs);
} else {
    // if booking date not set in :61, then we have to take it from :60F
    $bookingDate = $soaDate;
}
```

**Comment by Magellanth** [comment]
Hat funktioniert, ich würde es so vorschlagen (auch getestet):

```php
$year = substr($transaction, 0, 2);
$valutaDate = $this->getDate($year . substr($transaction, 2, 4));

if (preg_match('/^\d{4}$/', substr($transaction, 6, 4)) === 1) {
    // try to guess the correct year of the booking date

    $valutaDateTime = new \DateTime($valutaDate);
    $bookingDateTime = new \DateTime($this->getDate($year . substr($transaction, 6, 4)));

    // the booking day can be before or after the value day
    // and one of them can be in another year
    $diff = $valutaDateTime->diff($bookingDateTime);

    //if diff is more than half a year
    if($diff->days > 182){
        //and positive
        if($diff->invert === 0){
            //its in the last year
            $year--;
        }
        //and negative
        else {
            //its in the next year
           $year++;
        }

    }
    $bookingDate = $this->getDate($year . substr($transaction, 6, 4));

} else {
    // if booking date not set in :61, then we have to take it from :60F
    $bookingDate = $this->soaDate;
}
```

**Comment by ampaze** [comment]
Kann @nemiah entscheiden. Es fühlt sich irgendwie willkürlich an auf ein halbes Jahr zu prüfen, aber es kommt wohl am Ende aufs gleiche raus.

**Comment by nemiah** [comment]
Keine Ahnung, ob es so passt. Einfach PR schicken, mergen und schauen, was passiert :wink: 
Ich verstehe auch nicht, warum das Datum in erster Linie so komisch ist :woman_shrugging:

**Comment by djm03** [comment]
siehe auch #62

**Comment by Magellanth** [comment]
Ich hab mal den pull request erstellt.

@ampaze Ja das halbe Jahr ist ja nichts anderes als "näher dran" und laut meiner Datenbasis aus 12 Jahren gab es keinen einzigen Fall der auch nur 2 Monate auseinander lag, insofern sollte der Sicherheitspuffer groß genug sein.

**Comment by ampaze** [comment]
Wurde durch #202 gefixt. Kann also zu hier.
