### ISSUE TITLE
Cant exeute direct debit

### ISSUE THREAD

**Issue by daidonpah** [nemiah/phpFinTS#2]
Hey nemiah, great work on this module. If you could help me out for a moment: some classes don't seem to be included anymore. E.g. SEPADirectDebitBasic. I first got the error 

Uncaught Error: Class 'nemiah\phpSepaXml\SEPADirectDebitBasic' not found

and I then realized that I cannot find it myself.

Or maybe I'm just doing something really wrong.
Regards

**Comment by nemiah** [comment]
Hello @daidonpah the classes should be downloaded when installing with composer but it looks like this is not working.
You can find them in this repo: https://github.com/nemiah/phpSepaXml

Best wishes,
Nena

**Comment by daidonpah** [comment]
Thank you!
