### ISSUE TITLE
Sollte BaseAction den Text zum Rückmeldungscode 20 extrahieren und der Anwendung verfügbar machen?

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#205]
Z.B. 0020::*SEPA-Einzelüberweisung erfolgreich

würde ich evtl. dem Endnutzer anzeigen wollen. Aber nur `BaseAction::processResponse` kommt da einfach ran. D.h. der Rückmeldungscode müsste dort extrahiert werden und in der Action gespeichert werden.

Was meint ihr? Inbesondere @Philipp91

**Comment by Philipp91** [comment]
Also ein neues Feld `BaseAction::$successMessage`, das von `processResponse()` gefüllt wird? Klingt sinnvoll.

**Comment by ampaze** [comment]
Genau. Okay, dann würde ich das mal testweise einbauen.
