### ISSUE TITLE
Reaktion bei Tippfehler in der TAN

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#206]
Ich hatte es bislang so implementiert, dass bei Fehler 9941 (TAN ungültig) die TAN erneut beim Nutzer abgefragt wird und dann mit der bestehende Challenge erneut an die Bank geschickt wird.

Z.B. bei GLS

> 9941::TAN ungültig. Bitte richtige TAN eingeben.

Allerdings handhabt das Postbank anders. Dort heißt es

> 9941::Die mobileTAN ist nicht korrekt. Bitte reichen Sie Ihren Auftrag erneut ein.

Gibt es eine Möglichkeit diese Fälle zu unterscheiden?

In den `ParameterZweiSchrittTanEinreichung` oder `VerfahrensparameterZweiSchrittVerfahren` hab ich keine Infos der Bank dazu gefunden.

Allerdings sendet Postbank in diesem Falle im Gegensatz zur GLS ein `HITAN` Segment mit. Ich bin mir aber nicht sicher ob jede `HITAN` Antwort der Bank quasi die betreffende Challenge beendet?

(Ich hab jetzt auch nicht probiert was passiert wenn ich bei der GLS immer wieder die falsche TAN eingebe... dann müsste ja theoretisch irgendwann auch die Challenge beendet werden.)

**Comment by Philipp91** [comment]
Habe das mal mit der Consorsbank getestet. Wenn ich beim Login eine falsche TAN eingebe, kommt:

> HIRMG:2:2:+9050::Nachricht teilweise fehlerhaft.'HIRMS:3:2:3+9941::TAN ungültig.'

Wenn ich es dann einfach nochmal mit der richtigen TAN versuche, kommt:

> HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9010::Unerwartete Nachrichtennummer. Bitte melden Sie sich erneut an.'

Sprich gleich bei der falschen TAN hat die Bank den ganzen Dialog/Session verworfen, das aber nicht explizit mitgeteilt. Das ist allerdings beim Login, vielleicht verhält es sich bei Überweisungen anders.

Wenn wir mal davon ausgehen, dass dieser Fall recht selten vorkommt, würde ich sagen, es schadet nicht, einfach davon auszugehen, dass man nochmal von vorne anfangen muss? Sprich einfach nochmal `->execute()` aufzurufen dürfte auch bei der GLS nicht schaden -- es ist ja nicht so, dass die Überweisung dann doppelt ausgeführt wird.

**Comment by ampaze** [comment]
Da dies nicht nur bei Überweisungen sondern auch bei (Sammel-)Lastschriften zum tragen kommt, würde ich gerne vermeiden unnötig riesige Datenmengen erneut zur Bank zu schicken. So es sich denn vermeiden lässt.

Was hälst du von (in FinTsNew::submitTan)
```php
// Execute the request.
$response = $this->sendRequestForAction($action, $request);
if ($response === null) {
    // If the bank sends HITAN with process type == 2 then the TAN Request is no longer valid.
    // In case of an error, this helps to differentiate if we can try sending the TAN again or not
    $response = $action->getError()->getResponse();
    /** @var HITANv6 $hitan */
    $hitan = $response->findSegment(HITANv6::class);
    if ($hitan !== null && $hitan->tanProzess === 2 && $hitan->auftragsreferenz === $tanRequest->getProcessId()) {
        $action->setTanRequest(null);
    }

    return; // Error occurred and was written to $action.
}
```

Und in der Anwendung

```php
if ($actionError->hasError(Rueckmeldungscode::TAN_UNGUELTIG)) {
    // Manche Banken erlauben es, die TAN erneut einzugeben
    if (!is_null($action->getTanRequest())) {
```

**Comment by Philipp91** [comment]
> vermeiden unnötig riesige Datenmengen (d.h. XML mit 500 Lastschriften) erneut zur Bank zu schicken

Ich vermute mal, wir reden hier über 500KB? In Zeiten von Netflix lohnt es sich nicht, darüber nachzudenken.

Mehr Code heißt immer mehr Wartungsarbeit und mehr verschiedene Ausführungspfade, die versehentlich kaputt gehen können (oder ein weiter Integration-Test, den man nur dafür pflegen muss). Zudem müsste ja auch die Anwendung mit der eher überraschenden Situation klarkommen, dass nach der Eingabe einer TAN gleich eine weitere fällig ist.

Ich würde sagen, ein paar verschwendete MB in dem dann doch eher seltenen Fall, dass sich der Nutzer bei der TAN vertippt, sind das deutlich kleinere Übel.

**Comment by ampaze** [comment]
Mit den Datenmengen kann ich deinen Standpunkt verstehen, aber es ist eigentlich ähnlich wie BPD immer abfragen oder lokal speichern. Es ist im Sinne der Spec es nicht jedes mal abzufragen.

Genauso würde ich sagen, dass man auf die Bank reagieren sollte wenn die sagt "schick die TAN bitte nochmal korrekt" anstatt einfach neu anzufangen. Hängt womöglich auch wieder von der Bank ab ob man evtl. nur einen Auftrag der auf TAN wartet offen haben darf. Wer weiß das schon.

Die Anwendung muss sowieso damit klar kommen, dass die TAN abgelehnt wurde. Wie genau kann die Anwendung ja entscheiden. Ich würde es aber schon im Bereich der Library sehen den Entwickler der Anwendung so gut es geht es dabei zu unterstützen. 

`ServerException::indicatesBadTan` geht dabei ja genau in die Richtung. Aber z.B. Sparda benutzt diese Rückmeldungscodes nicht. Sondern

> 'HIRMS:4:2:3+9130::TAN muss aus genau 6 Ziffern bestehen'
'HIRMS:4:2:3+9130::Diese TAN-Nummer ist ungültig bzw. nicht vorhanden. Bitte ändern Sie Ihre Eingab'
'HIRMS:4:2:3+9040::Diese TAN-Nummer ist ungültig. Bitte ändern Sie Ihre Eingabe. Beim nächsten Fehl'

_(ja die abgeschnittenen Meldungen sendet Sparda so...)_

Es wäre also durchaus gut wenn man sich nicht auf die Rückmeldungscodes verlassen müsste. Mein Ansatz dafür war, auf die HITAN zu gucken bzw. dich zu fragen ob dir noch was schlaues einfällt oder was die Spezifikation vlt hergibt.

> Mehr Code heißt immer mehr Wartungsarbeit und mehr verschiedene Ausführungspfade, die versehentlich kaputt gehen können

Grundsätzlich richtig, aber in diesem Falle ist ja der Extra Code ja nur nötig weil du es so implementierst hast, dass die Response bei Fehler nicht zurückgeliefert wird.
Diese Prüfung kann z.B. auch in Response oder HITAN ausgelagert werden.

**Comment by Philipp91** [comment]
> aber es ist eigentlich ähnlich wie BPD immer abfragen oder lokal speichern

Da gibt es schon noch deutliche Unterschiede. Erstens sind es zwei Requests an den Server (BPD anonym, dann Kundensystem-ID separat) und zweitens verbrauchen die auch Zeit, nicht nur Datenvolumen. Wohingegen man bei einer falsch eingegebenen TAN ja so oder so genau einen weiteren Request machen muss.

> Genauso würde ich sagen, dass man auf die Bank reagieren sollte wenn die sagt "schick die TAN bitte nochmal korrekt" anstatt einfach neu anzufangen. Hängt womöglich auch wieder von der Bank ab ob man evtl. nur einen Auftrag der auf TAN wartet offen haben darf. Wer weiß das schon.

Das stimmt. Und/oder ob es auf den "Fehlversuche"-Zähler geht, wenn man die TAN nicht eingibt (was dann nach der Falscheingabe schon der zweite Fehlversuch sein könnte).

> Mein Ansatz dafür war, auf die HITAN zu gucken bzw. dich zu fragen ob dir noch was schlaues einfällt oder was die Spezifikation vlt hergibt.

Wir können es gerne versuchen, es ist aber schon ein bisschen Spekulation. Mir fällt dazu leider nichts ein, die Spezifikation schweigt sich aus (bis auf die Tatsache, dass mehrere Falscheingaben zu Sperren vom TAN-Generator bzw. dem Zugang führen können). Vielleicht können wir herausfinden, wie andere Anwendungen das handhaben.

> Grundsätzlich richtig, aber in diesem Falle ist ja der Extra Code ja nur nötig weil du es so implementierst hast, dass die Response bei Fehler nicht zurückgeliefert wird. Diese Prüfung kann z.B. auch in Response oder HITAN ausgelagert werden.

Ja, wir können gerne den Code so umstellen, dass es insgesamt besser aussieht. Schauen wir uns erstmal an, auf welcher Grundlage wir die beiden Fälle unterscheiden können/wollen, also woran die Bibliothek am besten feststellt, dass eine weitere TAN-Eingabe gefragt ist. Wenn es wirklich das `HITAN`-Segment ist, dann kann ich mir nochmal genauer anschauen, wo man es geschickt implementieren kann. Ganz ohne zusätzlichen Code kommt sicherlich keine Lösung aus, denn es braucht ja mindestens eine Schnittstelle um der Anwendung diesen Umstand mitzuteilen. Erst dachte ich, dass wir uns das inklusive der Schnittstelle sparen können, aber ich denke du hast Recht und wir sollten es unterstützen, um nicht die Fehlversuche zu erhöhen.

**Comment by ampaze** [comment]
> Wir können es gerne versuchen, es ist aber schon ein bisschen Spekulation. 
Vielleicht können wir herausfinden, wie andere Anwendungen das handhaben.

Ja es ist frickelig, ich kann mal schauen welche quelloffenen Anwendungen mit Quellcode den ich verstehen kann ich finde.

Meine Hypothese, dass die HITAN immer das Ende eine Challenge anzeigt, konnte ich selbst entkräften. Wir hatten einen Fall wo der Lastschriftsammler nach korrekter TAN aus inhaltlichen Gründen abgelehnt wurde. Da hat die GLS u.a. folgendes geantwortet

> 9010::*SEPA-Sammellastschrift fehlerhaft. Auftrag abgelehnt.
> 0900::*TAN entwertet.

Aber kein HITAN-Segment mitgeschickt.

Also bis jetzt würde ich festhalten
`Rueckmeldungscode::TAN_UNGUELTIG` + HITAN vorhangen = kein weiterer Versuch möglich.

**Comment by ampaze** [comment]
Ich überlege gerade ob die "Hilfestellung" des Entwicklers so aussehen könnte, dass bei erkannter Fehleingabe mit Möglichkeit zur Neueingabe, statt `ServerException` wieder eine `TanRequiredException` geworfen wird. 

An der `TanRequiredException` oder dem `TanRequest` könnte es einen Try Counter geben und  die Nachricht der Bank (initial also z.B. "Auftrag empfangen - Sicherheitsfreigabe erforderlich" und dann evtl. "TAN muss aus genau 6 Ziffern bestehen") zusätzlich zum Challenge-Text.
