### ISSUE TITLE
Alte API: Typo (?)

### ISSUE THREAD

**Issue by Naugrimm** [nemiah/phpFinTS#208]
Zumindest bei der Ostsächsischen Sparkasse kann ich mit 2.0.0 keinen Login durchführen.

Der HBCI Fehler ist:

9930: Kein gültiges Sicherheitsprofil.

https://github.com/nemiah/phpFinTS/blob/65f07cf9e5a7c8ca931537cc6e74babff4acec94/lib/Fhp/FinTs.php#L660-L666

In Zeile 663 soll es vermutlich heißen `$this->tanMechanism`. Jedenfalls funktioniert der Login, wenn ich das ändere. 

Einen Pull-Request kann ich gern machen, sobald das vielleicht jemand noch mit ein paar anderen Banken getestet hat.

Sollte die alte API nicht mehr gepflegt werden sollen, spart das Issue vielleicht ein paar Leuten wenigstens Zeit bei der Fehlersuche :)

**Comment by ampaze** [comment]
Dein vorgeschlagener Fix klingt sinnvoll, mach gerne einen Pull Request.

Zum tragen kommt dies aber nur weil du keinen Tan Mechanismus an `->login` übergibst und dann der einzig Verfügbare benutzt wird. Dieser braucht aber scheinbar einen Tan Medium Namen.

Den musst du bei  `->login` mit angeben und in dem Falle solltest du auch den Tan Mechanismus mit angeben. Nur wird einem die Nummer des Mechanismus nicht angezeigt wenn es nur einen gibt ... 🤔 

Wenn du neu mit der Implementation anfängst, würde ich dir empfehlen mit FinTsNew zu arbeiten.
