### ISSUE TITLE
Allgemeines

### ISSUE THREAD

**Issue by masterix83** [nemiah/phpFinTS#211]
Hallo Zusammen,
mir fehlen leider entsprechende Programmierkenntnisse und ich finde keine detailierte Beschreibung (wahrscheinlich für Profis auch nicht nötig).
Ich würde gerne Kontostände und Umsätze abrufen. Sehe ich das richtig, dass es aufgrund von PSD2 nicht mehr ausreicht, einfach nur die Zugangsdaten zu verwenden? Wie geht man mit der Eingabe der TAN um? Ist es korrekt, dass ich ohne Zwei-Faktoren-Authentifizierung gar nicht mehr an die Daten rankomme? Bisher habe ich fints-hbci-php von Schindler verwendet, was sehr gut funktioniert hat. Danke für eine kurze Info.

**Comment by Philipp91** [comment]
> Ich würde gerne Kontostände und Umsätze abrufen. Wie geht man mit der Eingabe der TAN um?

Siehe [hier](https://github.com/nemiah/phpFinTS/blob/master/SamplesNew/statementOfAccount.php)

> Sehe ich das richtig, dass es aufgrund von PSD2 nicht mehr ausreicht, einfach nur die Zugangsdaten zu verwenden? Ist es korrekt, dass ich ohne Zwei-Faktoren-Authentifizierung gar nicht mehr an die Daten rankomme?

Bei den meisten Banken braucht man früher oder später eine TAN. Aber bei einigen Banken braucht man nicht jedes Mal, sondern nur ein Mal im Quartal eine TAN.
