### ISSUE TITLE
Zusätzliche Meldungen der Bank bei TAN Request berücksichtigen

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#217]
Ich würde gerne Hinweise der Bank bei einem TAN Request verwerten können.

Beispiel Sparda:

```
'HIRMS:4:2:4+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich
'HIRMS:5:2:3+3040::Bei Nicht-Eingabe von 4 angeforderten mTANs binnen 30 h wird Ihr Zugang gesperrt'
```

Diese Informationen werden verworfen, da FinTsNew nur das HITAN-Segment rausfischt und an  die Action schreibt. 

Wäre es nicht sinnvoll bei der Action alle Responses die es dazu gab auch zu speichern? Wegen mir auch nur die letzte. Oder aber die ganze Response wird als TanRequest betrachtet und an die Action geschrieben.

----

Zusatzhinweis: 3040 ist als `Rueckmeldungscode::PAGINATION` deklariert. Bin mir nicht sicher ob das so pauschal korrekt ist. Es müsste wohl eher `ADDITIONAL_INFORMATION_AVAILABLE` sein und nur als Paginierung gewertet werden wenn auch ein Token dafür dabei ist. Vlt macht es aber auch die Sparda falsch.

**Comment by Philipp91** [comment]
> Zusatzhinweis: 3040 ist als Rueckmeldungscode::PAGINATION deklariert. Bin mir nicht sicher ob das so pauschal korrekt ist. Es müsste wohl eher ADDITIONAL_INFORMATION_AVAILABLE

Ok. Können wir umbenennen, oder eine zweite Konstante mit demselben Wert erstellen -- dann erkennt man an der jeweiligen Code-Stelle, mit welcher Intention die Konstante da verwendet wird.

> Wäre es nicht sinnvoll bei der Action alle Responses die es dazu gab auch zu speichern?

Ich würde es nicht in der Action speichern, sondern im `TanRequest`. Vermutlich brauchen wir dann eine `TanRequestImpl` oder wir machen `TanRequest` selbst zur Klasse. Darin kann man dann `$hitan` speichern (und die drei Getter darauf zugreifen lassen; `HITAN` selbst implementiert das Interface dann nicht mehr), sowie weitere Informationen wie eben dieses `HIRMS`-Segment.

> Vlt macht es aber auch die Sparda falsch.

Weiß nicht, ich haben solche Zusatzinformationen bei meinen beiden Banken jedenfalls noch nie gesehen.
