### ISSUE TITLE
TAN bei Login (Consorsbank SecurePlus)

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#22]
Dank PSD2 müssen viele Banken jetzt/bald auch beim Login eine TAN verlangen. Manche verlangen sie immer, andere nur manchmal. Im Fall der Consorsbank ist die TAN nur von der Uhrzeit abhängig, kann also ohne Challenge generiert werden bevor die phpFinTS-Bibliothek überhaupt das erste Mal aufgerufen wird. Bei anderen Banken könnte das anders sein. Denkbar wäre zum Beispiel nur ein Bestätigen auf dem Smartphone (so ist es bei der DKB, wenn man es entsprechend einrichtet), oder die Eingabe eines Challenge-Codes bevor die TAN generiert wird.

Mit der Consorsbank erhalte ich aktuell die Meldung "HIRMS:4:2:4+0020::Informationen fehlerfrei entgegengenommen.+3050::BPD nicht mehr aktuell. Aktuelle Version folgt.+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer:900:999" aus `syncDialog()`. Dann versucht phpFinTS einfach, seine normale Anfrage zu schicken, woraufhin der Server verständlicherweise abbricht mit "HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9120::Unerwartete Nachricht."

Die Umstellung scheint noch nicht abgeschlossen: https://twitter.com/consorsbank/status/1170984484960968704

**Comment by nemiah** [comment]
Hallo,

bei mir funktioniert im Moment noch alles, deswegen habe ich noch keine Möglichkeit, die neue Funktionalität einzubauen und zu testen.

Liebe Grüße
Nena

**Comment by roben** [comment]
Bei der Postbank gehts jetzt auch los:

```
[HIRMS] Auftrag ausgeführt.
[HIRMS] BPD nicht mehr aktuell. Aktuelle Version folgt.
[HIRMS] Meldung unterstützter Ein- und Zwei-Schritt-Verfahren
[HIRMS] Starke Authentifizierung ab dem 2019-09-08 erforderlich.
Received system id: XXXX
Received dialog id: YYYY
Supported TAN mechanisms: 930
```

Und dann direkt:

```
[HIRMS] Dialog bereits geschlossen.
[HIRMS] Dialog ungueltig/unbekannt.
```

Bei der Postbank gab es übrigens noch einen Fehler beim Auslesen aller HIRMS-Meldungen. Ich mache ein eigenes Issue dafür auf.

**Comment by DkDavid** [comment]
Ebenfalls Postbank und kein Login mehr möglich. 
Es scheint das Feld HKTAN notwendig zu sein. Leider werden alle meiner Versuche das Feld hinzuzufügen als "Ungültiger Wertebereich" zurückgegeben.
HKTAN+6+4+HKIDN+IBAN:BLZ+++BestSign

**Comment by devil2035** [comment]
Hier auch Postbank... Kann ich irgendwie sinnvoll zum debuggen beitragen? Ich hab leider nicht wirklich Ahnung vom FinTS Protokoll selbst.

**Comment by nemiah** [comment]
Hallo zusammen,

ein Kunde von mir meinte, die Postbank hat vorsorglich HBCI mal ganz abgestellt.
Keine Ahnung, ob das stimmt, aber solange keine meiner Banken die Umstellung macht, kann ich das Login-Problem leider nicht angehen.

Liebe Grüße
Nena

**Comment by devil2035** [comment]
Also an der Kundenhotline (Postbank) wurde meiner Kollegin gesagt sie soll das Programm doch einfach nochmal neu einrichten. Das HBCI abgestellt worden wäre ist nicht erwähnt worden. Bei der Postbank würde mich das jetzt aber auch nicht wirklich überraschen.

Liebe Grüße
Patrick

**Comment by sirozzy** [comment]
Hallo Kollegen,
auch ich habe jetzt ein Problem mit der Postbank und den 3 Fehlermeldungen:

            [9999] => Dialog bereits geschlossen.
            [9800] => Dialog ungueltig/unbekannt.
            [9050] => Teilweise fehlerhaft.

Falls jemand da schon eine funktionierende  Lösung hat, würde mich das sehr interessieren.

Viele Grüße
Frank

**Comment by timrasche** [comment]
Ebenfalls hier:

- Request Failed: Pflichtfeld nicht gefunden (9160)
- Die Nachricht enthält Fehler. (9050)
- Dialog abgebrochen (9800)

Bereits beim eröffnen der Verbindung seit gestern.

**Comment by nemiah** [comment]
Duplicate of #20
