### ISSUE TITLE
Travis-Integration reparieren

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#220]
Scheint sich von alleine verabschiedet zu haben. In meinem eigenen Repository ging es auch nicht mehr. Dann habe ich folgendes gemacht:

1. In den Repository-Einstellungen bei "Webhooks" den Travis rausgelöscht.
2. Im [Travis-Profil](https://travis-ci.com/profile/) auf der "neuen" Travis-Seite (travis-ci.com) auf "Activate and Migrate" geklickt und die folgenden Assistenten durchgeklickt, u.a. mit GitHub-Passwort bestätigt, dass die Travis-App auf das (eine) Repository zugreifen darf.
3. Auf der "alten" [Seite](https://travis-ci.org/account/repositories) (travis-org.com) auf "Sign up for the beta" geklickt. Auf E-Mail gewartet und dort den Migrieren-Button angeklickt und den Assistent durchgeklickt.
4. Auf der [neuen Seite](https://travis-ci.com/account/repositories) geprüft, dass das Repository auch wirklich da ist.

Alle ab dann frisch erstellten Pull Requests wurden getestet und der heute aufgetretene Fehler wurde wie erwartet [gefunden](https://github.com/Philipp91/fints-hbci-php/pull/10/checks?check_run_id=391909879).

@nemiah Wenn du die paar Klicks auch machen könntest, müsste es auch bei dir wieder funktionieren. Ich weiß natürlich nicht, für wieviele andere Projekte du gleichzeitig Travis eingerichtet hast, evtl. wäre es deswegen für dich etwas mehr Arbeit. Wobei die Migration im Grunde für alle gleichermaßen problemlos funktionieren sollte.

**Comment by nemiah** [comment]
Für meine Software brauche ich sowas nicht, ich teste immer alles und dann testen die "Auftraggeber" :grin: 
Ich hab mich mal durchgeklickt, aber k.A. ob es jetzt funktioniert…

**Comment by Philipp91** [comment]
Yep, läuft, wie man an https://github.com/nemiah/phpFinTS/pull/221 sehen kann. Natürlich schlägt es fehl, weil https://github.com/nemiah/phpFinTS/issues/219 noch nicht gefixt ist, also funktioniert Travis genauso, wie es soll.

**Comment by ampaze** [comment]
Code Styles werden inzwischen auch wieder einige angemeckert. Wer will das beheben 😁 

Sonst werden ja alle zukünftigen PR fehlschlagen.

**Comment by Philipp91** [comment]
Kann ich machen.

**Comment by nemiah** [comment]
Ist ja eigentlich nur `php composer.phar cs-fix` ausführen, oder?

**Comment by Philipp91** [comment]
Erledigt: https://github.com/nemiah/phpFinTS/pull/224
