### ISSUE TITLE
Action: SendSEPADirectDebit - missing support of "COR1"

### ISSUE THREAD

**Issue by fbett** [nemiah/phpFinTS#228]
It is possible to reduce the lead time by declaring "COR1" instead of "CORE" for basic direct debits.
In that case, the bank expects a HKDSC segment.

Currently the action "SendSEPADirectDebit" supports HKDME and HKDSE.
The "old" version supports "COR1".

**Comment by Heart1010** [comment]
COR1 is "dead", isn't it? Use CORE instead (with the shorter submitter time from COR1)

**Comment by fbett** [comment]
Oh, it is. Thanks!

**Comment by ampaze** [comment]
Can confirm that COR1 is dead. You can get the shortest Lead Time your Bank supports, with the GetSEPADirectDebitParameters Action. It can be the next (Target2) day, when you send it before 1pm for example.

**Comment by Heart1010** [comment]
> Can confirm that COR1 is dead. You can get the shortest Lead Time your Bank supports, with the GetSEPADirectDebitParameters Action. It can be the next (Target2) day, when you send it before 1pm for example.
...here next day possible when sending it before 10am
