### ISSUE TITLE
Postbank Dialog Initialisierung Unexpected TAN request

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#229]
Es ist wieder soweit, die Postbank möchte eine TAN beim anmelden. Scheinbar macht die Postbank dies aber wieder anders als üblich: 

Der Dialog wird erfolgreich initialisiert, enthält aber einen Hinweis 

> Vorläufige Sperre liegt vor. Entsperren mit GV 'PIN-Sperre aufheben' möglich.

und eben den TAN Request den FinTsNew nicht erwartet.

```
HNHBK:1:3+000000000858+300+3757655120271000dKEuch*n5O.A11+1+3757655120271000dKEuch*n5O.A11:1'
HNVSK:998:3+PIN:1+998+1+2::37576551205470006XJ99SAQ5E5XU2+1:20200128:100520+2:2:13:@8@:5:1+280:<PRIVAT>:<PRIVATE__>:V:0:0+0'
HNVSD:999:1+@602@HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:2+3931::Vorläufige Sperre liegt vor. Entsperren mit GV ?'PIN-Sperre aufheben?' möglich.'HIRMS:4:2:3+0020::Information fehlerfrei entgegengenommen.'HIRMS:5:2:4+3920::Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:912:913:920:930'
HIRMS:6:2:5+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich'
HIRMS:7:2:6+0020::Auftrag ausgeführt.'
HISYN:8:4:6+37576551205470006XJ99SAQ5E5XU2'HITAN:9:6:5+4++QRYO81XS0EXFE20200128100520470+mobileTAN über Mobilfunknummer mT?:<PRIVAT_>+++mT?:<PRIVAT_>''HNHBS:10:1+1'
```

Die Bankingsoftware Banking4 erkennt diesen Fall aber auch nicht, schickt die TAN hin und kriegt dann wieder den Hinweis.

```
HNHBK:1:3+000000000503+300+3757660785234000sBFxMAsSF9.B11+2+3757660785234000sBFxMAsSF9.B11:2'
HIRMG:2:2+9075::Dialog abgebrochen - starke Authentifizierung erforderlich.+9050::Teilweise fehlerhaft.'
HIRMS:3:2:2+3931::Vorläufige Sperre liegt vor. Entsperren mit GV ?'PIN-Sperre aufheben?' möglich.'
HITAN:4:6:3+2++NGAUMMA5R9JFA20200128113945373'
HNHBS:5:1+2'
```

Was ich momentan nicht sagen kann, ist ob die Postbank das jetzt generell so macht nach den 90 Tagen oder ob ein spezieller Grund für die Sperrung vorliegt. Darüber wird man ja nicht informiert.

Falls man den Fall abdecken muss, würde ich es so verstehen, dass statt `HKTAN` der GV `HKPSA` geschickt werden muss.

----

Dies ist evtl. auch in #200 und #124 das Problem.

**Comment by Philipp91** [comment]
Klingt eher so, als wäre dein Zugang gesperrt, möglicherweise wegen
vorangegangenen fehlgeschlagenen oder ignorierten TAN-Anfragen.

ampaze <notifications@github.com> schrieb am Di., 28. Jan. 2020, 12:02:

**Comment by ampaze** [comment]
Mag so aussehen, aber die letzte Kommunikation mit der Postbank war fehlerfrei.

**Comment by Philipp91** [comment]
> den TAN Request den FinTsNew nicht erwartet

Inwiefern nicht erwartet? Wird stattdessen eine Exception geworfen oder so? Ideal wäre es, wenn du einen Integration-Test bauen könntest, der das Problem reproduziert. Das `HITAN`-Segment ist da und die Bibliothek sollte in der Lage sein, es in die Action zu schieben, die gerade ausgeführt wird.

**Comment by ampaze** [comment]
Unerwartet weil keine KundensystemId zurückkommt.

```php
if ($this->bpd === null || $this->kundensystemId === null) {
                throw new UnexpectedResponseException('Unexpected TAN request');
            }
```

Die Prüfung auf KundensystemId ist aber noch an einigen weiteren Stellen.

Ich kann mir morgen noch mal den ganzen Log von Banking4 angucken, der hat ja entweder die Kundensystem-Id nicht gebraucht zum TAN senden oder irgendwie eine gehabt.

**Comment by ampaze** [comment]
Hab mich geirrt, die Bank sendet die KundensystemId (`HISYN`) doch, dann muss ich erstmal gucken warum die Exception überhaupt geschmissen wurde. Das würde ja heißen das entweder BPD oder KundensystemId nicht korrekt aus der Antwort der Bank ermittelt wird.

**Comment by Philipp91** [comment]
Ok. Also sind wir jetzt wieder vor der Frage, ob die Postbank wirklich einen schwach authentifizierten Dialog initialisieren kann oder nicht. Beim letzten Mal in einem der anderen Bugs sah es irgendwie so aus, als würde es funktionieren. Aber möglicherweise ging es damals doch nicht wirklich und die TAN-Freigabe war schon durch. Das heißt aber nicht, dass es gar nicht geht.

Im `SYNC_REQUEST` senden wir derzeit in `HNSHK` die Angabe `PIN:2+930`. (Übrigens nicht verwirren lassen, in `HNVSK` gibt es auch eine `PIN:x+yyy` Sequenz, aber da ist `yyy=998` fix und das `x` muss einfach mit `HNSHK` übereinstimmen, also kommt es letztlich auf `HNSHK` an.) Das bedeutet, dass ein Zweischritt-Verfahren angefordert wird. Das ist für eine schwache Authentifizierung zwar auch erlaubt (die Bank _muss_ ja nicht nach einer TAN fragen nur weil sie weiß, mit welchem TAN-Verfahren sie das tun _könnte_), aber vielleicht verwirrt das die Postbank. Vielleicht wäre es besser, wenn wir da `PIN:1+999` schicken.

Funktioniert es, wenn du:
1. Die `FinTsNew`-Instanz frisch erstellst und _kein_ TAN-Verfahren angibst.
2. `ensureSynchronized()` aufrufst (dazu kannst du es `public` machen oder `getTanModes()` aufrufen).
3. (Jetzt wäre hoffentlich eine Kundensystem-ID da ohne dass nach einer TAN gefragt wurde.)
4. Das TAN-Verfahren angibst mit `selectTanMode()` und dann normal `login()` machst, jetzt wo die Kundensystem-ID da ist?

Bitte alle Nachrichten aufzeichnen. Wenn es so funktioniert, können wir die Bibliothek so abändern, dass sie immer `999` zur schwachen Synchronisierung verwendet, dann müsste dein frisch aufgezeichneter Integration-Test für die Postbank funktionieren auch ohne dass man die oben beschrieben umständliche Aufrufreihenfolge macht. Dann müssen wir schauen, ob es mit den anderen Banken weiterhin funktioniert (kann ich für DKB und Consors machen).

**Comment by ampaze** [comment]
Wir haben die PIN mittlerweile der Einfachheit halber über die Webseite entsperrt. Mit der PIN-Sperre aktiv kann ich es vermutlich also in ca 90 Tagen wieder testen.

Aber ich verstehe nicht ganz warum die von dir beschriebenen Änderungen für den im Integration-Test festgehaltenen Fall nötig wären. Da ist doch das Problem, dass die gelieferte Kundensystem-ID nicht berücksichtigt wird, weil erst geprüft wird und die Zuweisung erst später passiert.

Oder hab ich was übersehen? Hast du den Integration-Test mal laufen lassen?

**Comment by Philipp91** [comment]
> Da ist doch das Problem, dass die gelieferte Kundensystem-ID nicht berücksichtigt wird, weil die Prüfung vor der Zuweisung passiert.

Das stimmt. Aber wenn man das Problem lösen würde indem man die Kundensystem-ID einfach wegspeichert, dann hätte man weiterhin das Problem (das habe ich mit dem Integration-Test rausgefunden), dass man in `executeWeakDialogInitialization()` ist und einen TanRequest bekommt. Die Funktion ruft aber `$dialogInitialization->ensureSuccess()` auf ohne vorher auf TanRequest zu prüfen, was meiner Meinung nach auch gerechtfertigt ist. Denn wenn man einen schwach authentifizierten Dialog initialisiert, sollte man nicht nach einer TAN gefragt werden, denn TANs sind ja gerade für starke Authentifizierung da.

Aber vielleicht ist das mit PIN-*Sperre* nochmal was anderes.

**Comment by ampaze** [comment]
Dein Ziel wäre es also quasi den TAN-Request auf später zu verschieben, beim richtigen Init? Wenn ich mich recht erinnere hab ich es für die alte Implementation auch so gemacht, indem beim Sync 999 verwendet wurde. Müsste also funktionieren.

Dann lass uns doch deinen Vorschlag mit 999 mal implementieren. Reingehackt hab ich es auf die schnelle nicht bekommen, es steht sogar an mehreren Stellen in den PHP Kommentaren, dass `$hktanRef` gleich NULL zu TAN Mode 999 führe würde, das kann ich aber so nicht bestätigen.

> Denn wenn man einen schwach authentifizierten Dialog initialisiert, sollte man nicht nach einer TAN gefragt werden

Ich bin mir nicht sicher ob man bei den Banken danach gehen kann, was logisch wäre ... 😛

**Comment by fbett** [comment]
Das Problem tritt auch bei der Deutschen Bank auf, wenn die Tan erneut eingegeben werden soll.

Pin-Tan Verfahren wurde per $fints->selectTanMode(902) gesetzt nach dem Call des Constructors:
````
> HNHBK:1:3+000000000145+300+0+1'HKIDN:2:2+280:XXIBANXX+9999999999+0+0'HKVVB:3:3+0+0+0+<PRIVATE________________>+1.1'HKTAN:4:6+4+HKIDN'HNHBS:5:1+1'
< HNHBK:1:3+000000004694+300+mM29pFa3LX0I20200210232229650%+1+mM29pFa3LX0I20200210232229650%:1'HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+0010::Nachricht entgegengenommen.'HIRMS:3:2:2+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:3+1040::BPD nicht mehr aktuell. Aktuelle Version folgt.+1050::UPD nicht mehr aktuell. Aktuelle Version folgt.'HIBPA:5:3:3+35+280:XXIBANXX+DB24-Filiale+0+1+300+0'HIKOM:6:4:3+280:XXIBANXX+1+2:193.150.167.8::MIM:1+3:https?://fints.deutsche-bank.de/::UUE:1'HISHV:7:3:3+N+RDH:1:9:10+RAH:9:10'HIKPV:8:1:3+6:1'HITANS:9:4:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:1:J:1:0:N:N:N:N:N:00:0:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1::J:1:0:N:N:N:N:N:00:0'HITANS:10:5:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:1:J:1:0:N:0:0:N:N:00:0:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1::J:1:0:N:0:0:N:N:00:0'HITANS:11:6:3+1+1+1+N:N:1:901:2:MTAN:::Mobile-TAN:6:1:mobileTAN:256:J:1:N:0:0:N:N:00:0:N:1:902:2:MS1.0.0:::photoTAN-Verfahren:7:1:Freigabe durch photoTAN:1:J:1:N:0:0:N:N:00:0:N'HIPINS:12:1:3+1+1+1+5:5:6:Benutzerkennung:Kundenkennung:HKCSB:N:HKCCM:J:HKFRD:N:HKDSC:J:HKDMB:N:HKSPA:N:HKCDB:N:DKPSP:J:HKCML:J:HKAUB:J:HKCSL:J:HKBME:J:HKBSA:J:HKBML:J:HKDME:J:HKDMC:J:HKUMB:J:HKBMB:N:HKCMB:N:HKDML:J:HKKAZ:J:HKDSL:J:HKCSA:J:HKBSE:J:HKCDE:J:HKWPD:N:HKBBS:N:HKTAN:N:HKPRO:N:HKDSE:J:HKDBS:N:HKSAL:N:HKCDN:J:HKCCS:J:HKCSE:J:HKBSL:J:HKPSP:J:HKDSA:J:HKCDL:J:HKCME:J'DIPINS:13:1:3+1+1+HKCSB:N:HKCCM:J:HKFRD:N:HKDSC:J:HKDMB:N:HKSPA:N:HKCDB:N:DKPSP:J:HKCML:J:HKAUB:J:HKCSL:J:HKBME:J:HKBSA:J:HKBML:J:HKDME:J:HKDMC:J:HKUMB:J:HKBMB:N:HKCMB:N:HKDML:J:HKKAZ:J:HKDSL:J:HKCSA:J:HKBSE:J:HKCDE:J:HKWPD:N:HKBBS:N:HKTAN:N:HKPRO:N:HKDSE:J:HKDBS:N:HKSAL:N:HKCDN:J:HKCCS:J:HKCSE:J:HKBSL:J:HKDSA:J:HKCDL:J:HKCME:J'HIPSPS:14:1:3+1+1+1'DIPSPS:15:1:3+1+1'HIPROS:16:2:3+20+1'HIPROS:17:3:3+20+1'HIPROS:18:4:3+20+1+1'HIFRDS:19:1:3+20+1'HIKAZS:20:4:3+20+1+90:N'HIKAZS:21:5:3+20+1+90:N:N'HIKAZS:22:6:3+20+1+1+90:N:N'HIKAZS:23:7:3+20+1+1+90:N:N'HISALS:24:3:3+20+1'HISALS:25:4:3+20+1'HISALS:26:5:3+20+1'HISALS:27:6:3+20+1+1'HISALS:28:7:3+20+1+1'HIWPDS:29:2:3+20+1+N'HIWPDS:30:3:3+20+1+N'HIWPDS:31:4:3+20+1+N:N:N'HIWPDS:32:5:3+20+1+N:N:N'HIWPDS:33:6:3+20+1+1+N:N:N'HIUMBS:34:1:3+20+1+4:51:53:54:56:67:69'HIUMBS:35:2:3+20+1+1+4:51:53:54:56:67:69'HIAUBS:36:3:3+20+1+1'HIAUBS:37:4:3+20+1+1'HIAUBS:38:5:3+20+1+1'HIAUBS:39:6:3+20+1+1+1'XIKDMS:40:1:3+20+1+1+20480'HISPAS:41:1:3+20+1+0+N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HISPAS:42:2:3+20+1+0+N:N:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HISPAS:43:3:3+20+1+0+N:N:N:N:0:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'HICCSS:44:1:3+20+1+1'HICSES:45:1:3+20+1+1+0:90'HICSBS:46:1:3+20+1+1+N:N'HICSAS:47:1:3+20+1+1+0:90'HICSLS:48:1:3+20+1+1+J'HICCMS:49:1:3+20+1+1+500:J:J'HICMES:50:1:3+20+1+1+1:90:500:J:J'HICMBS:51:1:3+20+1+1+N:N'HICMLS:52:1:3+20+1+1'HIDSES:53:1:3+20+1+1+1:90:1:90'HIDSCS:54:1:3+20+1+1+1:90:1:90::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIDBSS:55:1:3+20+1+1+N:N'HIDSAS:56:1:3+20+1+1+1:90:1:90'HIDSLS:57:1:3+20+1+1+J'HIBSES:58:1:3+20+1+1+1:90:1:90'HIBBSS:59:1:3+20+1+1+N:N'HIBSAS:60:1:3+20+1+1+1:90:1:90'HIBSLS:61:1:3+20+1+1+J'HIDMES:62:1:3+20+1+1+1:90:1:90:500:J:J'HIDMCS:63:1:3+20+1+1+500:J:J:1:90:1:90::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIDMBS:64:1:3+20+1+1+N:N'HIDMLS:65:1:3+20+1+1'HIBMES:66:1:3+20+1+1+1:90:1:90:500:J:J'HIBMBS:67:1:3+20+1+1+N:N'HIBMLS:68:1:3+20+1+1'HICDES:69:1:3+20+1+1+1:1:360:0102030612:01020304050607080910111213141516171819202122232425262728293099'HICDBS:70:1:3+20+1+1+N'HICDNS:71:1:3+20+1+1+9:1:360:J:J:J:J:J:J:J:J:J:0102030612:01020304050607080910111213141516171819202122232425262728293099'HICDLS:72:1:3+20+1+1+0:0:N:J'HIUPA:73:4:3+9999999999+1+0'HIUPD:74:6:3+9999999999::280:XXIBANXX++9999999999+++anonym'HITAN:75:6:4+4++noref+nochallenge'HNHBS:76:1+1'	
> HNHBK:1:3+000000000113+300+mM29pFa3LX0I20200210232229650%+2'HKEND:2:1+mM29pFa3LX0I20200210232229650%'HNHBS:3:1+2'
< HNHBK:1:3+000000000183+300+mM29pFa3LX0I20200210232229650%+2+mM29pFa3LX0I20200210232229650%:2'HIRMG:2:2+0010::Nachricht entgegengenommen.'HIRMS:3:2:2+0100::Dialog beendet.'HNHBS:4:1+2'
> HNHBK:1:3+000000000412+300+0+1'HNVSK:998:3+PIN:2+998+1+1::0+1:20200210:222229+2:2:13:@8@00000000:5:1+280:XXIBANXX:<PRIVATE___>:V:0:0+0'HNVSD:999:1+@247@HNSHK:2:4+PIN:2+902+8333954+1+1+1::0+1+1:20200210:222229+1:999:1+6:10:19+280:XXIBANXX:<PRIVATE___>:S:0:0'HKIDN:3:2+280:XXIBANXX+<PRIVATE___>+0+1'HKVVB:4:3+35+0+0+<PRIVATE________________>+1.1'HKTAN:5:6+4+HKIDN'HKSYN:6:3+0'HNSHA:7:2+8333954++<PRI>''HNHBS:8:1+1'
< HNHBK:1:3+000000003784+300+fsHM6UTVGz7M20200210232229799%+1+fsHM6UTVGz7M20200210232229799%:1'HNVSK:998:3+PIN:1+998+1+2::37588261501870003VOG1L6F8ZHBFK+1:20200210:232230+2:2:13:@8@:5:1+280:XXIBANXX:<PRIVATE___>:V:0:0+0'HNVSD:999:1+@3527@HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'HIRMS:4:2:4+3920::Meldung unterst?tzter Ein- und Zwei-Schritt-Verfahren:901:902+0010::Auftrag entgegengenommen. Freigabe durch TAN erforderlich.'HIRMS:5:2:5+0030::Auftrag empfangen - Sicherheitsfreigabe erforderlich'HIRMS:6:2:6+0020::Auftrag ausgef?hrt.'HISYN:7:4:6+37588261501870003VOG1L6F8ZHBFK'HITAN:8:6:5+4++M3FGwvsW20200210232229974#LPE#+Bitte geben Sie die photoTan ein+@2987@	image/png??...
````

Tatsächlich wurde das Problem gelöst, indem vor "FinTs::selectTanMode()", "FinTs::getTanModes()" aufgerufen wurde.

**Comment by ampaze** [comment]
@Philipp91 Hast du noch vor TAN Mode 999 umzusetzen?

**Comment by Philipp91** [comment]
Sorry, ich war mit anderen Sachen beschäftigt. Jetzt habe ich es wie vorgeschlagen implementiert: https://github.com/Philipp91/phpFinTS/commit/41272e33fb7e08fb56520e6a3a9dbad8475e60a1 Mit meinen beiden Banken (DKB und Consorsbank) funktioniert es tatsächlich. Für die Postbank habe ich zwar den Integration-Test händisch angepasst, aber es wäre gut, wenn das noch jemand mit der echten Bank testen könnte. Hoffentlich funktioniert es, und vmtl. sehen die Antwortnachrichten ein bisschen anders aus.

Der Code ist noch nicht aufgeräumt, das mache ich morgen.

**Comment by Philipp91** [comment]
@ampaze @fbett @NabilHanna Wäre super, wenn das jemand von euch mal testen könnte.

**Comment by ampaze** [comment]
@Philipp91 Teste ich am Montag! Danke für die Umsetzung.

**Comment by NabilHanna** [comment]
@Philipp91: Habe bei mir soeben upgedated und kann die Norisbank bestätigen.
Ein $fints->login() ohne vorherigem $fints->getTanModes() ist nun problemlos möglich.

**Comment by ampaze** [comment]
Umsatzabruf hat bei GLS, Sparda und Postbank problemlos geklappt.

**Comment by fbett** [comment]
Super. Vielen Dank @Philipp91 für dein Engagement :)

**Comment by Philipp91** [comment]
Danke für's Testen! Wenn ihr die Postbank-Anbindung noch ein bisschen festzimmern wollt könnt ihr die Anfragen/Antworten mitschneiden und anhand eines Diffs mit dem Integration-Test [hier](https://github.com/nemiah/phpFinTS/pull/246/files#diff-d7a638eb185d4007e4cf72bfd17c90afR22) entscheiden, ob der noch ein Update braucht. Aber das TODO kann auch offen bleiben.
