### ISSUE TITLE
Not all HIRMS and HIRMG messages shown

### ISSUE THREAD

**Issue by roben** [nemiah/phpFinTS#23]
`Response::getSummaryBySegment` only searches for the first occurrence of the segment. At least Postbank responses contain more than one HIRMS elements, though. Changing the method as below fixes this issue.

```php
protected function getSummaryBySegment($name)
{
	if (!in_array($name, array('HIRMS', 'HIRMG'))) {
		throw new \Exception('Invalid segment for message summary. Only HIRMS and HIRMG supported');
	}

	$result = array();
	foreach ($this->findSegments($name) as $segment) {
		$segment = $this->splitSegment($segment);
		array_shift($segment);
		foreach ($segment as $de) {
			$de = $this->splitDeg($de);
			$result[$de[0]] = $de[2];
		}
	}

	return $result;
}
```

Sorry for not making a pull request but my own fork of mschindler83/fints-hbci-php would need some serious refactoring in advance.

**Comment by DkDavid** [comment]
@roben 
Sorry, but as you a referring to a connection to the Postbank. Does the connection still work for you since they updated their FinTS implementation two days ago? Im am struggling with the 2-factor authentication which is now necessary even for the login.

**Comment by nemiah** [comment]
Thank you @roben, I already pushed the change

Best wishes
Nena
