### ISSUE TITLE
Uncaught Error: Class 'Fhp\\FinTs' not found

### ISSUE THREAD

**Issue by D3vJust** [nemiah/phpFinTS#231]
Hey,

I'm trying to use this libary, but I always get the same error:
`Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Fhp\\FinTs' not found in /xx/saldo.php:31\nStack trace:\n#0 {main}\n thrown in /xx/saldo.php on line 31\n'`

I installed it via composer and filled out the needed information...

**Comment by D3vJust** [comment]
Hat sich mittlerweile erledigt. Die Libs waren nicht da...

Beim Login (Postbank) bekomme ich im Log aktuell immer folgende Meldungen:
`[HIRMG] 0020: Dialoginitialisierung erfolgreich.
[HIRMG] 3076: Keine starke Authentifizierung erforderlich.
[HIRMG] 3060: Teilweise liegen Warnungen/Hinweise vor.
[HIRMS] 0020: Information fehlerfrei entgegengenommen.
[HIRMS] 1040: BPD nicht mehr aktuell. Aktuelle Version folgt.
[HIRMS] 3920: Meldung unterstÃ¼tzter Ein- und Zwei-Schritt-Verfahren (920, 930)
[HIRMS] 1050: UPD nicht mehr aktuell. Aktuelle Version folgt.`

Ich bekomme keine TAN, obwohl angegeben: `$fints->login(920, "SO:Gerätename");`

Idee, woran es hier liegen könnte?
Kann so auch nicht die SEPA Accounts o.ä. abfragen..

**Comment by ampaze** [comment]
> 3076: Keine starke Authentifizierung erforderlich.

Heißt genau, dass du keine TAN brauchst. Man braucht nicht bei jedem Login eine TAN, nur manchmal.

920 ist Bestsign, je nachdem wie das im Detail funktioniert ist es vermutlich nicht implementiert. 

Würde die außerdem empfehlen FinTsNew zu nutzen, wenn du gerade neu anfängst damit.

**Comment by D3vJust** [comment]
@ampaze 

Okay danke.. bin jetzt FinTsNew am nutzen.. 

Wenn ich die statementOfAccount.php aufrufe, bekomme ich folgenden Fehler:
`Got error 'PHP message: PHP Fatal error: Uncaught Fhp\\Protocol\\UnexpectedResponseException: Segment not found: Fhp\\Segment\\SPA\\HISPA in /var/www/vhosts/xx.de/xxxx.de/lib/Fhp/Protocol/Message.php:148\nStack trace:\n#0 /var/www/vhosts/xx.de/xxxx.de/lib/Fhp/Action/GetSEPAAccounts.php(69): Fhp\\Protocol\\Message->requireSegment('Fhp\\\\Segment\\\\SPA...')\n#1 /var/www/vhosts/xx.de/xxxx.de/lib/Fhp/FinTsNew.php(684): Fhp\\Action\\GetSEPAAccounts->processResponse(Object(Fhp\\Protocol\\Message))\n#2 /var/www/vhosts/xx.de/xxxx.de/lib/Fhp/FinTsNew.php(320): Fhp\\FinTsNew->processActionResponse(Object(Fhp\\Action\\GetSEPAAccounts), Object(Fhp\\Protocol\\Message))\n#3 /var/www/vhosts/xx.de/xxxx.de/fintestnew/statementOfAccount.php(16): Fhp\\FinTsNew->execute(Object(Fhp\\Action\\GetSEPAAccounts))\n#4 {main}\n thrown in /var/www/vhosts/xx.de/xxxx.de/lib/Fhp/Protocol/Message.php on line 148\n'`

Idee, was das sein kann?

**Comment by Philipp91** [comment]
Kannst du mit dem `CLILogger` oder so die Antwort der Bank mitschneiden und hier posten? Wenn du nicht sicher bist, ob noch private Daten drin sind, reicht es, wenn du nur die `HISPA`-Segmente postest, sofern sie existieren, und sie nach ein paar Zeichen abschneidest (bevor die privaten Daten anfangen). Also `HISPA:x:y:z+...`.

**Comment by D3vJust** [comment]
> Kannst du mit dem `CLILogger` oder so die Antwort der Bank mitschneiden und hier posten? Wenn du nicht sicher bist, ob noch private Daten drin sind, reicht es, wenn du nur die `HISPA`-Segmente postest, sofern sie existieren, und sie nach ein paar Zeichen abschneidest (bevor die privaten Daten anfangen). Also `HISPA:x:y:z+...`.

Ich habe tatsächlich nur ein "HISPAS"-Segment. ein "HISPA"-Segment existiert nicht in dem Callback..

**Comment by Philipp91** [comment]
Aber das `HISPAS` kommt ja vermutlich nicht als Antwort auf `HKSPA`, sondern irgendwann davor im Rahmen der BPD-Übermittlung, oder? Steht in der Antwortnachricht, die auf `HKSPA` folgt, irgendetwas Interessantes drin wie "wird nicht unterstützt" oder "Sie haben 0 Konten, deswegen schicken wir kein HISPA" oder so?

**Comment by D3vJust** [comment]
> Aber das `HISPAS` kommt ja vermutlich nicht als Antwort auf `HKSPA`, sondern irgendwann davor im Rahmen der BPD-Übermittlung, oder? Steht in der Antwortnachricht, die auf `HKSPA` folgt, irgendetwas Interessantes drin wie "wird nicht unterstützt" oder "Sie haben 0 Konten, deswegen schicken wir kein HISPA" oder so?

Habe das ganze mal etwas runtergebrochen:

`HNHBK:1:3+
HKIDN:2:2+
HKVVB:3:3+
HKTAN:4:6+4+
HKIDN
HNHBS:5:1+1
HNHBK:1:3+
HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+0010::Nachricht entgegengenommen.'
HIRMS:3:2:2+0020::Information fehlerfrei entgegengenommen.'
HIRMS:4:2:3+1040::BPD nicht mehr aktuell. Aktuelle Version folgt.+1050::UPD nicht mehr aktuell. Aktuelle Version folgt.'
HIBPA:5:3:3+13+280:+Postbank Berlin'
HIKOM:6:4:3+280:+1+3:https?://hbci.postbank.de/banking/hbci.do::MIM:1'
HIPINS:7:1:3+1+1+0+5:50:6:::HKTAN:N:DKPAE:J:HKDME:J:HKTAB:N:HKCSL:J:HKCDE:J:HKCDN:J:HKDMC:J:HKCDB:N:HKCCM:J:HKPSA:J:HKCCS:J:HKSAL:N:HKSPA:N:HKKAZ:N:DKPSA:J:HKPRO:N:HKBME:J:HKCME:J:HKCSB:N:HKPAE:J:HKCSE:J:HKKAU:N:HKCDL:J:HKCMB:N:HKEKA:N:HKDSC:J:HKCML:J'
DIPINS:8:1:3+1+1+HKTAN:N:DKPAE:J:HKDME:J:HKTAB:N:HKCSL:J:HKCDE:J:HKCDN:J:HKDMC:J:HKCDB:N:HKCCM:J:HKCCS:J:HKSAL:N:HKSPA:N:HKKAZ:N:DKPSA:J:HKPRO:N:HKBME:J:HKCME:J:HKCSB:N:HKCSE:J:HKKAU:N:HKCDL:J:HKCMB:N:HKEKA:N:HKDSC:J:HKCML:J'
HIPAES:9:1:3+1+1+
HIPSAS:11:1:3+1+1+0'
DIPSAS:12:1:3+1+1'
HITANS:13:6:3+1+1+0+N:N:0:910::
HHDOPT1:1.4:chipTAN optisch HHD1.4:6:1:Challenge:999:N'
HITABS:14:2:3+1+1+0'
HITABS:15:4:3+1+1+0'
HIPROS:16:3:3+1+1'
HISPAS:17:1:3+1+1+0+J:N:J:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02'
HIKAZS:18:5:3+1+1+90:N:N'
HIKAZS:19:6:3+1+1+0+90:N:N'
HISALS:20:5:3+1+1'
HISALS:21:6:3+1+1+0'
HIEKAS:22:3:3+1+1+0+J:N:N:3'
HIKAUS:23:1:3+1+1+0'
HICCSS:24:1:3+1+1+0'
HICSES:25:1:3+1+1+0+0:180'
HICSBS:26:1:3+1+1+1+N:J
HICSLS:27:1:3+1+1+1+J
HICDES:28:1:3+1+1+1+
HICDBS:29:1:3+1+1+1+N'
HICDNS:30:1:3+1+1+1'
HICDLS:31:1:3+1+1+1+1:1:N:J'
HICCMS:32:1:3+1+1+0+1000:J:J'
HICMES:33:1:3+1+1+0+1:180:1000:J:J'
HICMBS:34:1:3+1+1+1'
HIDMES:36:1:3+1+1+0+1:30:1:30:1000:J:J'
HIBMES:37:1:3+1+1+0+1:30:1:30:1000:J:J'
HIDSCS:38:1:3+1+1+1+1:30:1:30::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'
HIDMCS:39:1:3+1+1+1+1000:J:J:1:30:1:30::urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'
HIUPA:40:4:3+ '
HIUPD:41:6:3+  noref+nochallenge'HNHBS:43:1+1'
HNHBK:1:3+'
HKEND:2:1+'
HNHBS:3:1+2'
HNHBK:1:3+'
HIRMG:2:2+0010::Nachricht entgegengenommen.'
HIRMS:3:2:2+0100::Dialog beendet.'
HNHBS:4:1+2'
HNHBK:1:3+'
HNVSK:998:3+PIN:2'
HNVSD:999:1+@286@
HNSHK:2:4+PIN:2+920+7'
HKIDN:3:2+280:++0+1'
HKVVB:4:3+13+0+0++1.0'
HKTAN:5:6+4+HKIDN+++++++++SO?:GERÄTENAME'
HKSYN:6:3+0'HNSHA:7:2+739''
HNHBS:8:1+1'
HNHBK:1:3+0000000'
HNVSK:998:3+PIN:1+'
HNVSD:999:1+@620@
HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3076::Keine starke Authentifizierung erforderlich.+3060::Teilweise liegen Warnungen/Hinweise vor.'
HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'
HIRMS:4:2:4+3920::Meldung unterst�tzter Ein- und Zwei-Schritt-Verfahren:920:930+1050::UPD nicht mehr aktuell. Aktuelle Version folgt.'
HIRMS:5:2:6+0020::Auftrag ausgef�hrt.'
HIUPA:6:4:4++38+
HKSPA:1+DKTSP:1+
HKPSA:1'
HISYN:noref+nochallenge''
HNHBS:10:1+1'
HNHBK:1:3+000'
HNVSK:998:3+PIN:2+'
HNVSD:999:1+@219@
HNSHK:2:4+PIN:2+920+1'
HKEND:3:1+375'
HNHBS:5:1+2'
HNHBK:1:3+00000'
HNVSK:998:3+PIN:1'
HNVSD:999:1+@78@HIRMG:2:2+0010::Nachricht entgegengenommen.'
HIRMS:3:2:3+0100::Dialog beendet.''
HNHBS:4:1+2' 
HNHBK:1:3+00000'
HNVSK:998:3+PIN:2+998+1+'
HNVSD:999:1+@333@HNSH'
HKIDN:3:2+280:++'
HKVVB:4:3+13+38+0++1.0'
HKTAN:5:6+4+HKIDN+++++++++SO?:GERÄTENAME'
HNSHA:6:2+1508519++''
HNHBS:7:1+1'
HNHBK:1:3+00000000'
HNVSK:998:3+PIN:1+998+1+'
HNVSD:999:1+@321@
HIRMG:2:2+0020::Dialoginitialisierung erfolgreich.+3076::Keine starke Authentifizierung erforderlich.+3060::Teilweise liegen Warnungen/Hinweise vor.'
HIRMS:3:2:3+0020::Information fehlerfrei entgegengenommen.'
HIRMS:4:2:4+3920::Meldung unterst�tzter Ein- und Zwei-Schritt-Verfahren:920:930'
HITAN:5:6:5+4++noref+nochallenge''
HNHBS:6:1+1'
HNHBK:1:3+0000000'
HNVSK:998:3+PIN:2+998+1+1'
HNVSD:999:1+@188@
HNSHK:2:4+PIN:2+920+10'
HKSPA:3:1'HNSHA:4:2+1064460++''
HNHBS:5:1+2'
HNHBK:1:3+00000000'
HNVSK:998:3+PIN:1+998+1+2::0'
HNVSD:999:1+@105@HIRMG:2:2+3060::Teilweise liegen Warnungen/Hinweise vor.'
HIRMS:3:2:3+3010::Es liegen keine Eintr�ge vor.''
HNHBS:4:1+2'`

**Comment by ampaze** [comment]
Postbank verursacht hier mehr Probleme als alle anderen Banken zusammen... 👎

**Comment by Philipp91** [comment]
> Habe das ganze mal etwas runtergebrochen

Es gibt übrigens `prettify_message.php` hier im Repo, was auch noch die Feldnamen dazu schreibt und es dadurch wesentlich lesbarer macht.

**Comment by D3vJust** [comment]
> (Postbank verursacht hier mehr Probleme als alle anderen Banken zusammen... 👎 )

Freut einen natürlich zu hören :/

**Comment by Philipp91** [comment]
Also aus dem Pastebin entnehme ich:

Der Client fragt mit `HKSPA:3:1'` (also Segmentnummer 3) alle Konten an. Der Server antwortet mit ` HIRMS:3:2:3+3010::Es liegen keine Einträge vor.'` Hier steht die zweite 3 für die Anfrage-Segmentnummer, auf die sich die Antwort bezieht. Sprich: Es gibt keine Konten. Deswegen ist auch kein `HISPA`-Segment in der Antwort enthalten. Ein versuchter Fix dafür ist in #234. Aber auch der Fix ändert nichts daran, dass die Postbank dir keine Konten zurückschickt, d.h. du kriegst dann halt ein leeres Array. Warum weiß ich auch nicht.

**Comment by D3vJust** [comment]
Ich weiß wieso die Postbank mir keine Konten zurückgegeben hat.

Wenn ich den Anmeldenamen auf 'PostbankID#ProfilName'.. ich habe nur die PostbankID genutzt gehabt..
Jetzt bekomme ich auch mit den aktuellen Libs die Umsätze zurück.

Thema Lastschrift gehe ich jetzt an..
