### ISSUE TITLE
Startschwierigkeiten: selectTanMode() must be called before login() or execute()

### ISSUE THREAD

**Issue by philippd1** [nemiah/phpFinTS#238]
Hi zusammen,
erstmal vielen Dank für dieses riesen Projekt.

Ich habe leider ein paar Startschwierigkeiten...
Nutze den Code aus `SamplesNew/statementOfAccount.php` + `SamplesNew/login.php`, nur meine Parameter angepasst und mal aufgerufen...

Die `composer.json` schaut so aus:
```
{
	"require": {
		"nemiah/php-fints": "dev-master@dev"
	}
}
```
gesamte Ordnerstruktur:

![image](https://user-images.githubusercontent.com/17651032/74661733-d219b380-5198-11ea-9564-0bfc613d63f6.png)

ich bekomme dann direkt die folgende Meldung:
```
Fatal error: Uncaught RuntimeException: selectTanMode() must be called before login() or execute() in \vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php:626 Stack trace: #0 \vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php(245): Fhp\FinTsNew->requireTanMode() #1 \login.php(95): Fhp\FinTsNew->login() #2 \index.php(11): require_once('...') #3 {main} thrown in \vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php on line 626
```

über kurze Hilfe wäre ich dankbar 🙂🙂

**Comment by fbett** [comment]
Dieser Teil befindet sich gerade von unter Review (#229).
Gesichert ist, dass folgendes Vorgehen funktionieren sollte.

Vor `$login = $fints->login();`:
- zuerst die verfügbaren Tan Modes holen, per: `$tanModes = $fints->getTanModes()`
- Den User den gewünschten Tan Mode auswählen lassen
- dann über `$fints->selectTanMode($tanMode)`, den ausgewählten Tan Mode setzen.

Viel Spaß

@ampaze Ich würde vorschlagen das Sample hierzu anzupassen. Was meinst du?

**Comment by philippd1** [comment]
super, vielen Dank 👍 teste ich gleich mal
und: die Beispiele anpassen wäre gut :) auch wenn sich da aktuell noch einiges in development befindet

**Comment by ampaze** [comment]
> @ampaze Ich würde vorschlagen das Sample hierzu anzupassen. Was meinst du?

Ja, aber man sollte evtl. drauf Hinweisen, dass getTanModes optional ist, wenn man die TAN Mode Nummer einmal weiß, reicht selectTanMode. 

@Philipp91 Was meinst du?

**Comment by fbett** [comment]
`getTanModes` ist zumindest bei der Deutschen Bank nicht optional, trotz Angabe des Tan Modes.
Siehe https://github.com/nemiah/phpFinTS/issues/229#issuecomment-584406277

Ich meine in den Issues gelesen zu haben, dass dies auch auf mindestens eine andere Bank zutraf.

**Comment by ampaze** [comment]
Es ist rein vom logischen Prozess her optional, in Ticket #229 ist es als Workaround für das eigentliche Problem beschrieben, nämlich dass der TAN-Mode schon zu früh im Prozess des Verbindungsaufbaus verwendet wird.

**Comment by philippd1** [comment]
nachdem ich gestern mit einer anderen Library mein Konto erfolgreich gesperrt habe (🙄) heute noch ein Versuch...
Mit welchen Konten testet ihr denn das Projekt?
Der Demo-Account meiner Sparkasse scheint keine FinTS Unterstützung zu haben... `Ihr Zugang ist vorläufig gesperrt - Bitte PIN-Sperre aufheben.`
Die Daten dafür sind
```
finTS: darf man ja leider nicht sharen, aber die habt ihr ja eh 🙃
BLZ: "76350000"
username: "pushDEMO"/"chipDEMO"
PIN: "12345"
TAN: beliebige 6-stellige Zahl
```

Test-Account der apoBank
```
BLZ: 30060601
Kontonummer: 0001956434
PIN: 11111
TAN: 123456
```
damit gibt's folgendes Ergebnis: `9078 (global): Software nicht als FinTS-Produkt registriert. Bitte an Hersteller wenden.`. Ich habe aber überall meine ID angegeben...

Hat jemand 'ne Idee? 🙂

**Comment by fbett** [comment]
Ist es eine relativ neue ID? Es schien, als würde es in letzter Zeit einige Zeit (mehrere Wochen) dauern, bis die ID allen Banken bekannt ist.

**Comment by philippd1** [comment]
Die ID habe ich gestern bekommen.
Die apoBank werde ich also wahrscheinlich erst nach einiger Zeit testen können?
Was nehmt ihr denn zum development testen?

**Comment by ampaze** [comment]
Im allgemeinen nutzt hier jeder seine echten Bankzugänge, da sehr wenige Banken Testsysteme haben oder diese öffentlich machen.

Ich habe die apoBank mit meiner Produkt-ID getestet und ich bekomme die Bankparamter-Daten zurück. Ich meine mich auch zu erinnern, dass es hier Tickets gab wo der Zeitraum bis zur Übernahme neuer ID's durch die Banken mit mehreren Wochen angegeben wurde. 😞 

----

Die apoBank funktioniert aktuell aber nicht mit FinTsNew, da die Bank den Dialog von sich aus beendet und dann FintsNew den Dialog auch nochmal beenden will. Das muss sich erstmal jemand angucken.

**Comment by philippd1** [comment]
Also wegen mir kann der issue hier zu.
Leider kann ich aus organisatorischen Gründen nicht mit meinem Privatkonto testen 😐
Somit erstmal Ende an dieser Stelle. Danke trotzdem für eure Mühe!

Für Kunden der Sparkassen: habe alles durchgefragt, hier gibt's keine Testzugänge :/
