### ISSUE TITLE
Starke Kundenauthentifizierung bei Volksbank(en)

### ISSUE THREAD

**Issue by JarvisHome** [nemiah/phpFinTS#24]
Hallo Nena,

jetzt scheint es auch bei den Volksbanken zur Umstellung zu kommen. Seit heute Mittag bekommen wir die Meldung:

`Die Nachricht enthält Fehler. (9050); Starke Kundenauthentifizierung notwendig. (9075); Dialog abgebrochen (9800); Auftrag abgelehnt. (9340)`

Ich versuche mich jetzt mal schlau zu machen - oder gibt es bereits einen Lösungsansatz?

Viele Grüße
Christian

**Comment by JarvisHome** [comment]
Nachtrag: lt. Volksbank muss der Geschäftsvorfall HKTAN in Version 5 oder 6 integriert sein um die TAN Abfrage zur Starken Kundenauthentifizierung abhandeln zu können.

**Comment by nemiah** [comment]
Hallo Christian,

wenn eine meiner Banken umstellt, kann ich es mir ansehen.
Davor müsste es jemand anderes machen :)

Ja, grundsätzlich ist die TAN-Bearbeitung drin, aber sie wird beim Umsätze abholen nicht erwartet.

Liebe Grüße
Nena

**Comment by nemiah** [comment]
Duplicate of #20
