### ISSUE TITLE
GetStatementOfAccount älter als 90 Tage - Deutsche Bank

### ISSUE THREAD

**Issue by MisterErwin** [nemiah/phpFinTS#249]
Hallo zusammen,

bei dem Versuch Transaktionen bei der deutschen Bank abzufragen, die älter als 90 Tage sind. (Also 2. Januar oder früher) bekomme ich den wunderbaren Fehler:

> 9050 (global): Teilweise fehlerhaft.
> 9210 (wrt seg 3): Wert widerspricht Bankvorgaben.
> 9210 (wrt seg 4): Auftrag abgelehnt - Zwei-Schritt-TAN inkonsistent. Eingereichter Auftrag gelösch

Sieht für mich nach dem gleichen Problem wie in #239 aus.

Mit Hibiscus z.B. funktioniert das Ganze:
> HNHBK:1:3+000000000453+300+v4k#ara*wH1*20200402192509114%+3'HNVSK:998:3+PIN:2+998+1+1::3763301091248000E2226DNMNXDRIS+1:20200402:192513+2:2:13:@8@        :5:1+280:39070024:<username>:V:0:0+0'HNVSD:999:1+@230@HNSHK:2:4+PIN:2+901+1604026833+1+1+1::3763301091248000E2226DNMNXDRIS+1+1:20200402:192513+1:999:1+6:10:16+280:39070024:<username>:S:0:0'HKKAZ:3:7+<IBAN>:DEUTDEDB390+N'HKTAN:4:6+4+HKKAZ'HNSHA:5:2+1604026833++<pin>''HNHBS:6:1+3'

Im Vergleich dazu mit phpFinTS (new)
> HNHBK:1:3+000000000474+300+qoxQWtdqrCtJ20200402193359124%+3'HNVSK:998:3+PIN:2+998+1+1::3763301638914000F6L7N78YQUZ0GI+1:20200402:173403+2:2:13:@8@00000000:5:1+280:39070024:<username>:V:0:0+0'HNVSD:999:1+@251@HNSHK:2:4+PIN:2+902+6895384+1+1+1::3763301638914000F6L7N78YQUZ0GI+1+1:20200402:173403+1:999:1+6:10:19+280:39070024:<username>:S:0:0'HKKAZ:3:7+<IBAN>:DEUTDEDB390:013378500:EUR:280:39070024+N+20200102+20200402'HNSHA:4:2+6895384++<pin>''HNHBS:5:1+3'

Die minimale Änderung die ich eingefügt habe ist ein `$fints->selectTanMode(902);` (photoTAN) - hier 901 zu verwenden macht aber keinen Unterschied was den Fehler angeht.

Der konkrete Unterschied scheint zu sein, dass Hibiscus in den `HKKAZ` Befehl ein `HKTAN` eingliedert (soweit für mich sichtbar).

Hibiscus:
> HKKAZ:3:7+<IBAN>:DEUTDEDB390+N'
HKTAN:4:6+4+
HKKAZ'
HNSHA:5:2+1604026833++<pin>''

phpFiNTS:
> HKKAZ:3:7+<IBAN>:DEUTDEDB390:013378500:EUR:280:39070024+N+20200102+20200402'
HNSHA:4:2+6895384++<pin>''

(etwas rumprobieren meinerseits hat noch zu keinem Ergebnis geführt)

Sonst vielen Dank für die Library

**Comment by MisterErwin** [comment]
Hey,

das tanRequired Array hat interessanterweise `HKKAZ` als true/1 gesetzt.
> Array
(
    [HKAUB] => 1
    [HKUMB] => 1
    [HKCSE] => 1
    [HKDML] => 1
    [HKCCS] => 1
    [HKDSC] => 1
    [HKCSL] => 1
    [HKTAN] =>
    [HKDMB] =>
    [HKBML] => 1
    [HKPRO] =>
    [HKFRD] =>
    [HKCSB] =>
    [HKDME] => 1
    [HKDSE] => 1
    [HKBME] => 1
    [HKCSA] => 1
    [HKBBS] =>
    [HKCDE] => 1
    [HKBSE] => 1
    [HKSAL] =>
    [HKCDN] => 1
    [HKDSA] => 1
    [HKBMB] =>
    [HKKAZ] => 1
    [HKDSL] => 1
    [HKBSA] => 1
    [HKCCM] => 1
    [HKCMB] =>
    [HKDBS] =>
    [DKPSP] => 1
    [HKCDB] =>
    [HKCML] => 1
    [HKPSP] => 1
    [HKCDL] => 1
    [HKCME] => 1
    [HKDMC] => 1
    [HKWPD] =>
    [HKBSL] => 1
    [HKSPA] =>
)

(was mich jetzt selber verwirrt, da ich mir recht sicher bin, dass es zwischendurch nicht dadrinnen gestanden hat - jetzt sehe ich aber auch das PIN Angebot für HKKAZ)

Aber dein Hinweis mit fehlendem Datumsbereich hat mich einfach einmal dazu veranlasst to and from wegzulassen/auf null zu setzen (Zumal Hibiskus eine Datums-Auswahl anbietet die keinen neuen FinTS call veranlasst).
Dann akzeptiert die DB den Request und liefert artig eine Antwort.

Ich vermute einfach mal, dass das irgendwas zwischen Fehler und Absicht bei der DB ist und ich das issue closen kann?

Aber danke für die Hilfe!

**Comment by Philipp91** [comment]
Also funktioniert es ohne Datum, und mit dann nicht mehr? Funktioniert es mit `2020-03-15` bis `2020-03-31`? Vielleicht bedeutet "9210 (wrt seg 3): Wert widerspricht Bankvorgaben" ja sowas wie "Ungültiger Datumsbereich", z.B. weil die Daten zu weit in der Vergangenheit liegen oder weil man "heute" nicht abfragen kann sondern maximal "gestern".

**Comment by MisterErwin** [comment]
Ohne Datum `\Fhp\Action\GetStatementOfAccount::create($oneAccount);` funktioniert es.

Sobald zwei Daten (bei der DB) angegeben sind, die mehr als 90 Tage auseinander liegen (z.B. `$getStatement = \Fhp\Action\GetStatementOfAccount::create($oneAccount, new \DateTime('2019-12-01'), new \DateTime('2020-03-01'));`) tritt der Fehler auf.

Zwei Daten die nah genug beieinander liegen funktionieren (z.B. `2020-03-15` bis `2020-03-31`).

**Comment by ampaze** [comment]
> Vielleicht bedeutet "9210 (wrt seg 3): Wert widerspricht Bankvorgaben" ja sowas wie "Ungültiger Datumsbereich"

Das war auch meine Vermutung, als das Thema schon mal auftauchte:
Siehe https://github.com/nemiah/phpFinTS/issues/239#issuecomment-592038155

**Comment by MisterErwin** [comment]
Noch einmal Danke für die Hilfe.

Ich close das issue einfach mal
