### ISSUE TITLE
Die Postbank funktioniert aktuell nicht

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#25]
Bereits aus mehreren Quellen wurde berichtet, dass aktuell bei der Postbank keine Umsätze abgeholt werden können.

Es scheint daran zu liegen, dass die Postbank die HBCI-Zugänge vorerst abgeschaltet hat.
Da wir darauf keinen Einfluss haben, bitte ich darum, diesbezüglich keine weiteren issues zu erstellen.

Liebe Grüße
Nena

**Comment by roben** [comment]
Beim Refactoring von GetVariables ist mir aufgefallen, dass die Postbank ihre HITANS schon bei der Initialisierung mitschickt und dann den Dialog beendet. Mit `GetVariables` kommt man da also schon gar nicht mehr weiter bzw. müsste das auf die Initialisierungsnachricht anwenden.

**Comment by roben** [comment]
Außerdem schickt die Postbank auch gleich verschiedene TAN-Verfahren in mehreren Versionen mit. Eigentlich muss man sich dann zum Verfahren auch die Version merken, damit man auch entsprechend korrekt antwortet. Dafür ist natürlich noch mal ein ordentliches Refactoring erforderlich, aber hier sollte der neue Code von @Philipp91 schon helfen.

**Comment by roben** [comment]
Ich  habe testweise mal nur die höchste Version eingelesen und es waren genau die gleichen Mechanismen. Ich denke, da können wir die Version also vorerst ignorieren, bis wir weniger andere Probleme haben.

**Comment by roben** [comment]
Ich habe gerade Postbank-Umsätze abgefragt :tada:
Das Hauptproblem war letztendlich, dass die `HKTAN` zu wenig Parameter hatte und insbesondere bei mobileTAN keine "Bezeichnung des TAN-Mediums" übergeben hat. Das kann die Bank als Pflichtfeld markieren: "bei TAN-Prozess=1, 3, 4 und „Anzahl unterstützter aktiver TAN-Medien“ > 1  und „Bezeichnung des TAN-Mediums erforderlich“=2. Ansonsten ist es optional, kann also immer angegeben werden.
Dafür braucht `$fints->setTANMechanism` allerdings jetzt einen zweiten aber optionalen Parameter, z.B. `$this->_fints->setTANMechanism(930, 'Bestes Handy');`. Der Name des Mediums ist vermutlich bei der Bank irgendwo hinterlegt.

**Comment by roben** [comment]
Ach und die Postbank kommt gar nicht auf `HKEND` klar, die beenden den Dialog von sich aus schon. Wenn man jetzt wüsste, ob alle anderen Banken auch ohne `HKEND` klar kommen...

**Comment by roben** [comment]
Ich räume erstmal auf und mache einen PR fertig.

**Comment by nemiah** [comment]
@roben Wie sieht es mit der Postbank aus, Kann ich diesen Beitrag schließen?

**Comment by roben** [comment]
Die Bank selber war am WE mal kurz down (`Verarbeitung zur Zeit nicht möglich, bitte später erneut versuchen (9010); Dialogabbruch. (9800)`), aber sonst scheint das gut zu laufen. Kann gerne zu :+1:
