### ISSUE TITLE
Make messages and segments more debuggable

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#26]
I use an IDE with an interactive debugger in order to figure out how the bank communicates. In the variables view of the debugger, the presentation of messages and segments are pretty much useless because their internal storage format is just a couple of arrays (it mirrors the FinTS wire format).

The segment creation logic becomes more cumbersome due to this, e.g. [here](https://github.com/nemiah/phpFinTS/blob/95b1c0a3405131c6bdcd06eee41855aaf4e755ea/lib/Fhp/Segment/HKTAN.php#L29-L59).

The parsing logic and assignment to human-readable identifiers is only done in the getters (e.g. [getEncodedData()](https://github.com/nemiah/phpFinTS/blob/95b1c0a3405131c6bdcd06eee41855aaf4e755ea/lib/Fhp/Segment/HNVSD.php#L39) knows that the encoded data is stored in the `0`-th data element. That same information is hard-coded redundantly in the constructor and in `setEncodedData()`. More parsing logic is scattered at several call sites, e.g. [getSupportedTanMechanisms](https://github.com/nemiah/phpFinTS/blob/95b1c0a3405131c6bdcd06eee41855aaf4e755ea/lib/Fhp/Response/Response.php#L144) knows that it needs to look in the element with ID `3920` inside the segment `HIRMS` but there is not even a HIRMS class.

I propose to (1) have one class per segment _version_, e.g. `HKTANv6` and (2) use plain fields inside, e.g. `/** @type string */ public $processID;`. This will require some mapping to the wire format, as each field needs to declare its position (and ideally also whether it's required or not). A potential solution could be annotations, e.g.  `/** @type string @DE(5) */`.

Please let me know what you think.

**Comment by nemiah** [comment]
@Philipp91 This sounds good, the code often does seem overly complicated to me, too. Please send me small PRs, so that I can include them one by one.
