### ISSUE TITLE
Test Setup - Integration Tests

### ISSUE THREAD

**Issue by Cugar15** [nemiah/phpFinTS#266]
Hallo Zusammen,

   erst mal Danke fuer die Software - sollte genau das tun was ich mir wünsche :)

Habe mir bereits eine FinTS-Produkt-Registrierungsnummer zuteilen lass - soweit so gut.
Nur jetzt heisst es wohl warten..

In der Zwischenzeit wuerde ich gerne meine Software entwickeln wollen. Dazu koennte man doch die Integration tests hernehmen.

Leider habe ich bis jetzt noch nicht rausbekommen wie man diese nutzen kann.

Gibt es hierzu eine sehr einfaches: HowTo?

Danke im Voraus und wuerde mich auf eine Antwort freuen.

**Comment by Philipp91** [comment]
Dafür sind die Integration-Tests ja eigentlich auch nicht gedacht. Vielleicht hätte ich sie besser "Regression-Tests" nennen sollen. Da ist im Grunde nur die Bankkommunikation aufgezeichnet, wie sie passiert, wenn die Bibliothek sich auf eine bestimmte Art verhält. Wenn die Tests nicht fehlschlagen, weiß man, dass man das nach außen sichtbare Verhalten der Bibliothek nicht geändert hat (also ein reines Refactoring, oder nur die Schnittstelle zur Anwendung hin verändert). Wenn die Tests fehlschlagen, weil die Bibliothek einen anderen Request schickt als aufgezeichnet, weiß man gar nichts, dann muss man eine frische Sitzung mit der echten Bank durchführen und aufzeichnen. Im Grunde sind die Tests also nur ein Cache, damit man die Bank nicht so oft behelligen muss.

Im Grunde kannst du einen der Tests kopieren, die `$this-fints->...` Aufrufe rausnehmen und stattdessen deine eigene Anwendung instanziieren (`this->fints` dort reingeben) und dann Aufrufe machen, die innen drin in denselben `$this-fints->...` Aufrufen resultieren sollten. Das Problem ist, dass viele andere Aufruf-Reihenfolgen und -Parameter genauso richtig sein können, nur dass wir die eben nicht aufgezeichnet haben. Eigentlich bräuchtest du also deinen eigenen Cache-Eintrag, aber dafür müsstest du ja ein Mal mit einer echten Bank testen. Aber mit ein bisschen Basteln könnte es klappen, die bestehenden wiederzuverwenden.

**Comment by Cugar15** [comment]
OK, vielen Dank fuer die Antwort. Werd mal schauen was sich machen laesst.

Ich habe noch 2 weitere Probleme - ich mach auch gerne separte issues dafuer auf.

1) Probiere ich bei einer Sparkasse, bekomme ich nach vielem Text die Meldung:
    "Dialog abgebrochen - Banking-Programm ist nicht registriert"
    Hätte ich jetzt auch so erwartet.
 
    Probiere ich es bei der ING, dann bekomme ich:
    `
debug: > HNHBK:1:3+000000000145+300+0+1'HKIDN:2:2+280:50010517+9999999999+0+0'HKVVB:3:3+0+0+0+<PRIVATE________________>+1.0'HKTAN:4:6+4+HKIDN'HNHBS:5:1+1'
debug: < HNHBK:1:3+000000000201+300+000006JQ82GRI0P6CRIOEOH3R3MCP6+1+000006JQ82GRI0P6CRIOEOH3R3MCP6:1'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9400::Der anonyme Dialog wird nicht unterstützt.'HNHBS:3:1+1'
`

    So, wie in issue: #57 
    Bin mir aber sicher, dass ich auf der 'master' release bin.

    Sollte das so sein?

2) Ich führe php -f prettify_message.php < t1.log
   t1. log enthält den printout von oben.
   Dann gibt es die folgende php error message:
`
[14-Apr-2020 21:56:49 Europe/Berlin] PHP Fatal error:  Uncaught InvalidArgumentException: Failed to parse Fhp\Segment\Segmentkopf::segmentnummer: InvalidArgumentException: Invalid int:  > HNHBK in C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php:136
Stack trace:
#0 C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(268): Fhp\Syntax\Parser::parseDataElement(' > HNHBK', 'int')
#1 C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(204): Fhp\Syntax\Parser::parseDegElements(Array, 'Fhp\\Segment\\Seg...', false)
#2 C:\vendor\nemiah\php-fints\lib\Fhp\Segment\BaseDeg.php(75): Fhp\Syntax\Parser::parseDeg(Array, 'Fhp\\Segment\\Seg...')
#3 C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(424): Fhp\Segment\BaseDeg::parse('debug: > HNHBK:...')
#4 [internal function]: Fhp\Syntax\Parser::detectAndParseSegment('debug: > HNHBK:...')
#5 C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(455): array_map(Array in C:\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php on line 288
`

Danke fuer eine Antwort.

**Comment by Philipp91** [comment]
> Der anonyme Dialog wird nicht unterstützt

Für die ING-DiBa muss man `NoPsd2TanMode` verwenden.

> `Invalid int: > HNHBK`
> `Fhp\Syntax\Parser::detectAndParseSegment('debug: > HNHBK:...')`

Das `debug: >` gehört nicht zur Nachricht, es wird nur vom Logger ausgegeben. Die Nachricht fängt erst bei `HNHBK` an.

**Comment by Cugar15** [comment]
Dank  fuer die schnellen Antworten.
Und es hat beides funktioniert.
