### ISSUE TITLE
Frage zu GetSEPAAccounts

### ISSUE THREAD

**Issue by interose** [nemiah/phpFinTS#267]
Hallo zusammen, kommen bei euch eigentlich beim Abrufen der Kontenliste alle Konten mit? Also z.B. bei der DKB inkl. Visa & Broker Konto?
Ich meine dass zumindest das Visa Konto noch zusätzlich in dem accounts array war, bin mir aber jetzt nicht sicher.

**Comment by Philipp91** [comment]
Also bei der DKB kriege ich nur mein Girokonto (genannt "Sichteinlagen"), auch in Hibiscus. Ich entsinne ich mich auch dunkel, dass früher das VISA-Konto auch aufgelistet war, aber dann der Umsatzabruf dann dafür trotzdem nicht möglich, also hat es letztlich nichts gebracht. Möglicherweise haben sie das VISA-Konto jetzt entfernt, um Verwirrung zu vermeiden?
Ein Broker-Konto habe ich nicht bei der DKB.

Bei der Consorsbank sehe ich auch mein Verrechnungskonto, Tagesgeldkonto und Depot.

**Comment by interose** [comment]
Ich hab jetzt mal bei der DKB nachgefragt und folgende Antwort bekommen:

Sie können mit einer beliebigen Finanzsoftware Ihr DKB-Broker abfragen
jedoch nicht bedienen.
Die Umsatzanzeige und die Kreditkartenabrechnungen Ihrer DKB-VISA-Card 
können mit allen Software-Produkten abgerufen werden, die das Screen-
Scraping-Verfahren unterstützen. 

Broker hätte mich jetzt interessiert, aber da man den eh nicht bedienen kann hat es sich eigentlich auch schon wieder erledigt.

**Comment by Philipp91** [comment]
Und noch für's Protokoll: Screen-Scraping ist natürlich das "Gegenteil" von HBCI/FinTS.

**Comment by interose** [comment]
😄 jaaaa ich dachte mir auch was jetzt die Antwort mit meiner Frage bzgl. HBCI Schnittstelle zu tun hat, aber ich wollte da jetzt nicht noch ewig nachbohren.
