### ISSUE TITLE
Depotaufstellung (HKWPD) and Depotumsätze (HKWDU)

### ISSUE THREAD

**Issue by Andreas-Sommer** [nemiah/phpFinTS#268]
Are there any plans for an implementation of Geschäftsvorfall HKWPD and HKWDU?

**Comment by Philipp91** [comment]
I'm not aware of any such plans. I guess the main work lies in parsing the MT535 format? Or is there already a parser in PHP?

**Comment by ZwenAusZwota** [comment]
I try to implement HKWPD now, but unfortunately I stuck at the determination of the class.
I've implemented HIPWD, HIWPDS, HKWPD, but they are not loaded if I check with fetchBDP: HIWPDS] => Array ( [5] => Fhp\Segment\AnonymousSegment.
NameMapping.php was extended. Are the files (located in /Segment/WDP/) found automatically?

**Comment by Philipp91** [comment]
> NameMapping.php was extended

What's that file? I can't find it on `master` and I don't know it.

> Are the files (located in /Segment/WDP/) found automatically?

Yes, [this code](https://github.com/nemiah/phpFinTS/blob/d462d1b4d01a28277573c98ddfcb2bbdcb0e00fd/lib/Fhp/Syntax/Parser.php#L462-L475) should take care of finding the right segment class, and then your PHP class loader should take care of loading the PHP file as usual.

**Comment by ZwenAusZwota** [comment]
> What's that file? I can't find it on master and I don't know it.

https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/Segment/NameMapping.php

Thanks for the code. I'll try it

**Comment by Philipp91** [comment]
> https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/Segment/NameMapping.php

Huh. I think we can remove that, it has no call sites. @nemiah @ampaze Any concerns with that?

**Comment by nemiah** [comment]
nope

**Comment by ampaze** [comment]
Can be deleted. That file is from before the rewrite.
