### ISSUE TITLE
Sparkasse

### ISSUE THREAD

**Issue by tfisinger** [nemiah/phpFinTS#277]
Hallo Miteinander,

gibt es auch Beispiele für die Sparkasse?

VG

**Comment by Philipp91** [comment]
Nein, dafür gibt es keine gesonderten Beispiele. Der Beispielcode für Umsatzabruf und Überweisungen sollte so funktionieren, wie er ist. Sparkassen-spezifische Geschäftsvorfälle werden derzeit nicht unterstützt, aber die brauchen vermutlich auch die wenigsten.
