### ISSUE TITLE
Rückmeldung, ob meine XML-Daten korrekt sind

### ISSUE THREAD

**Issue by 2nd-Moon** [nemiah/phpFinTS#278]
Hi,
die Übermittlung von Lastschriften funktioniert schon ganz gut.

Wenn ich eine XML-Datei für DirectDebit übermittel, bekomme ich ein "Nachricht wurde übermittelt" oder sowas in der Art.
Wie komme ich jetzt an eine Fehlermeldung der Bank ran? Also z.B. IBAN ist inkorrekt oder Datum der Lastschrift ist zu kurzfristig. Hat hier jemand einen Tipp?

**Comment by ampaze** [comment]
Die Bank wird nicht mit Nachricht wurde übermittelt antworten wenn es einen Fehler gab. 

Wenn es einen Fehler gibt, solltest du eine entsprechende ServerException bekommen. 
Probier es am besten mal aus.

**Comment by 2nd-Moon** [comment]
Hi,
ich habe mal absichtlich die IBAN eine Stelle zu kurz übermittelt. Es wird trotzdem "Nachricht entgegengenommen.Auftrag ausgeführt." gemeldet. Ich habe nur eine einzige Lastschrift übermittelt.
Das ist die Postbank. Es muss also noch eine andere Möglichkeit über die Schnittstelle geben, Fehler und den Status Verarbeitung abzurufen. Nur wie?

**Comment by ampaze** [comment]
Dann prüft die Postbank deinen Auftrag wohl nicht direkt beim Einreichen.

Evtl. ist **C.10.4.3 SEPA-Statusreport** was du suchst.

> Der Kunde ruft zu einer Auftragsidentifikation oder einem Zeitraum SEPAStatusreports ab. 

Details dazu hier

https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf

Diesen Geschäftsvorfall musst du dann selbst implementieren.

**Comment by 2nd-Moon** [comment]
In dem PDF habe ich auch schon gesucht. Aber super, das ich genau der Vorgang den ich brauche. Muss ich dann mal schauen. danke.

**Comment by 2nd-Moon** [comment]
Mich wundert, dass das andere User gar nicht brauchen. Manche Banken lehnen den gesamten Auftrag wohl schon gleich ab.

**Comment by ampaze** [comment]
> Mich wundert, dass das andere User gar nicht brauchen. Manche Banken lehnen den gesamten Auftrag wohl schon gleich ab.

Ja, der Großteil der Banken würde ich mal vermuten/hoffen.

----

Vlt wird auch unterschieden zwischen Einzellastschrift und Sammellastschrift.

Du könntest mal

```php
// If the PAIN message contains a control sum, we should use it, if the bank also supports it
if ($useSingleDirectDebit && !is_null($this->ctrlSum) && !is_null($bpd->getLatestSupportedParameters('HIDMES'))) {
    $useSingleDirectDebit = false;
}
```

auskommentieren und es nochmal mit einer syntaktisch falschen IBAN probieren.

**Comment by 2nd-Moon** [comment]
Danke für den Tipp. Soweit bin ich in dem Code nicht Zuhause, dass ich dort in der Schnittstelle Änderungen machen kann. Es gab aber leider keine Veränderung der Rückmeldung. Er sagt immer noch "Auftrag ausgeführt."
