### ISSUE TITLE
2019-09-14: Game over for phpFinTS?

### ISSUE THREAD

**Issue by bodyhey** [nemiah/phpFinTS#28]
Dear all,

as Phillipp91 wrote: "Ab dem 14.09.2019 stellen die Mehrzahl der Kreditinstitute neben der FinTS-Schnittstelle eine weitere Schnittstelle nach den Regularien der PSD2-Richtlinien bereit. Zahlungsauslösedienste und Kontoinformationsdienste bedürfen dann einer Zulassung der deutschen (BaFin) oder einer anderen europäischen Regulierungsbehörde. Detaillierte Hinweise sowie Informationen zu Testzugängen finden sie auf den Web-Seiten der Institute, bzw. deren IT-Dienstleister oder unter nisp.online. Die bisherige FinTS-Schnittstelle darf durch diese Dienste bei Zugriffen auf Zahlungskonten dann nicht mehr genutzt werden."

Do we have any chance to get our implementations running again? With the lastest version from nemiah calling "Fhp\FinTs->getSEPAAccounts( )" I get today: "Fatal error: Uncaught exception 'Fhp\Dialog\Exception\FailedRequestException' with message 'Request Failed: Pflichtfeld nicht gefunden (9160); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)' [...]"

Hoping for the best,

Martin

**Comment by dennobaby** [comment]
Hi Martin,

you have to register your app at FinTS and get a Registration-Number.

See more here: https://www.hbci-zka.de

**Comment by nemiah** [comment]
phpFinTS is still going strong! :smile:
