### ISSUE TITLE
Should `execute()` call `$action->maybeThrowError()`?

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#282]
Currently, functions like `login()`, `execute()` and `submitTan()` throw out some exceptions directly (mostly the ones related to network, parsing and protocol errors), whereas the exceptions that pertain to the `BaseAction` itself are stored in there, so that they later need to be re-thrown by the application code calling `$action->maybeThrowError()`.

This design emerges directly from the HBCI specification's design, which conceptually allows multiple actions to be executed in a single request to the bank and thus each end up with different success/error outcomes. In practice though, the phpFinTS library only supports only a single action per request, for certain actions the specification doesn't allow multiple generally, and it's unclear whether bank servers have good support for multiple actions and whether it would be useful for any applications in the future.

We could change the three functions above that deal with actions to call `maybeThrowError()` at the end, before returning to the caller. Note that this is slightly different from `ensureSuccess()` (which is currently used in all example code) in that it does not throw when a TAN is needed, since `if ($action->needsTan())` is a much nicer way to check for that than another `catch` block.

This makes it impossible for application developers to check for these exceptions (like our example code currently does, there's an `ensureSuccess()` call missing [here](https://github.com/nemiah/phpFinTS/blob/278152dcab7258dc388a0db6f7c0d4c83ee6b3f3/Samples/login.php#L100)), but it also makes it much more difficult to differentiate action-level errors from network/protocol-level errors. (To help with the latter, we could wrap the exception into a new `ActionFailedException`, though I'm not sure how useful that would be.)

@nemiah @ampaze @fbett Any reasons not to call `maybeThrowError()` always? Any thoughts on wrapping the exception or not? Do you have use cases in your application code that require differentiating exception types and sources like that, or do you just mix everything in a single `catch` block anyway?

Side note: I'm not sure if the wrapping [here](https://github.com/nemiah/phpFinTS/blob/278152dcab7258dc388a0db6f7c0d4c83ee6b3f3/lib/Fhp/FinTs.php#L793) is good. My application code checks for `ServerException::indicatesBadLoginData()` and such, but it would miss that when the `ServerException` is wrapped inside an `UnexpctedResponseException` like there. Maybe we should treat it like [here](https://github.com/nemiah/phpFinTS/blob/278152dcab7258dc388a0db6f7c0d4c83ee6b3f3/lib/Fhp/FinTs.php#L499-L503) instead.

**Comment by nemiah** [comment]
Sounds like an interesting idea to me and error handling is an important issue. But, to be honest, I didn't miss it yet :woman_shrugging:

**Comment by ampaze** [comment]
I did find the current exception handling very confusing while implementing, you have to know that you need to trigger the exception throwing (aka maybeThrowError).

So I would think that FinTs should not swallow these exceptions at all.

Having said that, i settled on always using `ensureSuccess` and catch the exceptions

```php
} catch (TanRequiredException $error) {
    return $this->handleTanNeeded($request, $fints, $account, $action, $description);
} catch (ServerException $error) {
```

So no single catch block. 

I treat login just as any other action

```php
$action = $fints->login();
$action->ensureSuccess();
```

And submitTan requires an action which I also call ensureSuccess on

```php
$fints->submitTan($action, trim($request->request->get('tan')));
$action->ensureSuccess();
```

**Comment by Philipp91** [comment]
> But, to be honest, I didn't miss it yet 🤷‍♀️

> Having said that, i settled on always using `ensureSuccess`

Obviously your existing code has it all figured out. This change would be mostly to help new users of the library make mistakes by not calling `ensureSuccess()`, e.g.
```
$action = GetStatementOfAccount::create(...);
try {
  $fints->execute($action);
  if ($action->needsTan()) $fints->submitTan($action, getSomeTan());
} catch (...) {...}
$action->getStatement(); // This calls ensureSuccess() inside, but it's outside the try-block.
```

> So no single catch block.

I see. So you do use `TanRequiredException` and different `catch` blocks. But is it a single `try` block? I.e. do you always call `ensureSuccess()` right after `execute()` or `submitTan()`? (Apparently yes for the latter, but you haven't posted your `execute()` call, so I'm not sure about that one.)

**Comment by ampaze** [comment]
> But is it a single try block?

Yes one try block with two catch statements. I always call `ensureSuccess` right after execute.

I am all for throwing the exceptions automatically. 

Why do you think that `if ($action->needsTan())` is better?

**Comment by Philipp91** [comment]
> Why do you think that if ($action->needsTan()) is better?

More of a general feeling/rule ("if it's not an exceptional path, then don't model it with an exception" -- and clearly needing a TAN happens quite regularly).

> (I would have to use needsTan twice, on the login action and on the real action. No?)

Well, they could be managed by the same TAN-handling function, like in the example code. Currently, you don't have the login action inside your one `try` block either. In particular, nobody can do:

```
try {
  $login = $fints->login();
  $login->ensureSuccess();
  $action = ...;
  $fints->execute($action);
  $action->ensureSuccess();
} catch (TanRequiredException $e); {
  $tan = getSomeTanFromSomewhere();
  $fints->submitTan(/* Now what? Is it $login or is it $action ? */, $tan);
  /* Now what? Continue with `$action = ...`, which would need to be duplicated here? */
}
```

So every application will either handle all TAN requests with separate redundant code, or abstract out some sort of TAN handling function that takes advantage of the fact that all `$action instanceof BaseAction` as well as `$login instanceof BaseAction`.

**Comment by ampaze** [comment]
I do have my login action inside the try catch block and your example is close to what I am doing.

I don't need to submit the tan inside the catch block. As I have to ask for the TAN anyway. So when it is entered I am inside the try block again.

```php
try {
    $action = null;
    // TAN Eingabe durch Nutzer erfolgt und liefert auch den FinTs Zustand sowie die Action
    if ($request->isMethod('post') && $request->request->has('fints')) {
        /** @var BaseAction $action */
        $action = unserialize(base64_decode($request->request->get('action')));
        $account = $this->em->getRepository(Account::class)->find($request->request->get('account_id'));

        $fints = $this->getFinTsForAccount($account);
        $fints->loadPersistedInstance(base64_decode($request->request->get('fints')));
        $fints->submitTan($action, trim($request->request->get('tan')));
        $action->ensureSuccess();
    } else {
        $fints = $this->getFinTsForAccount($account);
    }

    if (!is_null($work)) {
        // Keine Action fortgeführt, also erstmal Login
        if (is_null($action)) {
            $action = $fints->login();
            $action->ensureSuccess();
        }

        // Login ist erfolgt, also eigentliche Action ausführen
        if ($action instanceof DialogInitialization) {
            if ($work instanceof BaseAction) {
                $action = $work;
                $fints->execute($action);
            } else {
                $action = $work($fints, $action);
            }
            $action->ensureSuccess();
        }
    }
} catch (TanRequiredException $error) {
    return $this->handleTanNeeded($request, $fints, $account, $action, $description);
} catch (ServerException $error) {
}
```

**Comment by Philipp91** [comment]
I see. This also looks good.

> (I would have to use needsTan twice, on the login action and on the real action. No?)

I guess you would indeed need to call it twice. But in exchange you could remove the `ensureSuccess()` calls. So if we don't count `}` as a line of code, you'd have the same number of lines.

Also the control flow would become clearer. Currently, a reader of your code needs to know that `ensureSuccess()` can throw `TanRequiredException` and thus the execution can (and regularly will) jump from there to the `handleTanNeeded()` call. That arguably makes the code more difficult to understand for people who aren't already familiar with it, so the "if it's not an exceptional path, then don't model it with an exception" rule applies here too. (Though I acknowledge that this might not matter to you at all, especially if it's a private code base.)

Another minor advantage of the clearer control flow is that IDEs will analyse it properly. Suppose you add another argument `$dialogId` to the `handleTanNeeded()` call, which you only populate after the login succeeded. Then if the bank wants a TAN on login already, the code would access an undefined variable and crash, which you could only catch by testing with a bank that actually wants login TANs. But if the login is immediately followed by `if (needsTan) handleTanNeeded(..., $dialogId)`, then it would become obvious to a reader and to an IDE that `$dialogId` is accessed (lexically and logically) before it's defined. (Safer programming languages wouldn't even allow accessing variables in the `catch` block that were declared in the `try` block, which would also prevent this kind of bug.)

**Comment by ampaze** [comment]
> I guess you would indeed need to call it twice. But in exchange you could remove the ensureSuccess() calls. So if we don't count } as a line of code, you'd have the same number of lines.

It's not really about the number of lines, even if I would use `needsTan` i would still have to call `ensureSuccess` or check for $isAvailable myself.

> "if it's not an exceptional path, then don't model it with an exception"

I know what you mean, but I wouldn't equate exception with totally unexpected. Then we would never need any specific Exception classes. 
Keep in mind that not all fints actions require a TAN, this even includes SEPA transfers in certain conditions.

**Comment by Philipp91** [comment]
> i would still have to call ensureSuccess or check for $isAvailable myself.

If that goes wrong, it means that `execute()` wasn't called at all. I'd consider this to be a problem on the level of an `AssertionError`, i.e. if that happens, the code is totally broken. So for me it'd be fine to just call `execute()` (which throws the main errors), then `needsTan()` to avoid the `TanRequiredException`, and then call any getters I need (or just assume that everything went smoothly in case of an action without results).
