### ISSUE TITLE
DirectDebit: Auftrag wird nicht angenommen

### ISSUE THREAD

**Issue by Chiller999** [nemiah/phpFinTS#284]
Hi,
ich wollte soeben eine SEPA-Lastschrift einreichen. Dies funktioniert auch in anderer Banking-Software.

Leider wird nach dem Absenden der TAN folgender Fehler ausgegeben:

**HIRMG:3:2+9050::Die Nachricht enthält Fehler.'HIRMS:4:2:3+9000::Auftrag nicht abgeschlossen. Etwas ist fehlgeschlagen.**

Würde mich sehr über Tipps freuen!

**Comment by Chiller999** [comment]
Nachtrag: Habe es auch mit falschen Login oder falscher TAN versucht. Dann werden andere Fehlermeldungen ausgegeben...

**Comment by Chiller999** [comment]
Nachtrag: Auch der Anfang ist natürlich abweichend:

HNHBK:1:3+000000000428+300+xxxxxxxxxxxxxxxxxxxxxxxx+4

statt

HNHBK:1:3+000000000428+300+xxxxxxxxxxxxxxxxxxxxxxxx+3

**Comment by Chiller999** [comment]
Update: Ich habe gerade herausgefunden, dass erst nach der TAN-Eingabe die vorherige Aktion überprüft wird und der Fehler vermutlich damit zusammen hängt.

**Comment by ampaze** [comment]
Da deine TAN Sende Nachricht scheinbar die vierte Nachricht ist, sieht es so aus als würdest du davor (versehentlich) eine Nachricht zuviel senden.

Das kann z.B. an der Art und Weise wie du die TAN Behandlung machst liegen.

Gibt es denn in den phpFints Logs ein HNHBK Segment  mit +3 am Ende?

**Comment by Chiller999** [comment]
@ampaze Danke für die Rückmeldung! Also beim Absende-Skript für die TAN gibt es nur zwei Log-Einträge. Bei der vorherigen Action müsste ich nochmal schauen.

Danke aber, dass es an `HKDME` liegt. Habe mir die vorherigen Logs nochmals angesehen und bemerkt, dass wohl nur `HKDSC` funktioniert bei der Apobank.

Wie kann ich dies umstellen?

**Comment by ampaze** [comment]
Also die Bank sagt zumindest, dass sie HKDME kann, sonst würdest du beim Abschicken der Nachricht eine Exception bekommen. Wenn du HKDSC benötigst, musst du das Segment implementieren und eine neue Action schreiben, die dies benutzt. 

Da es COR1 aber gar nicht mehr gibt, ist es schon merkwürdig das die Apobank nur das können soll.

Hast du nicht auch gesagt, dass alles in den Logs identisch war, d.h. die anderen Programme haben auch HKDME benutzt?

**Comment by Chiller999** [comment]
@ampaze Ich hatte erst nur die Logs von der TAN Übermittlung verglichen und die XML-Daten.
Andere Programme senden `HKDSC`.

**Comment by Chiller999** [comment]
Wo könnte man denn HKDME einfach in HKDSC austauschen?

**Comment by ampaze** [comment]
Denke nicht, dass man das so einfach tauschen kann. Du kannst in der [Spezifikation](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf) aber mal die benötigen Parameter jeweils vergleichen und HKDSC analog zu HKDME implementieren.

**Comment by Chiller999** [comment]
@ampaze Danke, dann wird es wohl doch etwas mehr Aufwand. Oder man wartet, bis die Bank ggf. doch noch etwas ändert 🙄

**Comment by Chiller999** [comment]
Lösung des Problems: Ein kleines Detail hatte ich nicht beachtet. Momentan werden wohl nur Buchungen mit `<BtchBookg>true</BtchBookg>` angenommen. Dann funktioniert es 🙄 egal ob CORE oder COR1...

**Comment by ampaze** [comment]
Gut das die Bank einem das mit klaren Fehlermeldungen zurückmeldet 🙄
