### ISSUE TITLE
SEPA Debit: Aus HKDSE wird HKDME

### ISSUE THREAD

**Issue by Cugar15** [nemiah/phpFinTS#285]
Hallo Zusammen,

   ich versuche terminierte Lastschriften bei der Bank einzureichen. Hierzu ein paar Fragen:

1) Laut Standard gibt es wohl die folgenden Möglichkeiten:
```
Lastschriften:

x	HKDSE Einreichung terminierter SEPA-Einzellastschriften 

	HKBSE Einreichung terminierter SEPA-Firmeneinzellastschriften 

Sammellastschriften:

x	HKDME Terminierte SEPA Sammellastschrift einreichen 

	HKBME Terminierte SEPA Firmensammellastschrift einreichen 
```

phpFinTS untersützt wohl HKDSE und HKDEM  - aber leider nicht HKBSE oder HKBME.
Ist das richtig?

Wenn ja, könnte HKBSE und HKBME ergänzt werden?

2) Wird eine terminierter SEPA-Einzellastschrift eingereicht - also HKDSE - wird immer eine HKDME, also eine terminierte SEPA Sammellastschrift mit einer Position erzeugt. 
Verantwortlich dafuer ist wohl der folgende Code in SendSEPADirectDebit.php:

```
// If the PAIN message contains a control sum, we should use it, if the bank also supports it
		
if ($useSingleDirectDebit && !is_null($this->ctrlSum) && !is_null($bpd->getLatestSupportedParameters('HIDMES'))) {
      $useSingleDirectDebit = false;
 }
```

Bei meiner Lastschrift ist die ctrlSum im XML vorhanden - erzeugt mit nemiah\phpSepaXml - und es gibt bei der Bank auch HIDMES (wobei es auch HIDSMS gibt).
Damit wird  $useSingleDirectDebit = false gesetzt und damit eine terminierte SEPA Sammellastschrift erzeugt.

Warum ist das so??

Danke fuer eine Rueckmeldung

**Comment by ampaze** [comment]
> phpFinTS untersützt wohl HKDSE und HKDEM - aber leider nicht HKBSE oder HKBME.
Ist das richtig?

Korrekt. Wenn sich diese Geschäftsvorfälle was z.B. die benötigen Felder angeht nicht groß unterscheiden, dann sollte es relativ einfach sein vermute ich. Da kannst du gerne einen PR basteln dazu. Was ist der inhaltliche Unterschied zwischen Firmenlastschriften und den Normalen?

> Warum ist das so??

Ich war der Meinung, dass es sinnvoller ist die Kontrollsumme auch auf FinTs Ebene zu übermitteln. Ein Sammler mit nur einer Lastschrift wird von den Banken mit denen ich zu tun hatte, wie eine Einzellastschrift behandelt. Wenn du das bei deiner Bank anders brauchst, könnte man dies zukünftig auch per Parameter steuerbar machen.

**Comment by Chiller999** [comment]
Firmenlastschriften können wohl nur beim Zahlungspflichtigen eingezogen werden, wenn der Bank des Zahlungspflichtigen das Mandat vorliegt. Und dies unterstützen wohl nicht alle Banken/Konten.

Man hat dann aber wohl den Vorteil, dass sich die Lastschrift nicht so leicht zurückbuchen lässt.

**Comment by ampaze** [comment]
Die Geschäftsvorfälle scheinen bzgl. benötigter Daten auf den ersten Blick bis auf den Namen komplett identisch zu sein. Du kannst ja mal testen, HKDSEv2.php und die Klasse darin umzubenennen in die Firmenvariante.

**Comment by Cugar15** [comment]
OK, erst mal vielen Dank fuer die Antworten.

Erst mal grundsaetzlich: @Chiller999: Es muss fuer beide Varianten ein gültiges Mandat vorliegen - ohne geht es nicht. Eine Basislastschrift kann aber wohl auch umgedeutet werden...

Der Unterschied zwischen den Varianten besteht in den Fristen und der Zurückbuchbarkeit.

@ampaze: Ja, ich habe mir das auch schon mal angesehen ob man die Varianten nicht einfach 'kopieren' kann. Bin aber mit der Materie und der Klasse noch nicht so vertraut.

Zum Thema Einzellastschrift: Vorschlag wäre erst zu prüfen ob die Bank HIDSES unterstützt und dann auch diese Variante durchführen - wenn nicht, dann prüfen ob HIDMES vorhanden ist und einen Sammler mit einer Lastschrift senden. 

Ich werde die beiden Themen mal trennen damit die Themen besser getrackt werden können.

**Comment by ampaze** [comment]
> Zum Thema Einzellastschrift: Vorschlag wäre erst zu prüfen ob die Bank HIDSES unterstützt und dann auch diese Variante durchführen - wenn nicht, dann prüfen ob HIDMES vorhanden ist und einen Sammler mit einer Lastschrift senden.

Hab noch nicht ganz verstanden warum genau du zwingend HIDSES benötigst.

**Comment by Cugar15** [comment]
Im Moment gehe ich davon aus, dass die Lastschrift 'funktioniert' - im Nachhinein betrachtet.

Wenn man SEPA machen will, dann sollte man da tunlichst keine Blödsinn machen weil es dann mit dem Mandat von der Bank sehr schnell vorbei ist. Deswegen teste ich hier auch sehr genau.

Wenn dieses wirklich super gute php Package (Lob!!) für einen größere Gemeinde und nicht nur 'insider' Verwendung finden soll, dann sollten meiner Meinung auch die Standards entsprechend behandelt werden.

Eine Konsequenz ist z.B., dass beim Sparkassen Bankingprogramm vier verschiedene Auftragsarten unterschieden werden:
Terminierte Überweisung, Terminierte Sammelüberweisung, Basis-Einzellastschrift und Firmen-Einzellastschrift.

Eigentlich hätte ich meine Tests in der Kategorie Basis-Einzellastschrift erwartet - da landen diese normalerweise wenn ich direkt  im Bankingprogram eingebe - aufgetaucht sind sie aber unter Terminierte Sammelüberweisung.

Also, wenn ich als user eine Einzellastschrift einreichen will, dann ist man schon etwas überrascht wenn man plötzlich mit einer Sammellastschrift konfrontiert wird und es kommen Fragen auf warum.

**Comment by ampaze** [comment]
Was sagst du zu #290?

**Comment by Cugar15** [comment]
Dieser Patch stellt sicher dass das 'gewuenschte' Verhalten einer Einzellastschrift als default erfolgt.
Kann man sicher so machen.

Hier noch eine Beobachtung/Anmerkung: Bei der Sparkasse muss die Tan per Generator dann aus Pin, Kontonummer des Debitors und Betrag errechnet werden. Also wird da schon eine checksum brechnet. Ob man die dann trotzdem noch braucht ist die Frage.
