### ISSUE TITLE
phpFinTS to support HKBSE and HKBME 

### ISSUE THREAD

**Issue by Cugar15** [nemiah/phpFinTS#286]
Currently, only HKDSE and HKDME are supported.

To support B2B, HKBSE and HKBME need to be supported.

Differences are: (In German)

CORE – Lastschrift:
Das BASIS – Lastschriftverfahren ersetzt die alten “Einzugsermächtigungen. Dient den Lastschriften auf Privat- bzw. Verbraucherkonten
Vorlauffrist beträgt 5 Tage bei einer Erstlastschrift und 2 Tage bei einer Folgelastschrift.
Rückgaberecht: 8 Wochen nach Einzug bzw. 13 Wochen bei nichtvorliegen eines gültigen Mandats

B2B – Lastschrift:
Die „Business -  to – Business“-Lastschrift ersetzt das Abbuchungsverfahren zwischen Firmen. Es kann nicht bei Kunden eingesetzt werden.
Die Vorlauffrist beträgt mindestens ein Tag.
Es besteht eine Prüfpflicht der Bank des Debitors (Zahlungspflichtigen) da eine Rückgabe der Lastschrift nach Einlösung nicht mehr möglich ist.

**Comment by ampaze** [comment]
Woher hast du die Fristen für Basis Lastschriften? Das deckt sich nicht mit dem was wir verwenden und unsere Bank an Vorlauffristen meldet.

**Comment by ampaze** [comment]
Wie im anderen Ticket schon besprochen, wäre es sehr hilfreich wenn du die bestehenden Segmente mal umbenennen könntest und testest ob es damit funktioniert.

**Comment by Cugar15** [comment]
Ich habe versch Quellen ge-googelt - waren alle konsistent mit den Fristen. Hier ein link auf einen Seite die alles sehr schoen zusammenfasst:

https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-lastschrift-sdd/sepa-vergleich-sdd-core-vs-sdd-b2b/

Es gibt aber auch viele andere Seiten mit den gleichen Aussagen und Fristen.

Ich werde mich mal versuchen und den code anpassen.. Mal schauen was passiert.

**Comment by ampaze** [comment]
Du kannst die Fristen mit `GetSEPADirectDebitParameters` bei deiner Bank abfragen. Wäre ja mal interessant. 

Für Business Lastschriften kann dann ja auch eigentlich CORE nicht die richtige Lastschriftart sein. D.h. das XML müsste evtl. auch anders sein.

**Comment by Cugar15** [comment]
Ja, im XML muss dann der type  anstatt CORE natuerlich auf B2B gesetzt werden.
Ich werde versuchen die Fristen mal abzufragen.

**Comment by Cugar15** [comment]
Also bei den Fristen kommt immer 2 Tage raus, egal was - das scheint mir aber mit der V1 zusammenzuhängen.

Ich habe jetzt mal die Ordner BSE und BME erstellt und den Inhalt ensprechend angepasst.

Dann versuche ich die BPD zu reporten in: GetSepaDirectDebitParameters.php
```
    public function createRequest(BPD $bpd, ?UPD $upd)
    {
        $type = $this->singleDirectDebit ? 'HIBSES' : 'HIBMES';
print_r($bpd);
```
Bei der BPD kommt hier folgendes raus:
[HIBMES] => Array ( [1] => Fhp\Segment\AnonymousSegment Object ( [type] => HIBMESv1 [segmentkopf] => Fhp\Segment\Segmentkopf Object ( [segmentkennung] => HIBMES [segmentnummer] => 93 [segmentversion] => 1 [bezugselement] => 3 ) ) )

Bei einem HIDMES steht da wesentlich mehr Information. Auch ist das kein AnonymousSegment Object

Muss ich noch mehr ändern damit das in den BPD erscheint - oder kann die Sparkasse kein B2B??

**Comment by Cugar15** [comment]
Ups, OK, hab noch was übersehen - jetzt erscheint das ganze auch in der BPD.

**Comment by Cugar15** [comment]
Ich habe jetzt einen Code der funktioniert - zumindest bis zum TAN request.

Ich würde den gerne zur Verfügung stellen - hab das aber noch nie gemacht.

Werde mich mal schlau machen wie das geht.
