### ISSUE TITLE
getSupportedTanMechanisms: assertion fails for class HITANv6

### ISSUE THREAD

**Issue by carli2** [nemiah/phpFinTS#287]
`lib/Fhp/Response/GetVariables.php` fails at line 49:

```
            if (!($hitans instanceof HITANSv6)) {
                throw new \AssertionError(); Bug
            }
```
the assertion is thrown even if `$hitans` is of the correct type.

I suppose it is a problem with 
```
use Fhp\Segment\HITANS\HITANSv6;
```

which has an other class name when parsed by the XML parser.

Can you please either fix the classname or remove the assertion?

**Comment by carli2** [comment]
Comment: I'm using the library via composer's autoload

**Comment by Philipp91** [comment]
You're using the old version of the library, which is not supported anymore. Please install from `master` for now.

**Comment by carli2** [comment]
What is the `composer` line for this version? I cannot deploy a git version; would be cool to release the new version on composer.

**Comment by Philipp91** [comment]
I'm working on a few last improvements to make sure the API is stable.

**Comment by ampaze** [comment]
> What is the `composer` line for this version? I cannot deploy a git version; would be cool to release the new version on composer.

You can use the version `dev-master` in the meantime. 
https://packagist.org/packages/nemiah/php-fints#dev-master
