### ISSUE TITLE
Aufsetzpunkte (aka Paginierung) nach TAN Eingabe funktionieren nicht, wenn man minimale Serialisierung verwendet

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#299]
Wenn man 

```
Fints::persist(true)
```
verwendet, um die Ausführung für die Abfrage der TAN zu unterbrechen, wird BDP und UPD nicht gespeichert. 

Wenn dann die Antwort der TAN Übermittlung einen Aufsetzpunkt enthält, kommt es zur Fehlermeldung

> Argument 1 passed to Fhp\Action\GetStatementOfAccountXML::createRequest() must be an instance of Fhp\Protocol\BPD, null given

Es ist doch eigentlich gar nicht nötig, für jeden Aufsetzpunk wieder `createRequest` aufzurufen. Es wäre völlig ausreichend das RequestSegment zu speichern und nur den Wert für den Aufsetzpunkt zu ändern und erneut abzuschicken.

Der Ansatz in FinTs::execute wäre also z.B. (auch gleich abgeändert auf ein RequestSegment pro Request)

```php
$requestSegment = null;
// Let the BaseAction implementation build its request segment.
if ($action->hasRequestSegment()) {
    $requestSegment = $action->getRequestSegment();
} else {
    $requestSegment = $action->createRequest($this->bpd, $this->upd);
    $action->setRequestSegment($requestSegment);
}
$requestSegments = is_array($requestSegment) ? $requestSegment : [$requestSegment];
```

Hab ich da was übersehen?

----

Eine Alternative wäre, die benötigen Daten aus BDP und UPD an der Action zu speichern und diese ebenfalls zu serialisieren. Dann kann man bei createRequest BDP optional machen und entsprechend reagieren wenn $bdp null ist.

**Comment by Philipp91** [comment]
In `submitTan()` gibt es doch einen `readBPD()`-Aufruf. Der müsste stattfinden bevor der Fehler auftritt, oder? Also liefert die Bank dann keine BPD zurück? Dann wäre es so, dass die Bank die BPD nur bei einer Dialoginitialisierung schickt, aber sonst nicht. Vielleicht könnte dann `submitTan()` die Situation erkennen und ein `HKVVB` mitschicken, wenn die BPD nocht nicht da sind, sodass sie gleich wieder geliefert werden?

**Comment by ampaze** [comment]
Die Bank hat keinen Grund die BPD mitzusenden. Nach der Übermittlung der TAN wird einfach die Antwort gesendet wie sie ohne TAN Unterbrechung gewesen wäre. Dieser Schritt funktioniert ja auch noch. Erst wenn die Paginierung ins Spiel kommt muss man weitere Anfragen senden, wofür man aktuell BPD und ggf. UPD braucht.

Kommt mir irgendwie unverhältnimäßig vor, die BPD erneut anzufragen. Der Request ist bis auf den Aufsetzpunkt ja identisch zu dem was vorher gesendet wurde, warum also nicht einfach an der Action speichern?
