### ISSUE TITLE
Keine Buchungsdaten - Volksbank

### ISSUE THREAD

**Issue by JarvisHome** [nemiah/phpFinTS#303]
Seit heute hat die Volksbank (zumindest bei uns) etwas am Schema geändert. Die Buchungen kommen rein, werden jedoch nicht erfolgreich geparst. 

Ich konnte das Problem beheben in dem ich in der Klasse Fhp\MT940 die Zeile 22 ersetzt/angepasst hab:
`if (substr_count($rawData, "\r\n-") > 0) $divider = "\r\n";
elseif (substr_count($rawData, '@@-') > 0) $divider = "@@";
else $divider = "\n";`

sprich: es scheint so als ob sich bei der VoBa das Trennzeichen geändert hat.

Da ich aber eigentlich keine Ahnung vom MT940 Parser hab sollte sich das mal jemand anschauen der in der Materie drin ist.

**Comment by fbett** [comment]
Hi, wir haben auch ein Konto bei der Volksbank und können dies bisher noch nicht bestätigen.
Zumindest die Umsätze vom 23.07. konnten erfolgreich gelesen werden.

> Die Buchungen kommen rein, werden jedoch nicht erfolgreich geparst.
Wie äußerst sich das? Wird eine Exception geworfen oder ein Fehler protokolliert (über den Logger)?
Welche PHP Version auf welcher Plattform (Linux/Windows) wird eingesetzt?

**Comment by JarvisHome** [comment]
Hallo fbett,
geäußert hat es sich so, dass die Umsätze (ohne Fehler) nicht zurückgegeben wurden. Ich hab dann den Logger angeworfen und geschaut was die Interaktion mit der Bank beinhaltet. Dort (in den Rohdaten) waren die Umsätze vorhanden. Im Parser ist der ganze Block jedoch (wegen fehlendem divider) übersprungen worden. Somit hat er zwar Saldo etc. abgerufen, jedoch keine Buchungen für den aktuellen Tag gemeldet (leerer Array)

Interessant dazu: wir haben mehrere Konten bei mehreren Banken (Volksbank, Kreissparkasse, BTV,...) - betroffen war jedoch lediglich die Volksbank. Hier ging es nur mit dem Trennzeichen "\n". Bei den anderen Banken ging es wie gewohn mit "\r\n". Scheint also kein lokales Problem wegen Windows / Unix zu sein.

auch die Rohdaten sahen (direkt von der Bank) unterschiedlich aus:

- Bei der Volksbank sehen die $cleanedRawData gleich aus wie $rawData (sprich: die FinTS Schnittstelle liefert schon sehr lange Zeichenketten ohne Zeilenumbruch)

- Bei der Kreissparkasse sind die cleanedRawData ungleich wie die $rawData ->weil dort die $rawData ab einer bestimmten Länge abgeschnitten sind und in der nächsten Zeile (mit \r\n) weiter gehen.

Ganz grob vereinfacht: die Volksbank liefert bei mir bereits über die Schnittstelle das Ergebnis was die Zeile 
`$cleanedRawData = preg_replace('#' . $divider . '([^:])#ms', '$1', $rawData);` 
sonst erst erstellt.

Hoffe das hilft weiter. Interessant finde ich dass der Effekt bei dir nicht aufzutreten scheint,...

**Comment by JarvisHome** [comment]
Nachtrag: hat sich erledigt. Seite heute geht es wieder mit der alten Version. Laut meinen Logs kommen die Daten nun wieder so wie gewohnt an. Ich vermute mal dass die Bank einen Bug auf der Schnittstelle hatte und dieser nun behoben wurde.

**Comment by fbett** [comment]
Ok, danke für deine Follow-Up!
War bestimmt so, wie von dir vermutet eine Fehlkonfiguration bei der Bank.
