### ISSUE TITLE
Can we fetch bank details inside a cron?

### ISSUE THREAD

**Issue by Foddy** [nemiah/phpFinTS#306]
Hi,

is it possible to fetch an account balance or the statement periodically on the server without having to enter a TAN every time the cron runs? We want to automatically process transactions but don't want to trigger the method manually…

Thanks!

**Comment by nemiah** [comment]
Hi @Foddy,

while it is possible to use a cronjob (I do it myself), in my experience you have to enter a login-TAN every 90 days.

Best,
Nena

**Comment by Foddy** [comment]
Thanks for this info! :)
