### ISSUE TITLE
"Banking-Programm nicht PSD2-fähig"

### ISSUE THREAD

**Issue by micronax** [nemiah/phpFinTS#31]
Hi,
seit der SCA/PSD2 Umstellung gestern erhalte ich trotz Angabe meiner Registrierungs- und Versionsnummer seitens der Sparkasse die Meldung:

```
Request Failed: Die Nachricht enthält Fehler. (9050); Banking-Programm nicht PSD2-fähig, bitte aktualisieren. (9075); Dialog abgebrochen (9800); Ungültige Auftragsnachricht? (9340)
```

`setTANMechanism` habe ich auch korrekt gesetzt.

Jemand eine Idee?

**Comment by nemiah** [comment]
Hallo,

hmm, diese Nachricht ist mir neu.
Funktioniert es mit der Hibiscus-Software?

Liebe Grüße
Nena

**Comment by roben** [comment]
Genau die Meldung erhalte ich bei der Sparkasse jetzt auch. Sobald ich mehr weiß, melde ich mich wieder.

**Comment by acsig** [comment]
Hibiscus läuft, nach reset der BPH Daten. Ich bekomme auch eine Fehlermeldung bei der Sparkasse. "setTANMechanism" kenne ich nicht. Habe ich da etwas übersehen? Wie kann ich die Registrierungsnummer angeben?

**Comment by nemiah** [comment]
@acsig Ok, super, dann vergleiche bitte das HBCI-Log von Hibiscus mit der Log-Ausgabe von phpFinTS. Irgendwo sollte der Unterschied sein.

**Comment by micronax** [comment]
Nachtrag: Erhalte den Fehler bei allen Sparkassen. Getestet bei Sparkasse Hanau, Frankfurt und Haspa (Hamburg).

Ich hatte gedacht, es hat ggf. etwas mit der `setTANMechanism`-Funktion zu tun, da (soweit ich verstanden habe) darüber ja die 2FA-Tans erzeugt werden.

**Comment by acsig** [comment]
Ich habe es gerade mit einer frisch generierten FinTS-Produkt-Registrierungsnummer getestet und bekomme trotzdem: 

```
2019-09-16 15:54:50 ERROR [HIRMG] Die Nachricht enthält Fehler.
2019-09-16 15:54:50 ERROR [HIRMG] Dialog abgebrochen
2019-09-16 15:54:50 ERROR [HIRMG] Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.
2019-09-16 15:54:50 WARNING [HIRMS] Bitte wenden Sie sich an den Hersteller des Banking-Programms.
2019-09-16 15:54:50 ERROR [HIRMS] Dialog abgebrochen - Banking-Programm ist nicht registriert.
2019-09-16 15:54:50 ERROR [HIRMS] Der Auftrag wurde nicht ausgeführt.
```
Möglicherweise braucht es etwas Zeit, bis sich die Registrierungsnummer "rumgesprochen" hat.

**Comment by micronax** [comment]
Die ursprüngliche Fehlermeldung in dieser Issue hat aber definitiv einen anderen Hintergrund. Die Nummer ist bereits seit Wochen registriert und wenn ich hier absichtlich einen Zahlendreher einbaue etc. erhalte ich eine andere Fehlermeldung.

**Comment by acsig** [comment]
OK, ich muss wohl mindestens bis morgen früh warten, im schlimmsten Fall 2-3 Tage, bis die Nr. überall bekannt ist habe ich gerade gelesen. Kann dann erst wieder dazu beitragen.

**Comment by dennobaby** [comment]
Die Meldung hat m.E.n. nichts mit der Registrierungsnummer zutun. Ich habe seit Monaten eine, meine Sparkasse meldet eben das gleiche.

@nemiah kann ich irgendwie beim debuggen helfen?

**Comment by roben** [comment]
Ich kann zumindest vermelden, dass es mit der Sparkasse auch funktionieren kann. Unsere Registrierung ist ca. einen Monat alt.
Ich erhalte lediglich folgende Meldungen von der Sparkasse bei der Initialisierung:
```
[HIRMG] Bitte beachten Sie die enthaltenen Warnungen/Hinweise.
[HIRMS] Der Auftrag wurde ausgeführt.
[HIRMS] BPD nicht mehr aktuell, aktuelle Version enthalten.
[HIRMS] Bitte eine Karte für die Verwendung mit chipTAN zuordnen.
[HIRMS] Zugelassene Zwei-Schritt-Verfahren für den Benutzer.
[HIRMS] Starke Kundenauthentifizierung nicht notwendig.
```

**Comment by nemiah** [comment]
Da bei mir die Sparkasse funktioniert, kann ich leider nicht debuggen.
Mein Vorschlag ist, die Logs von Hibiscus und phpFinTS zu vergleichen.

**Comment by dennobaby** [comment]
Kann es hier Versionsunterschiede geben? 
Ich beziehe phpFinTS über composer. Lt. composer gibt es noch kein Update, allerdings bin ich mir doch ziemlich sicher, dass es allein in den letzten Tagen einige Änderungen am Code gegeben hat?!

**Comment by nemiah** [comment]
Im composer gibt es noch nicht die aktuelle Version.

**Comment by acsig** [comment]
@dennobaby: Es sei denn man gibt als Version dev-master an... dann klappt es... war heute früh auch mein Fehler. 
@nemiah: Logs des ersten Aufrufs sehen schon unterschiedlich aus zwischen Hibiscus und phpFinTS. Für mich gerade schwer zu erkennen, was Prüfsummen etc. sind. Da da ja auch Zugangsdaten enthalten sind, poste ich das hier nicht ;-)

**Comment by dennobaby** [comment]
Interessant. Nach composer update mit dev-master funktioniert es bei mir wieder.

**Comment by micronax** [comment]
Mit der `dev-master`-Version erhalte ich einen neuen Fehler beim Abrufen der SEPA-Konten:

```
Request Failed: Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Falsche Segmentzusammenstellung (9110)
```

**Comment by acsig** [comment]
So, nach 2 Tagen hat sich die neue Registrierungsnummer wohl rumgesprochen. Bei der Sparkasse Herford funktioniert der Zugriff nun. Allerdings frage ich nur den Kontostand, bzw. die Einzelbuchungen ab.

**Comment by micronax** [comment]
Endless story: Mit der neusten `dev-master` Version und einer definitiv bekannten Registrierungsnummer erhalte ich nun:

```
[Fhp\Dialog\Exception\FailedRequestException]
  Request Failed: Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.(Die angegebene Bankreferenz/
  Dialog-ID ist nicht gültig.) (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)
```

**Comment by acsig** [comment]
Das klingt nach einer anderen (alten) Baustelle. Ggf. führende Nullen bei der Kontonummer weglassen? 
Wann kommt der Fehler? Funktioniert 
`$fints = new FinTs(
    FHP_BANK_URL,
    FHP_BANK_PORT,
    FHP_BANK_CODE,
    FHP_ONLINE_BANKING_USERNAME,
    FHP_ONLINE_BANKING_PIN,
    $oLogger,
    FHP_REGISTRATION_NO,
    FHP_SOFTWARE_VERSION
    );

var_dump($fints->getVariables());`

bei Dir, oder gibt es da auch schon Fehler?

**Comment by micronax** [comment]
Danke für deine Antwort :) `getVariables()` funktioniert ohne Fehler:

```
{#1676
  +"tanModes": array:7 [
    910 => "chipTAN manuell"
    911 => "chipTAN optisch"
    912 => "chipTAN-USB"
    913 => "chipTAN-QR"
    920 => "smsTAN"
    921 => "pushTAN"
    900 => "iTAN"
  ]
}
```

**Comment by roben** [comment]
"Die angegebene Bankreferenz/ Dialog-ID ist nicht gültig." deutet darauf hin, dass der Dialog vorher schon abgebrochen wurde. Was werden denn vorher für Meldungen (HIRMG und HIRMS) von der Bank geloggt?

**Comment by micronax** [comment]
OK, sorry. Habe eben realisiert, dass ich die SEPA-Accounts problemlos abrufen kann und auch die Buchungsliste (Hier wird dann nach TAN gefragt, aber das ist ja mein Problem)

Der og. Fehler `Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.(Die angegebene Bankreferenz/Dialog-ID ist nicht gültig.)` tritt beim Abrufen des Saldos per `getSaldo($sepaAccount)` auf.

**Comment by micronax** [comment]
> OK, sorry. Habe eben realisiert, dass ich die SEPA-Accounts problemlos abrufen kann und auch die Buchungsliste (Hier wird dann nach TAN gefragt, aber das ist ja mein Problem)
> 
> Der og. Fehler `Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.(Die angegebene Bankreferenz/Dialog-ID ist nicht gültig.)` tritt beim Abrufen des Saldos per `getSaldo($sepaAccount)` auf.

Da das getSaldo()-Problem nichts mehr mit der ursprünglichen Issue hier zu tun hat, habe ich eine neue Issue aufgemacht: https://github.com/nemiah/phpFinTS/issues/44

**Comment by micronax** [comment]
> > So, nach 2 Tagen hat sich die neue Registrierungsnummer wohl rumgesprochen. Bei der Sparkasse Herford funktioniert der Zugriff nun. Allerdings frage ich nur den Kontostand, bzw. die Einzelbuchungen ab.
> 
> Bei der Sparkasse Lemgo besteht das Problem auch mit dev-master noch. Hast du darüber hinaus noch etwas angepasst?

Nein, habe die aktuelle `dev-master´-Version verwendet. Wie gesagt, das Abrufen des Konto-Saldos per `FinTS::getSaldo()` funktioniert nicht, das Abrufen der Konto- und Buchungsliste jedoch funktioniert bei mir nun problemlos.

**Comment by micronax** [comment]
Für Alle, die das gleiche Problem haben: `dev-master` statt dem lateste release `2019.5` verwenden.

**Comment by jh1987** [comment]
Uncaught exception 'Fhp\Dialog\Exception\FailedRequestException' with message 'Request Failed: Bitte wenden Sie sich an den Hersteller des Banking-Programms. (3079); Dialog abgebrochen - Banking-Programm ist nicht registriert. (9078); Der Auftrag wurde nicht ausgeführt.(Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.) (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)'

Das Problem ist, dass ich nicht bei https://www.hbci-zka.de/ registriert bin, korrekt?
Vielen Lieben Dank für die Hilfe

**Comment by nemiah** [comment]
@jh1987 vermutlich, ja :wink:

**Comment by dsentker** [comment]
> So, nach 2 Tagen hat sich die neue Registrierungsnummer wohl rumgesprochen. Bei der Sparkasse Herford funktioniert der Zugriff nun. Allerdings frage ich nur den Kontostand, bzw. die Einzelbuchungen ab.

@acsig Wie genau hast du das angestellt? Bei mir erhalte ich die Nachricht: Request Failed: Die Nachricht enthält Fehler. (9050); Banking-Programm nicht PSD2-fähig, bitte aktualisieren. (9075); Dialog abgebrochen (9800); Ungültige Auftragsnachricht? (9340)

Ich erhalte auch nur Kauderwelsch bei $fints->getVariables(). Kann mich jemand aufklären?
![https://i.imgur.com/jLDGzKm.png](https://i.imgur.com/jLDGzKm.png)
