### ISSUE TITLE
Only supports VerfahrensparameterZweiSchrittVerfahrenV6

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#312]
Hallo zusammen,

ein Kunde hat bei mir die Exception "Only supports VerfahrensparameterZweiSchrittVerfahrenV6" erhalten.
Sie wird in der FinTs.php in Zeile 627 geworfen.

$this->selectedTanMode ist vom Typ Fhp\Segment\ **HITANS** \VerfahrensparameterZweiSchrittVerfahrenV6 und erwartet wird wohl Fhp\Segment\ **TAN** \VerfahrensparameterZweiSchrittVerfahrenV6.

Ich habe es jetzt mal auskommentiert und es läuft :grin: 

Ich denke mal, das hängt auch mit der HINTANv7 zusammen. Kann das jemand fixen? Ich kenne mich leider nicht mehr aus in eurem Code und mein fix würde so aussehen:

if (!($this->selectedTanMode instanceof VerfahrensparameterZweiSchrittVerfahrenV6 _OR $this->selectedTanMode instanceof Fhp\Segment\HITANS\VerfahrensparameterZweiSchrittVerfahrenV6_))  :blush: 

Liebe Grüße
Nena

**Comment by Philipp91** [comment]
Die Datei wurde mal [verschoben](https://github.com/nemiah/phpFinTS/commit/784e8cb45db128dec3553d76e0cfed6efecccd79), und ein paar Verwandte der Datei auch. Im heutigen Code gibt es den ganzen 'Fhp\Segment\HITANS` Namespace nicht mehr. Vermutlich hat der Kunde noch ein paar alte Dateien rumliegen, weil er beim Push einer neuen Version die alten Dateien nicht löscht.

**Comment by nemiah** [comment]
Danke für den Hinweis, ich habs mal so weitergegeben. Eigentlich sagt meine Anleitung, dass sie ein Update immer in ein neues Verzeichnis installieren sollen. Naja…
