### ISSUE TITLE
Uncaught InvalidArgumentException: Unsupported segment type/version Fhp\Segment\HITANS\HITANSv7

### ISSUE THREAD

**Issue by ticktoo** [nemiah/phpFinTS#314]
Since Friday, 20.11.2020 there occures an error when trying to get the supported TAN mechanisms against once specific bank institute (Sparkasse). With another bank institute (Fiducia) it still works very well.

```
PHP Fatal error:  Uncaught InvalidArgumentException: Unsupported segment type/version Fhp\Segment\HITANS\HITANSv7 in vendor/nemiah/php-fints/lib/Fhp/Segment/BaseSegment.php:98
Stack trace:
#0 vendor/nemiah/php-fints/lib/Fhp/Response/GetVariables.php(41): Fhp\Segment\BaseSegment::parse('HITANS:177:7:4+...')
#1 vendor/nemiah/php-fints/lib/Fhp/Response/GetVariables.php(19): Fhp\Response\GetVariables->parseTanModes()
#2 vendor/nemiah/php-fints/lib/Fhp/Response/GetVariables.php(24): Fhp\Response\GetVariables->get()
#3 vendor/nemiah/php-fints/lib/Fhp/Response/Response.php(158): Fhp\Response\GetVariables->getSupportedTanMechanisms()
#4 vendor/nemiah/php-fints/lib/Fhp/Dialog/Dialog.php(490): Fhp\Response\Response->getSupportedTanMechanisms()
#5 vendor/nemiah/php-fints/lib/Fhp/FinTs.php(218): Fhp\Dialog\Dialog->syncDialog(NULL, NULL)
#6 vendor/nemiah/php-fints/lib/Fhp/Segment/BaseSegment.php on line 98
```

Error occures with most recent version available via composer. The Banking website currently doesn't require a TAN authorisation on manual login.

Any help is appreciated. If I can provide you with anything helpful, let me know.

Thank you
Sebastian Kraus
ticktoo Systems

**Comment by Philipp91** [comment]
Duplicate of #309.

> Error occures with most recent version available via composer.

My `composer.lock` says:
```
"name": "nemiah/php-fints",
"version": "3.0.0",
```

And the error message you sent, specifically the `Unsupported segment type/version` bit, is not present in the library code that Composer downloaded for me. So I suspect you have an old version still. (Be sure to run `composer update`, not just `composer install`.)

**Comment by nemiah** [comment]
Yes, I think, too, that you are using the old version.

**Comment by ticktoo** [comment]
Sorry, that was it.
