### ISSUE TITLE
Anpassungen HKKAZ zur 3. KW 2021

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#323]
Hallo zusammen, betrifft uns das?

> Sehr geehrte Damen und Herren,
> 
> aus programmtechnischen Gründen mussten wir Anpassungen beim HKKAZ vornehmen.
> 
> Unser Ziel war es die Anpassungen zum bisherigen HKKAZ so gering wie möglich zu halten.
> Leider kann es zu einigen wenigen Abweichungen kommen, welche wir Ihnen hiermit im Vorfeld mitteilen möchten.
> 
> Übersicht der Änderungen:
> 
> Feld :61:
> 
> - Bei Nichtbelegung der Kundenreferenz wird „NONREF“ eingestellt. Dies war teilweise bisher nicht der Fall.
> - Teilweise konnten die SEPA-Referenzdaten nicht ermittelt werden. In diesen Fällen wurde die eigentlich vorhandene Kundenreferenz nicht berücksichtigt. Dies wurde behoben.
> 
> Feld :86:
> 
> - Teilweise konnten die SEPA-Referenzdaten nicht ermittelt werden. In diesen Fällen wurde die eigentlich vorhandene Kundenreferenz nicht berücksichtigt. Dies wurde behoben.
> - Beim Umbruch der 20er-Subfelder bleibt ein Blank vor dem Zeilenumbruch bestehen.
> - Teilweise erfolgte ein Umbruch, obwohl die maximale Länge von 65-Zeichen nicht überschritten wird. Dies wurde behoben.
> - Beim letzten 20-er Subfeld vor der Ausgabe der 30-er Subfelder wird kein Blank mehr angehangen.
> - Ein leeres Subfeld 31 wird nicht mehr geliefert.
> 
> Die Anpassungen werden ab dem 19.01.2021 pilotiert und stehen ab dem 21.01.2021 bei allen Banken zur Verfügung.

**Comment by ampaze** [comment]
Es betrifft scheinbar was die Bank ins MT940 Format packt, damit hab ich mich schon länger nicht mehr beschäftigt.

Die einzige evtl. relevante Änderung die ich spontan sehe ist

> Beim Umbruch der 20er-Subfelder bleibt ein Blank vor dem Zeilenumbruch bestehen.

Aber dies führt maximal dazu, dass erneut abgeholte Umsätze nicht mehr mit vorher Abgerufenen übereinstimmen. Weil jetzt ein Leerzeichen korrekt erhalten bleibt.

**Comment by nemiah** [comment]
> Aber dies führt maximal dazu, dass erneut abgeholte Umsätze nicht mehr mit vorher Abgerufenen übereinstimmen. Weil jetzt ein Leerzeichen korrekt erhalten bleibt.

Ok, das wäre in meinem Fall ungünstig, da es ja keinen anderen Weg gibt um festzustellen, ob es Umsatz schon bekannt ist. Mal sehen, wie es sich entwickelt…

**Comment by ampaze** [comment]
> Ok, das wäre in meinem Fall ungünstig, da es ja keinen anderen Weg gibt um festzustellen, ob der Umsatz schon bekannt ist. Mal sehen, wie es sich entwickelt…

Also Umsatzinhalte vergleichen ist meiner Meinung nach keine gute Idee. Was machst du wenn dir jemand zweimal hintereinander den gleichen Betrag schickt?

Afaik ist schlicht die Reihenfolge pro Buchungstag das entscheidende Merkmal, da sich diese nicht ändert auch bei mehrmaligem Abrufen des gleichen Tages.

**Comment by nemiah** [comment]
> Also Umsatzinhalte vergleichen ist meiner Meinung nach keine gute Idee. Was machst du wenn dir jemand zweimal hintereinander den gleichen Betrag schickt?

Ist sein Jahren kein Problem. Ich glaube, die Bank lässt auch zweimal den gleichen Betrag mit dem gleichen Verwendungszweck nicht zu. Passt schon, wenn es zum Problem wird, dann sehe ich es mir an. Danke für die Warnung :blush:
