### ISSUE TITLE
Only supports Prozessvariante 2 bei Hypovereinsbank

### ISSUE THREAD

**Issue by torbenc** [nemiah/phpFinTS#326]
Hallo,

erstmal vielen Dank für die Entwicklung dieser tollen Library. 

Wenn ich in der aktuellen Version unter Samples als Minimalbeispiel meine Zugangsdaten der Hypovereinsbank (mit BLZ 70020270) in der init.php eingebe, stirbt login.php direkt mit 

``Uncaught Fhp\UnsupportedException: Only supports Prozessvariante 2``

Muss ich irgendwo explizit Prozessvariante 2 wählen oder habe ich etwas übersehen?

**Comment by Philipp91** [comment]
Jein. Du wählst ja mit `selectTanMode()` einen TAN-Modus aus. Du hast einen gewählt, bei dem `TanMode::isProzessvariante2()==false`. Solche TAN-Verfahren werden von der Bibliothek im Moment nicht unterstützt. 

Die Bibliothek kann einen Auftrag abschicken und anschließend eine TAN-Challenge beantworten (Variante 2). Für Variante 1 müsste die Bibliothek einen Hash-Wert des Auftrags berechnen (nicht implementiert, ist vmtl. schwierig), ihn einschicken um eine Challenge anzufordern (nicht implementiert), in der Zwischenzeit den eigentlichen Auftrag zwischenspeichern (implementiert oder leicht umzustellen) und dann mit der Antwort auf die Challenge (d.h. mit der TAN) den Auftrag erst einschicken.
