### ISSUE TITLE
ING wirft Fehler "Der anonyme Dialog wird nicht unterstützt."

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#327]
Hallo zusammen,

ein Kunde hat ein Konto bei der ING und was ich in den anderen beiden issues gelesen habe, sollte die Bank inzwischen funktionieren.

Ich bekomme aber hier die Fehlermeldung "Der anonyme Dialog wird nicht unterstützt.", wenn ich einfach `$fints->getTanModes();` machen will.

Es funktioniert nichtmal `getBpd()` :disappointed: 

Hat jemand eine Idee?

Wer es testen möchte: BLZ 50010517, Server https://fints.ing.de/fints/, Benutzer und Passwort sollten ja noch keine Rolle spielen.

**Comment by Cugar15** [comment]
Hi, 

   hier ist was ich gemacht habe:

``` 
                if ($blz == "50010517") {  // ING does not honor tans!!
			$fints->selectTanMode(new Fhp\Model\NoPsd2TanMode());
		} else {
			$fints->selectTanMode($tanMode, $tanMedium);
		}

```

Das geht bei mir...

**Comment by nemiah** [comment]
Super, danke, damit geht es schon mal weiter :+1: 
Ich probiere es dann morgen mit dem Kunden :blush:

**Comment by Cugar15** [comment]
Vielleicht eins noch: 
Bei der ING kann man im Prinzip nur die Kontoauszuege der letzten 90 Tage abfragen. 
Mehr geht scheinbar nicht.

**Comment by nemiah** [comment]
Super, es funktioniert, danke dir! :+1: :smiley:
