### ISSUE TITLE
Hypovereinsbank-Spaß

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#328]
Wir hatten in der alten Version folgende Bedingung eingebaut:

        if ($this->url == 'https://hbci-01.hypovereinsbank.de/bank/hbci') {
            $this->logger->notice("Using 70020270 instead of $bankCode for Hypovereinsbank");
            $bankCode = '70020270';
        }

Könnten wir wieder reinmachen, damit es auch mit dieser Bank wieder funktioniert.

Liebe Grüße
Nena

**Comment by ampaze** [comment]
Müsste die Hypovereinsbank die korrekte BLZ für den Zugang nicht bei den FinTs Zugangsdaten angeben? Wird ja sonst mit keiner Banksoftware funktoinieren? Wie ist denn die Fehlermeldung mit falscher BLZ?

**Comment by nemiah** [comment]
Weiß nicht, die Leute tippen halt die BLZ ihrer Bank ein: 71120078
Dann kommt "Unbekanntes Kreditinstitut."
Mit Hibiscus kam auch eine Fehlermeldung :woman_sh

**Comment by ampaze** [comment]
Würde es eigentlich nicht als Aufgabe von FinTs sehen die Nutzereingaben zu korrigieren. Vor allem wenn sich dann die benötigte BLZ mal ändern sollte. 
Kannst du es nicht ggf. in deine Software packen?

**Comment by nemiah** [comment]
Ich weiß was du meinst, so habe ich es aktuell auch gemacht. Da das Problem aber seit damals wieder aufgetaucht ist, würde ich es an zentraler Stelle lösen.

**Comment by Philipp91** [comment]
Gibt nicht die Bank selbst diese Angaben raus, also die FinTS-URL und ihre BLZ? Dann müsste sie selbst darauf hinweisen, dass die BLZ des eigentlichen Kontos egal ist und man für den FinTS-Zugang eben diese spezielle BLZ verwenden soll. D.h. die "zentrale Stelle" sollte die Bank sein, dann wäre das Problem auch gleich für andere FinTS-Anwendungen gelöst.

Was man in der Bibliothek haben könnte wäre ein generelles Mapping von BLZ zu URL und "technischer BLZ". Denn damit könnten Anwendungen den Nutzer einfach nur nach der BLZ auf seiner Bankkarte fragen (die weiß man ja eh, ohne dass man bei der eigenen Bank auf der Webseite nach den FinTS-Daten schaut). Vielleicht gibt es sowas schon irgendwo (auf GitHub, aber nicht unbedingt in PHP) wo man es anzapfen könnte.

**Comment by nemiah** [comment]
Mag sein, aber ich werde nicht anfangen, die Banken anzuschreiben :no_good: :open_mouth: 

Ja, so eine Liste gibts schon und das liefere ich bei meiner Anwendung auch mit. Die Liste gibt zu der BLZ auch die URL aus, aber dann funktioniert es halt nicht. :woman_shrugging: 

Aber bevor wir da jetzt zu kompliziert werden, nehme ich die Extras für die ING und die Hypo einfach mit in die Readme auf…
