### ISSUE TITLE
Wie kann man neue Segmente hinzufügen

### ISSUE THREAD

**Issue by ZwenAusZwota** [nemiah/phpFinTS#329]
Hallo zusammen,

ich habe 4 Segmente für HKWPD (/Segment/WPD/[HIWPD.php, HIWPDv5.php, HIWPDSv5.php, HKWPDv5.php]) geschrieben und das Mapping in der NameMapping.php angepasst.
Allerdings werde diese Segmente offensichtlich nicht berücksichtigt.
Wo und wann werden die Segmente eigentlich geladen/den Geschäftsvorfällen aus/in der BPD zugeordnet?

Danke - Sven

**Comment by Philipp91** [comment]
Siehe https://github.com/nemiah/phpFinTS/issues/268#issuecomment-790116283

**Comment by ZwenAusZwota** [comment]
Danke. Die Benennung der Dateien und Klassen ist schon mal korrekt, aber offensichtlich werden die Klassen nicht importiert.
Das liefert der Parser:
Fhp\Segment\HIWPDS\HIWPDSv5
Fhp\Segment\WPD\HIWPDSv5

**Comment by Philipp91** [comment]
Alles klar, also funktioniert es? Wenn ja, bitte diesen Issue schließen.
