### ISSUE TITLE
get "vorgemerkte Buchungen" Postbank

### ISSUE THREAD

**Issue by Spica13** [nemiah/phpFinTS#336]
Is there a simple way to get the STARTDISP from statementOfAccount.php:

:20:STARTUMS
:21:NONREF
:25:70010080/5xxxxxxxx
:28C:0
:60F:C210328EUR123,45
:61:2103290329D50,01N005NONREF
:86:106?00KARTENZAHLUNG?20Referenz xxx?22Ma
ndat OFFLINE?23Einreicher-ID DE09xxx?25AGIP TOWN, xxx/DE?28Terminal xxx?34
011?60Folgenr. xxx Verfalld. xxx
:62F:C210331EUR123,45
-+@350@
**:20:STARTDISP**
:25:70010080/5xxxxxxxx
:28C:0
:34F:EUR20,00
:13D:2103311305+0200
:61:2104070330D20,00N010NONREF
:86:000?20LASTBUCHUNG, BEZAHLFUNKTION?21 EC-KARTE OHNE PIN, 30.03.2?2
2021 14:15:24
:90D:2EUR60,00
:90C:0EUR0,00
-''HNHBS:5:1+3'

The rawData I got from PostbankMT940.php but there are only the STARTUMS which will be parsed.
Is there a simple way to parse the STARTDISP data?

I've actualy no clue where I should start to get this done.

**Comment by djm03** [comment]
Currently I have the same problem: Daily between about 07:30 p.m. and 08:10 p.m. incoming SEPA realtime  payments are just visible as reserved transactions in my Postbank account. 

I have noticed that these reserved transactions are recorded by the script in

getNichtGebuchteUmsaetze

but I don't know how I can read it out for further processing.
