### ISSUE TITLE
Property Property [ <default> public $segmentkopf ]\n must be annotated.

### ISSUE THREAD

**Issue by soproho** [nemiah/phpFinTS#337]
Hi,

i've updated to PHP 7.4 yesterday and now I get an error when calling any methods to retrieve information from the bank, starting with getTanModes().

An `InvalidArgumentException` is thrown, saying "Property Property [ <default> public $segmentkopf ]\n must be annotated." in "Fhp/Segment/BaseDescriptor.php". But it seems that the annotation is there.

Are there any suggestions how this can happen?

Best Regards
Philipp

**Comment by fbett** [comment]
Hi, 
are you using the latest dev-master version? 

I have there PHP 7.4 installations - all are working fine, since at least a year.

**Comment by soproho** [comment]
Thanks for the reply...i just found out that also my settings for the Zend Opcache removed the comments and therefore no annotations at all have been found.

The correct ini value must be `opcache.save_comments=1` to keep comment. See https://stackoverflow.com/a/42087434
