### ISSUE TITLE
Samples Warning: Use of undefined constant STDIN ...

### ISSUE THREAD

**Issue by thomaslanger** [nemiah/phpFinTS#338]
In tanModesAndMedia.php

to fix:

Line 27: $tanModeIndex = trim(fgets(STDIN));

insert before line 27 : $stdin = fopen('php://stdin', 'r');
change
$tanModeIndex = trim(fgets(STDIN));
in 
$tanModeIndex = trim(fgets($stdin));

Line 51: $tanMediumIndex = trim(fgets(STDIN));
change in
$tanMediumIndex = trim(fgets($stdin));

**Comment by Philipp91** [comment]
Does this happen when you run that file on the command line or in a server/browser?

**Comment by thomaslanger** [comment]
Via Server+Browser

**Comment by Philipp91** [comment]
The `tanModesAndMedia.php` doesn't work there. It uses `STDIN` (or `php://stdin` after your change), which doesn't exist there. You need to run it in a shell with `php Samples/tanModesAndMedia.php`.
