### ISSUE TITLE
Sample browser.php

### ISSUE THREAD

**Issue by thomaslanger** [nemiah/phpFinTS#339]
Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors:

Function Parameter in $fints in Zeile 35: function handleRequest() ist nicht initialisiert.

Fix, in Zeile 33 folgendes einfügen: $fints = \Fhp\FinTs::new($options, $credentials);

**Comment by Philipp91** [comment]
Aber das ist ja schon [hier](https://github.com/nemiah/phpFinTS/blob/fce921b5311ee3c15eb075c25627a0584c6bee99/Samples/browser.php#L92)?

**Comment by thomaslanger** [comment]
Hat sich erledigt.
