### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [nemiah/phpFinTS#340]
Hi, can you add the following topics to this repository?
* https://github.com/topics/fints
* https://github.com/topics/hbci
* https://github.com/topics/php
* https://github.com/topics/banking

Thanks!

**Comment by nemiah** [comment]
:heavy_check_mark:

**Comment by mendel5** [comment]
👍

**Comment by mendel5** [comment]
Thanks 👍
