### ISSUE TITLE
MT940: Storno Credit and Storno Debit

### ISSUE THREAD

**Issue by DanielEgenolf** [nemiah/phpFinTS#341]
Hi,

thanks for this awesome FinTS wrapper! I have found one issue regarding the amount of statements. This wrapper differentiates between "credit" (C) and "debit" (D). But there are two more options, precisely: "Storno Credit" (RC) and "Storno Debit" (RD).

So if this tool catches some "storno" transactions, the getCreditDebit function returns not the correct sign/type.
May you please fix this issue and support these types too?

More information can be found here:
e.g: https://www.kontopruef.de/mt940s.shtml

Thanks and kind regards
Daniel

**Comment by Philipp91** [comment]
Looks like it's already implemented: https://github.com/nemiah/phpFinTS/blob/c0c14085b441f3b70016fb3f186fef1bc503ef9c/lib/Fhp/MT940/MT940.php#L76-L79

**Comment by DanielEgenolf** [comment]
Yes, but I think it is missing here (a few lines above):

MT940.php:

$cdMark = substr($day[$i], 0, 1);                    if ($cdMark == 'C') {                        $result[$soaDate]['start_balance']['credit_debit'] = static::CD_CREDIT;                    } elseif ($cdMark == 'D') {                        $result[$soaDate]['start_balance']['credit_debit'] = static::CD_DEBIT;                    }

**Comment by DanielEgenolf** [comment]
https://github.com/nemiah/phpFinTS/blob/c0c14085b441f3b70016fb3f186fef1bc503ef9c/lib/Fhp/MT940/MT940.php#L49-L54

**Comment by Philipp91** [comment]
This MT940 parser code is really hard to read. My guess is that that upper code parses the overall balance of the account (which can be positive or negative, but not cancelled).

**Comment by Philipp91** [comment]
> the getCreditDebit function returns not the correct sign/type.

Can you reproduce this? Could you provide an input string for `MT940::parse()` that returns a wrong result?

**Comment by Philipp91** [comment]
The library should expose `bool Transaction::isStorno()` or `bool Transaction::isCancellation()`, and it should be filled by the MT940 parser based on an expression like `.. =='RC' || .. == 'RD'`. Then your application can flip the sign on the amount when displaying it or using it to calculate balances.

Other applications may choose to find the matching original transaction and just delete both, or mark the original as cancelled in some database. So I think the library shouldn't just internally/magically flip the sign, but rather just hand out the information as a boolean.

**Comment by DanielEgenolf** [comment]
Exposing the library with the function `bool Transaction::isStorno()` is a great idea if `RC or RD` is set. Do I have to create a pull request for that or how should I proceed now?
Thanks Philipp for your help!

**Comment by DanielEgenolf** [comment]
I have created a pull request for this:
https://github.com/nemiah/phpFinTS/pull/342
So I will close this issue.

**Comment by Philipp91** [comment]
> So I will close this issue.

Btw GitHub has a feature where you can write "Fixes #nnn" in the pull request's description, and it will automatically close the issue once the pull request is merged.
