### ISSUE TITLE
Merkmal ob TAN erforderlich

### ISSUE THREAD

**Issue by roben** [nemiah/phpFinTS#35]
Weiß jemand, ob es in der Response irgendein einheitliches Merkmal gibt, dass eine TAN erforderlich ist? Oder ist das eine eigene Abfrage im Vorhinein?

Die Sparkasse läuft bei den Umsätzen ohne TAN durch, die Postbank antwortet schon bei `getSEPAAccounts` mit `Auftrag ausgeführt. (0020); BPD nicht mehr aktuell. Aktuelle Version folgt. (1040); Meldung unterstützter Ein- und Zwei-Schritt-Verfahren (3920); Starke Authentifizierung ab dem 2019-09-08 erforderlich. (3075); Gewähltes Zwei-Schritt-Verfahren nicht unterstützt. (9200); Teilweise fehlerhaft. (9050)` in verschiedenen Severities und es kommt zu einer `FailedRequestException`. Zumindest unter https://wiki.windata.de/index.php?title=HBCI-Fehlermeldungen konnte ich aber keinen Code davon als eindeutig identifizieren.

**Comment by roben** [comment]
Aus https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Formals_2017-10-06_final_version.pdf:
"Zur Einleitung des Prozesses der Gewährleistung einer starken Kundenauthentifizierung gemäß [PSD2] muss bei TAN-Verfahren ein HKTANSegment ab Segmentversion #6 eingestellt werden, wenn ein Kreditinstitut die Verwendung von HKTAN#6 unterstützt (BPD). Ansonsten kann der Dialog vom Institut mit dem Rückmeldungscode 9075 – Dialog abgebrochen - Starke Authentifizierung erforderlich abgewiesen werden. "

9075 kommt aber leider nicht. Eventuell liegt es aber auch daran, dass wir ein leeres HKTAN schicken, wenn keine TAN übergeben wurde. Ich forsche weiter.

**Comment by roben** [comment]
Ich sammel hier mal weiter, das hier ist recht vielversprechend:

1. Fortführen des Zwei-Schritt-TAN-Verfahrens. Dies wird vom Kreditinstitut generell durch den neuen Rückmeldungscode 0030 Auftrag empfangen - Sicherheitsfreigabe erforderlich signalisiert.
2. Keine starke Kundenauthentifizierung erforderlich. Dies wird durch den Rückmeldungscode 3076 Keine starke Authentifizierung erforderlich angezeigt, zusätzlich zu fachlichen Rückmeldungen zum eingereichten Auftrag wie z. B. 0010 Auftrag entgegengenommen.

**Comment by roben** [comment]
Weiter gehts, nachdem ich mit Windata verglichen habe:
Wenn keine TAN erforderlich ist, schickt die Postbank
`HIRMS:4:2:4+3920::Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:930+3076::Keine starke Authentifizierung erforderlich.` und ein `HITAN:5:6:5+4++noref+nochallenge`
Die 3076 deckt sich also mit dem letzten Post.

**Comment by roben** [comment]
Wenn ich mich nicht irre, müsste
`if (!isset($hitan[4]) or $hitan[4] == 'nochallenge')` in `Dialog.php`
`if (isset($hitan[4]) && $hitan[4] == 'nochallenge')` sein.

**Comment by nemiah** [comment]
Wenn es keine TAN-Abfrage gibt, dann kommt die Methode zurück, bei mir funktioniert es so.

**Comment by roben** [comment]
Ja, das war zum Teil ein Verständnisproblem von mir. Ich habe aber `Dialog.php` gefixt, dass es auf die Nachricht `3076: Starke Kundenauthentifizierung nicht notwendig.` schaut, wie in der Spezifikation beschrieben.
