### ISSUE TITLE
I get "net::ERR_ABORTED 500 (Internal Server Error)"

### ISSUE THREAD

**Issue by itoxic97** [nemiah/phpFinTS#350]
Hey together,

5 months ago i had no problems. Now i get "net::ERR_ABORTED 500 (Internal Server Error)". I wrote to the Postbank Customer Service, they asked more information. This error are not detailied enough. How can i show more details, what the fints server gets back?

I use the browser.php

**Comment by Philipp91** [comment]
`net::ERR_ABORTED` is JavaScript's way of outputting an HTTP 500. Given that JS in the browser talks to your server and not directly to Postbank, it seems like your server throws the error and not the Postbank server. So unless we know more about the error itself, I don't think they're at fault. For instance, this kind of error would occur if you replace `FinTs::new` with `FinTS::new` in your code.

Please check the server logs for a more detailed error message. The location of these logs depends on the server's operating system and/or the frameworks you use. Usually it's `error.log` or `access.log` on Linux. With frameworks like Symfony, you can specify where the logs go, with the default being `./var/log/`.

If you can't find the logs, a good trick is to put `throw new \RuntimeException("TestTestTest")` near the "beginning" of your PHP code (e.g. the beginning of `browser.php`), trigger the error (you should again get `net::ERR_ABORTED 500` in the browser) and then sift through various log files on your server to find the unique string `TestTestTest`.
