### ISSUE TITLE
Sammelüberweisung possible?

### ISSUE THREAD

**Issue by witschko** [nemiah/phpFinTS#354]
Hello everybody,

first of all thank you for this great library, implementing things were a charm!

I have a question regarding "Sammelüberweisungen". I was thinking that it is possible by adding multiple creditors to the SEPA Transfer but it isn't working. How would I do that?

Regars
Philipp

**Comment by ampaze** [comment]
Hi @witschko

Sammelüberweisungen is not currently supported.

If you want to try to add support, you would need to implement the "`HKCCM`" Segment and in `SendSEPATransfer.php` add a check for the amount of SEPATransfers in the XML.

Have a look at `HKCCSv1.php` for the Einzelüberweisung and at `SendSEPADirectDebit.php` for how I did it for Lastschriften.

**Comment by witschko** [comment]
Hey @ampaze 

ok...thank you very much for the explanation. I'll have a look into the `HKCCM` and see what I can do.

**Comment by carli2** [comment]
see https://github.com/nemiah/phpFinTS/pull/366

if you want to use it NOW, you can alternatively use the following fork: https://github.com/LaunixPeter/phpFinTS

**Comment by witschko** [comment]
> see #366
> 
> if you want to use it NOW, you can alternatively use the following fork: https://github.com/LaunixPeter/phpFinTS

Thank you very much...i'll have a look at it
