### ISSUE TITLE
Continuous Integration/Testing

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#36]
With other GitHub repositories, I see automated tests being run whenever I send a pull request, and sometimes even auto-formatting for the code, which could prevent [this](https://github.com/nemiah/phpFinTS/blob/0c41d10d3d3a79bd8478baca2d03be16bab4a538/lib/Fhp/FinTs.php#L111-L113). I have no idea how that can be configured and whether that costs any money to run those tests, but I'm sure some folks here may have experience with it. With a couple of upcoming PSD2 changes and banks likely changing their implementations over the next months, it would be difficult to ensure that an incremental improvement for one bank does not break things for another. So my plan is to add "integration tests" (actually just unit tests, but with a mock bank) that closely mirror the communication with actual banks (minus personal information). It would be nice if those and the existing tests could be run automatically to prevent regressions.

**Comment by roben** [comment]
I'll second that. And ensuring a common code style would prevent escapades like #40, where I just wanted to provide a uniform code style for the files I have touched. We could also add a `.php_cs` file to the repository to be used with PHP-CS-Fixer. This is the one I currently use:

```php
<?php
  
return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => true,
        'full_opening_tag' => false,
        'single_quote' => true,
        'no_whitespace_in_blank_line' => true,
        'single_blank_line_at_eof' => true
    ))
    ->setIndent("\t")
    ->setLineEnding("\n")
;
```

Anyways, GitHub Actions seem to be what we need. And something like https://github.com/marketplace/actions/php-runner, which could run phpunit and PHP-CS-Fixer after push events and for pull requests.

Formally this was done like described [here](https://stefanzweifel.io/posts/github-actions-for-php-developers/), but hopefully the new Actions are easier to use.

**Comment by nemiah** [comment]
@roben please send me a PR, I'm busy reading all the posts in the issues and making sense of them :astonished:

**Comment by roben** [comment]
It's nothing really important right now. I will look into it when the dust has settled and everything has calmed down a bit.

**Comment by nemiah** [comment]
:heavy_check_mark:

**Comment by Philipp91** [comment]
It doesn't look like this was actually done, right?

I've tried [enrolling](https://github.com/features/actions/signup/) for the public beta of GitHub actions, and have [written](https://github.com/Philipp91/fints-hbci-php/commit/ac59fcfad0d9881bdaf1fb3327c64007c94291ff) some configuration file for it, but it doesn't seem to trigger on new pull requests. The whole new GitHub Actions YAML format is quite new (a few months) and they recently changed from running pull request actions on the fork to running them on the upstream repository. I've read several bug reports about this behavior. Maybe this will work soon.

For now, Travis should be good enough. It was already configured in the repository. I will send a PR to fix the outdated config.

**Comment by nemiah** [comment]
@Philipp91 Thank you, I enabled it on the travis site…
