### ISSUE TITLE
Upgrade to psr/log >3

### ISSUE THREAD

**Issue by pud-micha** [nemiah/phpFinTS#362]
Hello,

I depend on the current version of psr/log. This project still uses the outdated version 1.x.

Thanks

**Comment by Philipp91** [comment]
This was fixed in #360, but presumably not released yet.

**Comment by Philipp91** [comment]
@nemiah Please push a new release, there are now major dependencies like Monolog v3 that are incompatible with psr/log v1.

**Comment by nemiah** [comment]
Done :relaxed:

**Comment by Philipp91** [comment]
Kann man schließen.
