### ISSUE TITLE
Eingabe Registrierungsnummer / Falsche Segmentzusammenstellung (9110)

### ISSUE THREAD

**Issue by mg-tom** [nemiah/phpFinTS#37]
Zunächst einmal vielen Dank an alle, die an diesem Projekt mitarbeiten!

Beim Versuch Umsatzdaten abzurufen, erhalte ich seit neuestem bei der GLS Bank auch die von mehreren Usern berichtete Meldung "Pflichtfeld nicht gefunden (9160); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)"

Eine Registrierungsnummer habe ich bereits beantragt und erhalten, finde aber leider keine Info, wo ich diese im Script einpflegen muss.

Kann jemand weiterhelfen?

**Comment by roben** [comment]
Hallo Tom. Die Nummer übergibst du dem FinTs-Constructor. Im Samples-Ordner finden sich auch [Beispiele](https://github.com/nemiah/phpFinTS/blob/master/Samples/statement_of_account.php) dazu.

**Comment by mg-tom** [comment]
Hallo @roben, vielen Dank, damit bin ich schon mal ein Stück weiter.

Ich erhalte nun aber die Meldung " Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); **Falsche Segmentzusammenstellung (9110)**"

**Comment by trebaxa** [comment]
Wir erhalte auch bei "getSEPAAccounts" folgendes:
Request Failed: Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Falsche Segmentzusammenstellung (9110)

Eine gültige Registernummer haben wir.

**Comment by nemiah** [comment]
@trebaxa @mg-tom Bitte vergleicht mal das HBCI-Log von Hibiscus (wenn es damit funktioniert) mit dem Log von phpFinTS, wo liegt der Unterschied?

**Comment by trebaxa** [comment]
Wir verwenden kein Hibiscus

**Comment by mg-tom** [comment]
same here

**Comment by nemiah** [comment]
Das gibts kostenlos zum runterladen: https://www.willuhn.de/products/hibiscus/

**Comment by DoctorMorris** [comment]
Den Fehler "Falsche Segmentzusammenstellung (9110)" hatte ich auch beim Abruf von Umsätzen der Sparkasse Düren. Bei mir hat es funktioniert, nachdem ich https://github.com/nemiah/phpFinTS/blob/0c41d10d3d3a79bd8478baca2d03be16bab4a538/lib/Fhp/FinTsInternal.php#L193 von array_keys() zu array_values() geändert habe.

**Comment by mg-tom** [comment]
@DoctorMorris : Das hat bei mir auch geklappt, super! Vielen Dank!

**Comment by trebaxa** [comment]
Bei uns leider nicht. Haben PHP 7.1

**Comment by roben** [comment]
Das ist seltsam. Was setzt ihr denn bei `$fints->setTANMechanism` ein? In den Dialog müssen eigentlich die IDs (also die array_keys) und nicht deren Name rein.
Bei der Postbank kann ich jedenfalls nur mit den keys arbeiten.

**Comment by DoctorMorris** [comment]
> Supported TAN mechanisms: 920

`$fints->setTANMechanism(920);`

> HIRMS: (...)+3920::Zugelassene Zwei-Schritt-Verfahren für den Benutzer.:920+0020::Der Auftrag wurde ausgeführt.'

**Comment by roben** [comment]
> Supported TAN mechanisms: 920
Guter Hinweis, da ist mir wohl bei meinem Merge Request noch was durch die Lappen gegangen. Da sollten eigentlich die Namen der Verfahren stehen. Ich kümmere mich.

**Comment by js1963** [comment]
Die Version 25d05350ad56b20ddc2c1435126561f6f91141fa ging noch mit der HASPA (Hamburger Sparkasse). Mit dem nächsten Commit kommt der Fehler Falsche Segmentzusammenstellung (9110)

Mit array_values() funcktioniert es. Ich habe es für mich jetzt so gelöst:

protected function getUsedPinTanMechanism($dialog) {
        $mechs = array_keys($dialog->getSupportedPinTanMechanisms());
		if($this->tanMechanism !== null && in_array($this->tanMechanism, $mechs)) {
			return array($this->tanMechanism);
        }
       	$mechs = array_values($dialog->getSupportedPinTanMechanisms());
       	if($this->tanMechanism !== null && in_array($this->tanMechanism, $mechs)) {
       		return array($this->tanMechanism);
       	}
       	return $mechs;
}

**Comment by roben** [comment]
Das ist mit https://github.com/nemiah/phpFinTS/pull/40 gefixt.
