### ISSUE TITLE
easy Laravel Implementation possible?

### ISSUE THREAD

**Issue by seem2810** [nemiah/phpFinTS#374]
Hi there,

I'm coming over https://github.com/abiturma/laravel-fints to https://github.com/abiturma/php-fints and from this https://github.com/mschindler83/fints-hbci-php  to finally this project.

I've got the big problem, that my bank needs a Tan to receive the statements.
However I didn't find a solution.

Maybe some other has a possible migration?
(Gerne auf Englisch oder Deutsch) 

```
use Abiturma\PhpFints\Fints;

class HBCI
{
    public static function init(Bank $bank, $username = null, $pin = null)
    {
        $host = $bank->server;
        $account_number = $bank->account_number;
        $bank_code = $bank->bank_code;

        $fints = Fints::host($host)->username($username)->bankCode($bank_code)->pin($pin);
        dump($fints);
        dump($fints->getAccounts());
        $account = false;
        foreach ($fints->getAccounts() as $ac) {
            if ($ac->account_number == $account_number) $account = $ac;
        }

        if ($account) {
           $statements = $fints->getStatementOfAccount($account, $startDate);
           dd($statements);

```

**Comment by seem2810** [comment]
Thanks. I'll try.

**Comment by seem2810** [comment]
I've implemented your repo and it worked well.
But If i choose pushTAN 2.0 my app ask for confirmation.
After I receive an error: 

```
Protocol
 \ 
UnexpectedResponseException
PHP 8.1.7
9.20.0
Got neither 3956 nor HITAN with tanProzess=2
```

In:
```
if ($this->fints->checkDecoupledSubmission($action)) {

                    echo "Bestätigt.<br />";

                }
```

This validate the request for a few minutes and everything is fine.
But I don't know how to handle this error.

**Comment by seem2810** [comment]
any ideas?

**Comment by lukas-staab** [comment]
I am not sure right now. Seems either like a bank issue or a wrong api call. Maybe @Philipp91 or @nemiah has an idea.

**Comment by Philipp91** [comment]
> This validate the request for a few minutes and everything is fine.

What do you mean by "everything is fine"? That you can receive the bank statements as expected as long as you just ignore that exception?

**Comment by Philipp91** [comment]
> Got neither 3956 nor HITAN with tanProzess=2

Please [log](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L226) the traffic and send us the last response received from the server. That's the one to which the error message refers. Please make sure it doesn't contain any sensitive information before posting it.

------

The library currently only supports those two aforementioned cases (3956 code to mean "still waiting for the user's confirmation" or HITAN segment to mean "confirmation successful"). But perhaps there are more cases. I suspect that [this](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L456) could be the issue:

> Note that we only support the (B) variant here.

Which refers to section B.4.2.2.1 of the specification. So I guess based on the response you post and the further specification sections, we'd have to implement some more functionality to support this bank's login procedure.

**Comment by seem2810** [comment]
> > This validate the request for a few minutes and everything is fine.
> 
> What do you mean by "everything is fine"? That you can receive the bank statements as expected as long as you just ignore that exception?

Yes. I can receive the statements when I ignore the error. 



> > Got neither 3956 nor HITAN with tanProzess=2
> 
> Please [log](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L226) the traffic and send us the last response received from the server. That's the one to which the error message refers. Please make sure it doesn't contain any sensitive information before posting it.
> 
> The library currently only supports those two aforementioned cases (3956 code to mean "still waiting for the user's confirmation" or HITAN segment to mean "confirmation successful"). But perhaps there are more cases. I suspect that [this](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L456) could be the issue:
> 
> > Note that we only support the (B) variant here.
> 
> Which refers to section B.4.2.2.1 of the specification. So I guess based on the response you post and the further specification sections, we'd have to implement some more functionality to support this bank's login procedure.

I'll check it this week.

**Comment by timrasche** [comment]
Same behaviour here. Receive "Got neither 3956 nor HITAN with tanProzess=2" error message on submission checkup, but if i ignore the error, it works.

**Comment by timrasche** [comment]
@Philipp91 @nemiah short information after days of working on this implementation: success in all cases except decoupled authentication request. There is a method called "isProzessvariante2" on TanMode model. This returns true in my case but throw an error on "checkDecoupledSubmission" with message "Got neither 3956 nor HITAN with tanProzess=2". I think thats not a right behaviour. Can you check this?

**Comment by Philipp91** [comment]
> Please [log](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L226) the traffic and send us the last response received from the server. That's the one to which the error message refers. Please make sure it doesn't contain any sensitive information before posting it.

**Comment by Handman280** [comment]
any new news about this issue?

**Comment by witschko** [comment]
> > Please [log](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L226) the traffic and send us the last response received from the server. That's the one to which the error message refers. Please make sure it doesn't contain any sensitive information before posting it.

Hi everybody...I've got the same issue "Got neither 3956 nor HITAN with tanProzess=2". The message for the getStatementOfAccount() returns the statements as it seems.

I have attached a log file with the request and a response where you can find "Freigabe erfolgreich" and the positions. But it nevertheless shows this error. 
[fints.log](https://github.com/nemiah/phpFinTS/files/12095873/fints.log)
