### ISSUE TITLE
Show TAN methods

### ISSUE THREAD

**Issue by lindstrom79** [nemiah/phpFinTS#375]
Hello,

I noticed when I use phpFinTS with my VR bank account I get 4 TAN methods back and show them. For example I not see SecureGo plus which I have. When I choose SecureGo it also works nevertheless.

But when I use the same bank data with my bank software MoneyMoney I see some more - even SecureGo plus. Even TAN methods which I don't have appear there. 

Will phpFinTS always show the latest TAN methods that belong to a user? If so, why is SecureGo plus missing then?

![Screenshot 2022-07-12 at 09 58 53](https://user-images.githubusercontent.com/5145247/178752578-48cd4cbc-893b-4933-a364-fb78b2186a0f.png)
![Screenshot 2022-07-13 at 07 52 06](https://user-images.githubusercontent.com/5145247/178752749-6dca7b5c-ba06-43f7-9866-1ab014183ee0.png)

**Comment by uxxman** [comment]
had the same question 👍🏻

**Comment by Philipp91** [comment]
> Will phpFinTS always show the latest TAN methods that belong to a user?

The phpFinTS library shows all the TAN modes that are available to the user according to the server's response. More specifically:
1. The BPD contains a [list of all TAN modes](https://github.com/nemiah/phpFinTS/blob/5f6b4d3bf6916c0b5f90d70b1a98470cfe6a2a26/lib/Fhp/Protocol/BPD.php#L60) that the bank supports, independent of the user. This _should_ contain the "missing ones" -- you can verify this by doing `print_r($fints->getBpd()->allTanModes)`.
1. From that list, the library [only returns the subset available to the user](https://github.com/nemiah/phpFinTS/blob/5f6b4d3bf6916c0b5f90d70b1a98470cfe6a2a26/lib/Fhp/FinTs.php#L533) according to the user data. You can inspect that subset with `print_r($fints->allowedTanModes)`.

> If so, why is SecureGo plus missing then?

My guess is that it's not on the allowlist from that second step above. So the new question is: Why does MoneyMoney show it?

* It's possible that MoneyMoney just blindly shows all of the TAN modes from the BPD and disregards the user-specific data. (This theory is especially plausible if MoneyMoney prompts you to select the TAN mode _before_ you've provided your username and password to log in.)
* It's also possible that the bank server delivers a different set of allowable TAN modes to MoneyMoney (perhaps they recognize its client ID or perhaps MoneyMoney uses an older/newer protocol version that makes the server react differently). If you want to debug deeper into this, you need to log the FinTS traffic with both applications (use `$fints->setLogger()` for phpFinTS) and search for [`3920`](https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php), which is the serialized identifier of the data element that contains the allowed TAN methods.

**Comment by Philipp91** [comment]
Did you figure out the reason here?
