### ISSUE TITLE
ungebuchte Umsätze auflisten

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#377]
Hallo zusammen,

seit ich auf die neuere Version aktualisiert habe, bekomme ich die ungebuchten Umsätze nicht mehr aufgelistet.
Wie komme ich inzwischen da ran?

Liebe Grüße
Nena

**Comment by nemiah** [comment]
Äääh, ich glaube nicht, ich mache halt

 $getStatement = \Fhp\Action\GetStatementOfAccount::create($oneAccount, $from, $to);
 $fints->execute($getStatement);

:blush:

**Comment by Philipp91** [comment]
Laut https://github.com/nemiah/phpFinTS/search?q=nichtGebuchteUmsaetze wird das Feld `HIKAZv4::$nichtGebuchteUmsaetze` nirgendwo gelesen. Hast du eigenen Code, der es liest, aber der Wert ist jetzt `null`? Oder was meinst du mit "nicht mehr aufgelistet"?

**Comment by nemiah** [comment]
Früher hat es funktioniert, die ungebuchten Umsätze kamen einfach mit und ich habe sie mit $transaction->getBooked() rasugefiltert oder drin gelassen. Je nachdem, wie ich es gebraucht habe. Habs mal wieder eingebaut: #378

**Comment by Philipp91** [comment]
Kann man schließen.
