### ISSUE TITLE
getSEPAAccounts Fehler 9050 / 9110

### ISSUE THREAD

**Issue by trebaxa** [nemiah/phpFinTS#38]
Beim Aufruf von "getSEPAAccounts" erhalten wir folgende Meldung:

**Request Failed: Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Falsche Segmentzusammenstellung (9110)**

Eine gültige Registernummer liegt vor. Woran könnte es liegen?

**Comment by nemiah** [comment]
duplicate #37
