### ISSUE TITLE
Multiple transfers without "Sammelüberweisung"

### ISSUE THREAD

**Issue by witschko** [nemiah/phpFinTS#380]
Hi everyone,

does anybody if is it possible to make multiple transfers (or direct debits) within one transaction without using Sammelüberweisung/-lastschrift? According to a client it should be possible because they are currently using the VR-NetWorld software and can just check a box to determine if the transfers should be send within a "Sammel" container or as multiple transfers with using just one TAN.

Has anybody ever done something like this?

Thanks and Regards

**Comment by Heart1010** [comment]
Batch booking `<BtchBookg>` is the keyword here which should be set in the xml file (for "Sammelüberweisungen" / "Sammellastschriften")

**Comment by witschko** [comment]
Awesome, thanks...i'll have a look into it.
