### ISSUE TITLE
FinTS errors: 9050 (global): Teilweise fehlerhaft. 9120 (wrt seg 1): Nachrichtennummer nicht erwartet.

### ISSUE THREAD

**Issue by fafiebig** [nemiah/phpFinTS#383]
Ahoi,

habe jetzt bei page reload das Problem das die fints Instance noch vorhanden ist (wird per persist() data reinitialisiert) aber dann nur noch mit folgendem Fehler bei execute() reagiert:

FinTS errors: 9050 (global): Teilweise fehlerhaft. 9120 (wrt seg 1): Nachrichtennummer nicht erwartet.

Ich vermute einen fehlerhaften persistierten Stand, kann das aber nicht eingrenzen. 
Bei erstem Auslösen wird ordentlich responded, beim reload Fehler.

Gibts es eine Möglichkeit das zu prüfen bzw zu resetten?

Btw bei drittem auslösen folgt ähnlicher Fehler:

FinTS errors: 9050 (global): Teilweise fehlerhaft. 9800 (wrt seg 1): Dialog ungueltig/unbekannt.

Mein Fluss ist wie folgt:
login() if needed > persist() if login > submitTan() if needed > execute()

theoretisch müsste die Instance immer den Stand nach login() haben.

**Comment by fafiebig** [comment]
Btw beim drittem auslösen folgt ähnlicher Fehler:

FinTS errors: 9050 (global): Teilweise fehlerhaft. 9800 (wrt seg 1): Dialog ungueltig/unbekannt.

**Comment by Philipp91** [comment]
> login() if needed > persist() if login > submitTan() if needed > execute()

Ich nehme an, am Ende ist noch ein persist()?

> login() if needed

Wie ist das gemeint? Werden da u.U. uralte Instanzen weiter verwendet? Nach ein paar Minuten Inaktivität verwirft der Bank-Server die Session vermutlich und man muss [`forgetDialog()`](https://github.com/nemiah/phpFinTS/blob/c1ef5dd303203234759b3761f7e378f5488de70a/lib/Fhp/FinTs.php#L509) aufrufen. Oder man kann das ganze vermeiden, indem man nach jedem execute() erst `close()` und _dann_ `persist()` aufruft.

> nur noch mit folgendem Fehler bei execute() reagiert

Ist das dann der Fall, wenn direkt vorher login() ausgeführt wurde? Oder mit einer älteren Session?

**Comment by timrasche** [comment]
Hier das exakt gleiche Problem. Ich erhalte das bei pushTAN 2.0 Verfahren und der asynchronen Bestätigung auf externen Geräten. Kann das Problem aber nur bei der Volksbank erzeugen, Sparkasse z.B. funktioniert wenn man den Fehler "Got neither 3956 nor HITAN with tanProzess=2" ignoriert.

**Comment by timrasche** [comment]
Okay ich konnte das Problem weiter eingrenzen. Generell gilt ja das vor jeder Aktion ein "login" erfolgen muss, das klappt z.B. bei der Sparkasse hervorragend. Bei der Volksbank allerdings verwirft er scheinbar den Context, wenn "login" aufgerufen wird. Ohne vorherigen "login" funktionieren alle anderen Banken dann nicht. Ziemlich strange, vor allem scheint das Problem aber relativ neu zu sein da letzte Woche auch Volksbank das alles noch akzeptiert hat.

**Comment by witschko** [comment]
Hallo zusammen,

gibt es hier neue Erkenntnisse? Bei mir tritt das gleiche Problem auf bei einer decoupled TAN Abfrage. Hier ist der Ablauf folgendedermaßen:

- Browseraufruf -> persitierter Zustand wird geladen
- `checkDecoupledSubmission()` wird aufgerufen, liefert false zurück
- nächster Browseraufruf -> persitierter Zustand (der gleiche) wird geladen

Muss vor dem zweiten Aufruf zuerst neu `persist()` aufgerufen werden?

**Comment by Philipp91** [comment]
Ja. Mit anderen Worten, derselbe persistierte Zustand sollte nie zwei Mal geladen werden (außer wenn beim ersten Mal absolut gar nichts damit gemacht wurde, also insbesondere keine Nachrichten zum Server gesendet wurden).

**Comment by witschko** [comment]
Ok, danke...es hat funktioniert.

**Comment by witschko** [comment]
Ich persistiere sowohl Action als auch Instanz.
