### ISSUE TITLE
Composer Autoload-Issue

### ISSUE THREAD

**Issue by seem2810** [nemiah/phpFinTS#389]
Hello Guys,

`Class Fhp\Model\FlickerTan\TanRequestChallengeFlickerTest located in ./vendor/nemiah/php-fints/lib/Tests/Fhp/Model/FlickerTan/TanRequestChallengeFlickerTest.php does not comply with psr-0 autoloading standard. Skipping.`

How can I solve this?

**Comment by lukas-staab** [comment]
It is already solved on the master branch. Are you using the latest release or dev-master in your composer.json?

Nonetheless: it is not a breaking issue. As long as you don't want to run the tests you can ignore the warning.

**Comment by seem2810** [comment]
`"nemiah/php-fints": "^3.3",`

not dev-master :-)
I'll wait, thanks for the fast feedback
