### ISSUE TITLE
Dokumentation hinzufügen

### ISSUE THREAD

**Issue by dsentker** [nemiah/phpFinTS#39]
Ich bin auf diesen Fork aufmerksam geworden, weil seit einigen Tagen/Wochen die "altbekannte" FinTs-Lösung nicht mehr wie gewünscht funktioniert. Ich habe hier herausgelesen, dass mit diesem Fork bereits eine Aktualisierung erarbeitet wird.
Gibt es zu dem bisherigen Entwicklungsstand (TAN-Verfahren) bereits eine Dokumentation?

**Comment by nemiah** [comment]
Hallo,

tut mir leid, aber ich verstehe die Frage nicht :cry: 

Liebe Grüße
Nena

**Comment by svensq** [comment]
Hallo Nena,

ich vermute dsentker fragt sich, ähnlich wie ich auch, wie die TAN-Abwicklung umgesetzt werden kann.
Ich habe in den Samples die Tan-Abfragen gesehen, frage mich aber von wo die tan.txt kommt. Muss dazu ein zusätzlicher Service angebunden werden oder wird diese automatisch bei einem Tan-Request erstellt? Hierzu habe ich keine Information gefunden.
Vielen Dank für deine Hilfe.

Viele Grüße
Sven

**Comment by nemiah** [comment]
In die tan.txt muss die TAN eingetragen werden. Die Datei sollte leer angelegt bzw. beim Ausführen geleert werden. Wenn die Datei Inhalt hat, wird dieser als TAN verwendet. So funktioniert es mit einer Closure.

Wenn die Sitzung unterbrochen wird, dann ist ein Beispiel in der statement_of_account.php
