### ISSUE TITLE
finanzen.net Zero (Baader) funktioniert nicht

### ISSUE THREAD

**Issue by NabilHanna** [nemiah/phpFinTS#391]
Hallo zusammen,

ich versuche momentan verzweifelt, die Umsätze von finanzen.net Zero (Baader) abzurufen und erhalte folgende Fehlermeldung:
`[07-Sep-2022 17:28:17 Europe/Berlin] PHP Fatal error:  Uncaught Fhp\Protocol\UnexpectedResponseException: The server does not support any HISPAS versions implemented in this library in /www/htdocs/w017b2e1/fima24.de/vendor/nemiah/php-fints/lib/Fhp/Protocol/BPD.php:119
Stack trace:
#0 /vendor/nemiah/php-fints/lib/Fhp/Action/GetSEPAAccounts.php(53): Fhp\Protocol\BPD->requireLatestSupportedParameters('HISPAS')
#1 /vendor/nemiah/php-fints/lib/Fhp/BaseAction.php(199): Fhp\Action\GetSEPAAccounts->createRequest(Object(Fhp\Protocol\BPD), Object(Fhp\Protocol\UPD))
#2 /vendor/nemiah/php-fints/lib/Fhp/PaginateableAction.php(104): Fhp\BaseAction->getNextRequest(Object(Fhp\Protocol\BPD), Object(Fhp\Protocol\UPD))
#3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(286): Fhp\PaginateableAction->getNextRequest(Object(Fhp\Protocol\BPD), Object(Fhp\Protocol\UPD))
#4 Fhp\FinTs->execute(Object(Fhp\Action\GetSEPAAccounts in /vendor/nemiah/php-fints/lib/Fhp/Protocol/BPD.php on line 119
`

Anbei noch der Log:
`[D] > HNHBK:1:3+000000000145+300+0+1'HKIDN:2:2+280:70033100+9999999999+0+0'HKVVB:3:3+0+0+0+PRIVATE__________________+1.0'HKTAN:4:6+4+HKIDN'HNHBS:5:1+1'
[D] < HNHBK:1:3+000000000995+300+BAADERAG001ULWPLZmNi0K8d_QlXrg+1+BAADERAG001ULWPLZmNi0K8d_QlXrg:1'HIRMG:2:2+0010::Nachricht entgegengenommen.'HIBPA:3:3:3+0+280:70033100+Baader Bank AG+1+1:2+300++0+300'HISPAS:4:3:3+1+1+0+N:J:N:N:0:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIPAES:5:1:3+1+1+0'HISALS:6:6:3+1+1+0'HISALS:7:7:3+1+1+0'HIKAZS:8:6:3+1+1+0+3650:N:N'HIKAZS:9:7:3+1+1+0+3650:N:N'HICAZS:10:1:3+1+1+0+3650:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:camt.052.001.02'HICCSS:11:1:3+1+1+0'HIWPDS:12:6:3+1+1+0+N:N:N'HIPINS:13:1:3+1+1+0+6:64::::HKSPA:J:HKPAE:J:HKSAL:J:HKKAZ:J:HKCAZ:J:HKCCS:J:HKWPD:N'HITANS:14:6:3+1+1+0+N:N:0:930:2:smsTAN:mobileTAN::smsTAN-Verfahrens:6:1:mobileTAN:999:N:1:N:0:2:N:J:00:0:N'HNHBS:15:1+1'
[D] > HNHBK:1:3+000000000113+300+BAADERAG001ULWPLZmNi0K8d_QlXrg+2'HKEND:2:1+BAADERAG001ULWPLZmNi0K8d_QlXrg'HNHBS:3:1+2'
[D] < HNHBK:1:3+000000000169+300+BAADERAG001ULWPLZmNi0K8d_QlXrg+2+BAADERAG001ULWPLZmNi0K8d_QlXrg:2'HIRMG:2:2+0100::Dialog beendet'HIRMS:3:2:2+0100::Dialog beendet'HNHBS:4:1+2'
[D] > HNHBK:1:3+000000000385+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20220907:152815+2:2:13:@8@00000000:5:1+280:70033100:PRIVATE:V:0:0+0'HNVSD:999:1+@225@HNSHK:2:4+PIN:1+999+1298844+1+1+1::0+1+1:20220907:152815+1:999:1+6:10:19+280:70033100:PRIVATE:S:0:0'HKIDN:3:2+280:70033100+PRIVATE+0+1'HKVVB:4:3+0+0+0+PRIVATE__________________+1.0'HKSYN:5:3+0'HNSHA:6:2+1298844++PRIVATE_____''HNHBS:7:1+1'
[D] < HNHBK:1:3+000000001308+300+BAADERAG701ExaDiL3W8EGh0dbbPiL+1+BAADERAG701ExaDiL3W8EGh0dbbPiL:1'HNVSK:998:3+PIN:1+998+1+2+1:20220907:172816+2:2:13:@8@        :5:1+280:70033100:70033100:V:0:0+0'HNVSD:999:1+@1086@HIRMG:2:2+3060::Teilweise liegen Warnungen vor.+0010::Nachricht entgegengenommen.'HIRMS:3:2:4+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer:930'HIRMS:4:2:5+0020::Auftrag ausgeführt.'HIBPA:5:3:4+0+280:70033100+Baader Bank AG+1+1:2+300++0+300'HISPAS:6:3:4+1+1+0+N:J:N:N:0:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIPAES:7:1:4+1+1+0'HISALS:8:6:4+1+1+0'HISALS:9:7:4+1+1+0'HIKAZS:10:6:4+1+1+0+3650:N:N'HIKAZS:11:7:4+1+1+0+3650:N:N'HICAZS:12:1:4+1+1+0+3650:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:camt.052.001.02'HICCSS:13:1:4+1+1+0'HIWPDS:14:6:4+1+1+0+N:N:N'HIPINS:15:1:4+1+1+0+6:64::::HKSPA:J:HKPAE:J:HKSAL:J:HKKAZ:J:HKCAZ:J:HKCCS:J:HKWPD:N'HITANS:16:6:4+1+1+0+N:N:0:930:2:smsTAN:mobileTAN::smsTAN-Verfahrens:6:1:mobileTAN:999:N:1:N:0:2:N:J:00:0:N'HISYN:17:4:5+SI0YKKWwx0iomRfWFlg7Xw''HNHBS:18:1+1'
[D] > HNHBK:1:3+000000000404+300+BAADERAG701ExaDiL3W8EGh0dbbPiL+2'HNVSK:998:3+PIN:1+998+1+1::SI0YKKWwx0iomRfWFlg7Xw+1:20220907:152816+2:2:13:@8@00000000:5:1+280:70033100:PRIVATE:V:0:0+0'HNVSD:999:1+@194@HNSHK:2:4+PIN:1+999+2492263+1+1+1::SI0YKKWwx0iomRfWFlg7Xw+1+1:20220907:152816+1:999:1+6:10:19+280:70033100:PRIVATE:S:0:0'HKEND:3:1+BAADERAG701ExaDiL3W8EGh0dbbPiL'HNSHA:4:2+2492263++PRIVATE_____''HNHBS:5:1+2'
[D] < HNHBK:1:3+000000000283+300+BAADERAG701ExaDiL3W8EGh0dbbPiL+2+BAADERAG701ExaDiL3W8EGh0dbbPiL:2'HNVSK:998:3+PIN:1+998+1+2+1:20220907:172816+2:2:13:@8@        :5:1+280:70033100:70033100:V:0:0+0'HNVSD:999:1+@64@HIRMG:2:2+0100::Dialog beendet'HIRMS:3:2:3+0100::Dialog beendet''HNHBS:4:1+2'
[D] > HNHBK:1:3+000000000454+300+0+1'HNVSK:998:3+PIN:2+998+1+1::SI0YKKWwx0iomRfWFlg7Xw+1:20220907:152816+2:2:13:@8@00000000:5:1+280:70033100:PRIVATE:V:0:0+0'HNVSD:999:1+@273@HNSHK:2:4+PIN:2+930+9771416+1+1+1::SI0YKKWwx0iomRfWFlg7Xw+1+1:20220907:152816+1:999:1+6:10:19+280:70033100:PRIVATE:S:0:0'HKIDN:3:2+280:70033100+PRIVATE+SI0YKKWwx0iomRfWFlg7Xw+1'HKVVB:4:3+0+0+0+PRIVATE__________________+1.0'HKTAN:5:6+4+HKIDN'HNSHA:6:2+9771416++PRIVATE_____''HNHBS:7:1+1'
[D] < HNHBK:1:3+000000003661+300+BAADERAG161TelK_GtnfE-OMi3FQ3c+1+BAADERAG161TelK_GtnfE-OMi3FQ3c:1'HNVSK:998:3+PIN:1+998+1+2+1:20220907:172817+2:2:13:@8@        :5:1+280:70033100:70033100:V:0:0+0'HNVSD:999:1+@3439@HIRMG:2:2+3060::Teilweise liegen Warnungen vor.+0010::Nachricht entgegengenommen.'HIRMS:3:2:4+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer:930'HIRMS:4:2:5+3076::Keine starke Authentifizierung erforderlich.'HIBPA:5:3:4+0+280:70033100+Baader Bank AG+1+1:2+300++0+300'HISPAS:6:3:4+1+1+0+N:J:N:N:0:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.002.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.001.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.002.02:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.008.003.02'HIPAES:7:1:4+1+1+0'HISALS:8:6:4+1+1+0'HISALS:9:7:4+1+1+0'HIKAZS:10:6:4+1+1+0+3650:N:N'HIKAZS:11:7:4+1+1+0+3650:N:N'HICAZS:12:1:4+1+1+0+3650:N:N:urn?:iso?:std?:iso?:20022?:tech?:xsd?:camt.052.001.02'HICCSS:13:1:4+1+1+0'HIWPDS:14:6:4+1+1+0+N:N:N'HIPINS:15:1:4+1+1+0+6:64::::HKSPA:J:HKPAE:J:HKSAL:J:HKKAZ:J:HKCAZ:J:HKCCS:J:HKWPD:N'HITANS:16:6:4+1+1+0+N:N:0:930:2:smsTAN:mobileTAN::smsTAN-Verfahrens:6:1:mobileTAN:999:N:1:N:0:2:N:J:00:0:N'HIUPA:17:4:4+PRIVATE+0+0'HIUPD:18:6:4+PRIVATE009::280:70033100+DE4870033100PRIVATE009+PRIVATE+1+EUR+HANNA, NABIL        ++Kontokorrentkonto++HKSAL:1+HKKAZ:1+HKCAZ:1+HKSPA:1++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++{ "BIC"?: "BDWBDEMMXXX" }'HIUPD:19:6:4+PRIVATE001::280:70033100++PRIVATE+30+EUR+HANNA, NABIL        ++Kundenbestandsdepot++HKWPD:1+HKSPA:1++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++{ "BIC"?: "BDWBDEMMXXX" }'HITAN:20:6:5+4++noref+nochallenge''HNHBS:21:1+1'
`

Jemand eine Idee, woran das liegt?

**Comment by Philipp91** [comment]
phpFinTS unterstützt nur die Segmentversionen 1 und 2, die Bank sendet aber nur Version 3.

Wir sollten vermutlich Version 3 einfach implemtentieren. Die Spezifikation ist [hier](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf) Sektion C.10.1.5 auf PDF-Seite 380. Zum Implementieren einfach [hier](https://github.com/nemiah/phpFinTS/tree/master/lib/Fhp/Segment/SPA) alle Dateien mit V2 klonen und zu V3 umbenennen, auch im Dateiinhalt entsprechend anpassen und die Links zur Spezifikation aktualisieren. HKSPA und HISPA scheinen unverändert, könnten also direkt mit `extends HKSPAv2` bzw. `extends HISPAv2` von der Vorversion erben. HISPASv3 muss auf die neue Parameter-Version verweisen, und dort kommt dann das neue Feld "Anzahl reservierter Verwendungszweckstellen" dazu.

Das Feld klingt für mich nicht so, als müssten wir es irgendwie beachten. Einfach hinzufügen reicht.

Und zum Schluss noch [hier ergänzen](https://github.com/nemiah/phpFinTS/blob/a6fece0979cf18a399d8148363f832214a6d9e0f/lib/Fhp/Action/GetSEPAAccounts.php#L58).

**Comment by Philipp91** [comment]
Nur falls jemand diesen Thread mal findet, wenn wir zu FinTS 4.0 oder neuer wechseln:
In der neusten Spezifikation ist der Abschnitt dann ganz weg ([PDF-Seite 403](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv4/FinTS_4.1_Messages_Geschaeftsvorfaelle_Rel.2015_FV.pdf)). In der Version 4.0 stand noch:

```
Für die Übermittlung der SEPA-Kontoinformationen kann entweder eine mit einer
Folgeversion von FinTS V4.0 noch zu spezifizierende UPD oder der im Folgenden
beschriebene Geschäftsvorfall „SEPA-Kontoverbindung anfordern“ verwendet wer-
den. Die im Text enthaltenen Aussagen zur Verwendung der UPD gelten ab dem
Zeitpunkt, ab dem eine neue UPD-Version im Rahmen einer Erweiterung des FinTS
V4.0-Protokolls zur Verfügung steht.

Mit Hilfe des Geschäftsvorfalls „SEPA-Kontoverbindung anfordern“ wird einerseits
über die BPD dem Kundenprodukt/Kunden mitgeteilt, dass das Institut SEPA-
Geschäftsvorfälle generell unterstützt, andererseits kann mit diesem Geschäftsvor-
fall das Kundenprodukt die für den Kunden zugelassenen Konten mit IBAN/BIC an-
fordern. Die IBAN bzw. der BIC können entweder für bestimmte Konten oder – ab-
hängig vom BPD-Parameter „Einzelkontenabruf erlaubt“ – für alle Konten des Kun-
den angefordert werden. Alternativ kann die Übermittlung der zugelassenen Kon-
ten auch mittels UPD erfolgen.

Wenn das Kundenprodukt in der Dialoginitialisierungsantwort eine
neue UPD (im Aufbau der bestehenden FinTS V4.0-Version) erhält,
muss das Kundenprodukt durch Abgleich mit den lokal gespeicher-
ten Informationen ermitteln, ob zusätzlich SEPA-Informationen ab-
gerufen werden müssen, um die aktuellen Informationen über
IBAN/BIC zu erhalten. Der Aufbau der bestehenden UPD selbst
wurde für die Integration vom SEPA in FinTS nicht geändert.
Erhält ein Kundenprodukt nach entsprechender Erweiterung des
FinTS V4.0-Protokolls im Rahmen der Dialoginitialsierung eine UPD
in neuem Aufbau, so kann sie die zugelassenen Konten direkt dort
entnehmen und muss keine zusätzlichen SEPA-Informationen abru-
fen.
```

Sprich die ganzen SPA-Segmente werden verschwinden und die UPD sollen dann genügen.

**Comment by NabilHanna** [comment]
Danke, das hat so geklappt.

**Comment by Philipp91** [comment]
Super. Kannst du einen PR schicken?

**Comment by obccgn** [comment]
Gibt es hierzu ein Codebeispiel? Leider ist der Kommentar oben ein böhmisches Dorf für mich :(

**Comment by NabilHanna** [comment]
Es tut mir leid, ich bekomme das mit dem git nicht hin, ein patch zu erstellen.
Ich kann gerne meine erstellten Dateien per E-Mail teilen.

**Comment by obccgn** [comment]
Das wäre super. Vielen Dank. Kannst du die Dateien irgendwo hochladen und freigeben?

**Comment by obccgn** [comment]
Vielen Dank. Ich habe die Datei entsprechend angepasst, aber komme leider nicht weiter.

`The server does not support any HISPAS versions implemented in this library `
