### ISSUE TITLE
Hat jemand eine VB.NET oder C#-Version von phpFinTS?

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [nemiah/phpFinTS#392]
Hallo!

Es gibt das folgende C#-Projekt: https://github.com/iamtorsten/libfintx

Allerdings funktioniert das mit der Postbank nicht, und meine Issues werden nicht beantwortet.
Das ganze Projekt scheint ziemlich verlassen zu sein.

Ich würde deshalb gerne fragen, ob jemand eine VB.NET oder C#-Version von phpFinTS geschrieben hat, bzw. für sich selbst verwaltet.
Wenn nicht, dann würde ich es in selbst machen, aber ich wollte gerne vorher fragen, ob sich jemand die Mühe vielleicht schon gemacht hat.

Danke!

**Comment by Philipp91** [comment]
Von phpFinTS an sich wohl nicht. Es macht aber auch wenig Sinn, das zu portieren, wo es doch eine genaue, sprachunabhängige Spezifikation gibt.

Im .NET-Bereich gibt es [das kommerzielle Subsembly](https://subsembly.com/fints-api.html) sowie [libfintx](https://github.com/iamtorsten/libfintx).
