### ISSUE TITLE
Postbank

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [nemiah/phpFinTS#393]
Hallo!
Entschuldigt bitte, dass ich ein Issue bei Euch melde.
Es ist kein Issue bei Euch, sondern ich möchte per C# mein Onlinebanking bedienen.
Dafür benutze ich es das folgende Projekt:
https://github.com/iamtorsten/libfintx

Ich verwende die Postbank und bekomme den folgenden Fehler:
HNHBK:1:3+000000000137+300+0+1+0:1'HIRMG:2:2+9050::Teilweise fehlerhaft.'HIRMS:3:2:998+9130:8,2:Inhalt syntaktisch ungültig.'HNHBS:4:1+1'

Ich habe den Fehler [hier](https://github.com/iamtorsten/libfintx/issues/105) gemeldet.

Allerdings antwortet da Niemand, ich vermute, es benutzt einfach keiner die Postbank.

Bei Googeln des Fehlers bin ich auf das phpFinTS-Projekt gestoßen und gesehen, dass ihr den Fehler auch hattet, und dass er mit einem besonderen Workaround behoben wurde:

https://github.com/nemiah/phpFinTS/issues/111

Ich verstehe leider zu wenig php, und ich konnte auch nicht nachvollziehen, wo / was ihr geändert habt.

Wenn mir jemand sagen könnte, was man ändern muss oder erklären könnte, was im phpFinTS-Projekt geändert wurde, damit es geht, würde ich mich sehr freuen.

Vielen Dank!

**Comment by Philipp91** [comment]
Siehe [dort](https://github.com/iamtorsten/libfintx/issues/105#issuecomment-1250378741). Könnte an falscher BLZ liegen.

**Comment by NoteToSelfFindGoodNickname** [comment]
Ja, das war das Problem. Dankeschön!
