### ISSUE TITLE
Postbank: Name des TAN-Medium erforderlich

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [nemiah/phpFinTS#394]
Hallo!

Ich habe ein Problem mit [libfintx](https://github.com/iamtorsten/libfintx) (einer C#-Implementierung), aber dieses Projekt ist ziemlich verlassen. 
Könnte ich bitte deshalb bei Euch fragen? Ich habe gesehen, dass ihr auch mit diesem Problem zu tun hattet (möglicherweise https://github.com/nemiah/phpFinTS/pull/116/commits/4ef83436f2ef7027822eaa64c515f3c8bb510345).

Ich versuche, meinen Kontostand bei der Postbank abzufragen und bekomme diese Fehlermeldung:

3076: Keine starke Authentifizierung erforderlich., 9050: Teilweise fehlerhaft., 0020: Information fehlerfrei entgegengenommen., 1040: BPD nicht mehr aktuell. Aktuelle Version folgt., 3920: Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:920:930, 1050: UPD nicht mehr aktuell. Aktuelle Version folgt., 9210: Name des TAN-Medium erforderlich.

Kann mir jemand sagen, was ihr geändert habt, damit es geht?
Ich bin leider nicht gut in php-Lesen.

Möglicherweise handelt es sich um das selbe Problem, das ihr [hier](https://github.com/nemiah/phpFinTS/issues/111) behoben hattet.

Danke!

**Comment by Philipp91** [comment]
> 9210: Name des TAN-Medium erforderlich.

Du musst das Äquivalent von [`selectTanMode()`](https://github.com/nemiah/phpFinTS/blob/a6fece0979cf18a399d8148363f832214a6d9e0f/lib/Fhp/FinTs.php#L583) mit einem `TanMedium` aufrufen.

https://github.com/iamtorsten/libfintx/blob/de3cb976d96532c7087d5190d3da0ccbf4dcde70/src/libfintx.Sample.Ui/MainForm.cs#L189

**Comment by NoteToSelfFindGoodNickname** [comment]
Das weiß ich.
Der Aufruf kehrt aber sofort zurück, da stimmt etwas nicht.

Ich konnte es bis hierhin verfolgen, aber das ist so kompliziert geschrieben, dass ich nicht nachverfolgen kann, was genau nicht stimmt:

        public TANDialog(Func<TANDialog, Task<string>> waitForTanAsync, int flickerWidth = 320, int flickerHeight = 120)
            : this(waitForTanAsync)
        {
            RenderFlickerCodeAsGif = true;
            FlickerWidth = flickerWidth;
            FlickerHeight = flickerHeight;
        }

        /// <summary>
        /// Render TANCode (Flicker/Matrix) in WinForms.
        /// </summary>
        /// <param name="waitForTanAsync"></param>
        /// <param name="dialogResult"></param>
        /// <param name="pictureBox"></param>
        public TANDialog(Func<TANDialog, Task<string>> waitForTanAsync, PictureBox pictureBox)
            : this(waitForTanAsync)
        {
            PictureBox = pictureBox;
        }

**Comment by NoteToSelfFindGoodNickname** [comment]
Folgendes passiert:

Das hier wird aufgerufen...

        private async Task<bool> InitTANMedium(FinTsClient client)
        {
            // TAN-Medium-Name
            var accounts = await client.Accounts(CreateTANDialog(client));

Es kehrt nach 1 Sekunde zurück.
"accounts.IsSuccess" ist True.

In den messages steht: "{3076: Keine starke Authentifizierung erforderlich., 9050: Teilweise fehlerhaft., 0020: Information fehlerfrei entgegengenommen., 1040: BPD nicht mehr aktuell. Aktuelle Version folgt., 3920: Meldung unterstützter Ein- und Zwei-Schritt-Verfahren:920:930, 1050: UPD nicht mehr aktuell. Aktuelle Version folgt., 9210: Name des TAN-Medium erforderlich.}"

**Comment by Philipp91** [comment]
Oh, `InitTANMedium()` klang vielversprechend, ruft aber die _Accounts_ ab??

Ich glaube [`RequestTANMediumName()`](https://github.com/iamtorsten/libfintx/blob/de3cb976d96532c7087d5190d3da0ccbf4dcde70/src/libfintx.Sample.Ui/MainForm.cs#L491) geht in die richtige Richtung. Dann ist aber die Frage, wo man das Ergebnis hin tut. Ich glaube, man muss es in `client.HITAB` schreiben, so wie [hier](https://github.com/iamtorsten/libfintx/blob/de3cb976d96532c7087d5190d3da0ccbf4dcde70/src/libfintx.Sample.Ui/MainForm.cs#L655).

Ich denke, man kann auch `client.HITAB` setzen ohne die Accounts vorher abzurufen. Mag sein, dass manche Banken einen Accounts-Abruf auch ohne TAN-Medium erlauben, aber aus der obigen Fehlermeldung entnehme ich, dass die Postbank das nicht erlaubt. (Und nur weil man ein TAN-Medium verlangt, heißt das noch nicht, dass man es auch benutzen und mühsam eine TAN eingeben muss.) Und spätestens für den Abruf der Kontostände braucht es dann auf jeden Fall ein TAN-Medium.

Also ich würde rauskriegen, was valide Werte für `client.HITAB` sind, die Variable dann möglichst früh zuweisen und dann wieder den Kontoabruf probieren. Ohne `client.Accounts(...)`.

**Comment by NoteToSelfFindGoodNickname** [comment]
OMG, Danke!!!

Ich habe es jetzt so geändert:

        private async Task<bool> InitTANMedium(FinTsClient client)
        {
            // TAN-Medium-Name

            client.HITAB = txt_tan_medium.Text;
            var accounts = await client.Accounts(CreateTANDialog(client));
            if (!accounts.IsSuccess)
            {

Jetzt geht es!!!
