### ISSUE TITLE
Sammel-Basislastschrift, Sammel-Firmenlastschrift, Sammel-Ueberweisung

### ISSUE THREAD

**Issue by wienen-it-dev** [nemiah/phpFinTS#395]
Hi everyone,

when using GetStatementOfAccount->getStatement(), some of the transactions I get for these statements contain descriptions like Sammel-Basislastschrift, Sammel-Firmenlastschrift or Sammel-Ueberweisung.

These transactions I receive as aggregated data without detailed information. How to get the details like booking date, amount, description of each single transaction which are usually provided by Transaction class?

My bank already enabled detailed data transfer, but I still receive aggregated data. Couldn't find any functions in this library to retrieve the data details?

Statement functions getBookedXML(), getRawMT940() and getParsedMT940() also do not provide the data.

Appreciate any help

**Comment by nemiah** [comment]
Hi!

As far as I know you have to use "btchBookg" in the transmitted XML file to tell the bank you want all transactions separately.

**Comment by wienen-it-dev** [comment]
Hi nemiah,

vielen Dank für Deine schnelle Antwort und den Hinweis auf btchBookg.

Könntest Du uns helfen, die Stelle zu finden an der wir ansetzen müssen, um die Option btchBookg einzubauen?

Wir haben dies als object property in GetStatementOfAccount und diversen HKKAZ Segmenten hinzugefügt, was jedoch zu einem Fehler beim Request führt:
9050 (global) ... 9110 (wrt seg 3): Ungültige Auftragsnachricht: Unbekannter Aufbau. (wrt DE 8) 9010 (wrt seg 4) ...

Wären sehr dankbar für einen Hinweis der uns in die richtige Richtung bringt.

**Comment by nemiah** [comment]
Die Änderung muss in die SEPA XML-Datei, in der die Transaktionen ausgeführt werden:

`<?xml version="1.0" encoding="UTF-8"?>
<Document …>
  <CstmrDrctDbtInitn>
    <GrpHdr>
      <BtchBookg>false</BtchBookg>
      <MsgId>1666776539</MsgId>
      <CreDtTm>2022-10-26T11:28:59</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>137.04</CtrlSum>
      <InitgPty>
        <Nm>Firma</Nm>
      </InitgPty>
    </GrpHdr>…`

**Comment by Heart1010** [comment]
> Die Änderung muss in die SEPA XML-Datei, in der die Transaktionen ausgeführt werden:
> 
> `<?xml version="1.0" encoding="UTF-8"?> <Document …> <CstmrDrctDbtInitn> <GrpHdr> <BtchBookg>false</BtchBookg> <MsgId>1666776539</MsgId> <CreDtTm>2022-10-26T11:28:59</CreDtTm> <NbOfTxs>1</NbOfTxs> <CtrlSum>137.04</CtrlSum> <InitgPty> <Nm>Firma</Nm> </InitgPty> </GrpHdr>…`

...und die Bank muss es unterstützen (was bei den Genobanken z.B. erst seit kurzem der Fall ist - und hier auch teils nur, wenn es der Kunde so bei seiner Bank explizit für Konto xy hinterlegen lässt).

**Comment by wienen-it-dev** [comment]
Hi nemiah, hi Heart1010,

vielen Dank für Eure Hilfe.

Mittlerweile hat sich herausgestellt, dass wir wie von Euch beschrieben bereits bei Auftragserteilung ansetzen müssen. Dies wird bei uns bisher jedoch nicht über FinTS durchgeführt, sondern über andere Anwendungen. Beim Auftrag wurden dann zum Teil Sammelbuchungen mit btchBookg = true übermittelt.

Vielen Dank nochmals.
