### ISSUE TITLE
SEPA direct debit

### ISSUE THREAD

**Issue by timrasche** [nemiah/phpFinTS#397]
Is it possible to force the paramater "einzelbuchungGewuenscht" on Action "SendSEPADirectDebit" to reliable value of "true"?

**Comment by Philipp91** [comment]
Not today. In fact, it's either [`null` by default](https://github.com/nemiah/phpFinTS/blob/fce921b5311ee3c15eb075c25627a0584c6bee99/lib/Fhp/Segment/DME/HKDMEv1.php#L23) or [`false` in this special case](https://github.com/nemiah/phpFinTS/blob/20c099ded705e71485c99160fc06ff388512a2db/lib/Fhp/Action/SendSEPADirectDebit.php#L162-L165), which looks a little suspicious to me.

I wonder if instead of
```
if (!$useSingleDirectDebit) {
    if ($hidxes->getParameter()->einzelbuchungErlaubt) {
        $hkdxe->einzelbuchungGewuenscht = false;
    }
}
```
we perhaps want
```
if ($hidxes->getParameter()->einzelbuchungErlaubt) {
    $hkdxe->einzelbuchungGewuenscht = $useSingleDirectDebit;
}
```

**Comment by timrasche** [comment]
@Philipp91 Thanks for review, and i agree. Think need exactly this.

**Comment by Philipp91** [comment]
You can patch it in and try it out, send a PR if it worked.

**Comment by ampaze** [comment]
Just a heads up, `$useSingleDirectDebit` is only the type of request that is send to the bank (HIDME or HKDME). It has nothing to do with `einzelbuchungGewuenscht` except that `einzelbuchungGewuenscht` is only available for HKDME.

**Comment by timrasche** [comment]
hm ok, can we bring up this topic? I cant see any line of code in the examples or other parts to use this value "einzelbuchungGewuenscht" in combination with multiple sepa direct debits or transfers. Its mandatory on our software to list account statements as single lines and not in a collective way.

**Comment by ampaze** [comment]
Just setting it to `true `would potentially change functionality of software using this lib, including ours.

Options are:
* extend `SendSEPADirectDebit `and overwrite `createRequest` and change `einzelbuchungGewuenscht` as needed.
* we could take a look at the PAIN messages used and see if the information could be derived from the XML
