### ISSUE TITLE
DKB - XML schema issue after submitting a transaction

### ISSUE THREAD

**Issue by interose** [nemiah/phpFinTS#399]
Hi,
recently I get the following error message as soon as I want to execute a transaction:

`The bank does not support the XML schema urn:iso:std:iso:20022:tech:xsd:pain.001.003.03, but only urn:iso:std:iso:20022:tech:xsd:pain.001.001.03, urn:iso:std:iso:20022:tech:xsd:pain.008.001.02`

The last working transaction was at the end of the last year. Does anybody have the same problem with the DKB?

**Comment by interose** [comment]
Okay, I searched and debugged a little bit. Up to now I'm using the following lib to create the SEPA XML (https://github.com/nemiah/phpSepaXml) and within the start method (https://github.com/nemiah/phpSepaXml/blob/master/src/nemiah/phpSepaXml/SEPAFile.php#L16) only the scheme **pain.008.003.02** and **pain.001.003.03** are supported.

I found another lib (https://github.com/php-sepa-xml/php-sepa-xml) which allows the XML format to be passed.

**Comment by ampaze** [comment]
Like you said the generation of the XML is not part of FinTS. Maybe you can find out what the differences in `urn:iso:std:iso:20022:tech:xsd:pain.001.003.03` and `urn:iso:std:iso:20022:tech:xsd:pain.001.001.03`are and open an issue at [phpSepaXML](https://github.com/nemiah/phpSepaXml).

**Comment by interose** [comment]
So I tried the other lib and I also tried to simply modify the XML generation for [phpSepaXML](https://github.com/nemiah/phpSepaXml) - both are working. I try to discover what are the differences between those different schemes, but yea - it's not an issue of the phpFinTS lib and so I'm closing this issue.

**Comment by Cugar15** [comment]
Hello, facing the same issue right now with Sparkasse.

What was the resolution for this issue? 

What did you fix in: [phpSepaXML](https://github.com/nemiah/phpSepaXml)

Can you pls comment? 

Thanks,
Norbert
