### ISSUE TITLE
Keine eindeutige Identifizierung mehr möglich?

### ISSUE THREAD

**Issue by Padrio** [nemiah/phpFinTS#4]
https://github.com/nemiah/phpFinTS/blob/b9f4d0121bbd189e19f1a062cbf01d079bcfa5f0/Samples/statement_of_account.php#L46

Die Methode scheint rausgeflogen zu sein?
Gibts denn noch eine möglichkeit eine Transaktion eindeutig zu identifizieren?

**Comment by nemiah** [comment]
@Padrio das ist keine eindeutige ID für eine Transaktion, sondern ein Wert, den man bei der Lastschrift/Überweisung angeben kann. Mit diesem Wert lässt sich die Transaktion dann später wieder zuordnen. Die Methode sollte es weiterhin geben, sie ist in der Transaction-Klasse.

Liebe Grüße,
Nena

**Comment by Padrio** [comment]
Okay danke, dann muss ich doch auf die alternative Lösung zurückgreifen: Hash aus Datum / Description 1 & 2 etc..

Dankeschön! 

 

Von: Nena Furtmeier <notifications@github.com>
Antworten an: nemiah/phpFinTS <reply@reply.github.com>
Datum: Freitag, 26. Januar 2018 um 17:49
An: nemiah/phpFinTS <phpFinTS@noreply.github.com>
Cc: Pascal Krason <thepadrio@gmail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [nemiah/phpFinTS] Keine eindeutige Identifizierung mehr möglich? (#4)

 

@Padrio das ist keine eindeutige ID für eine Transaktion, sondern ein Wert, den man bei der Lastschrift/Überweisung angeben kann. Mit diesem Wert lässt sich die Transaktion dann später wieder zuordnen. Die Methode sollte es weiterhin geben, sie ist in der Transaction-Klasse.

Liebe Grüße,
Nena
