### ISSUE TITLE
SendSEPATransfer Response / Transfer-Limit

### ISSUE THREAD

**Issue by wienen-it-dev** [nemiah/phpFinTS#408]
Hallo zusammen,

drei Fragen:

1) Wie bekommt man Zugriff auf die Response-Daten beim SEPA-Transfer und welche Informationen sind dort enthalten? Etwa nach dieser Stelle aus dem Sample transfer.php:
...
```
$sendSEPATransfer = \Fhp\Action\SendSEPATransfer::create($oneAccount, $sepaDD->toXML());
$fints->execute($sendSEPATransfer);
```

2) Gibt es bei den Banken ein Limit für Auftragserteilungen (z.B. pro Stunde 1000 Überweisungen) und falls ja, kann man dieses Limit über die FinTS Schnittstelle abfragen?

3) Wenn sonstige Beschränkungen bestehen (z.B. tägliches Überweisungslimit in EUR für Bankkonto / Dispo erreicht etc.): Wird diese Information bei fehlgeschlagenen Überweisungen über FinTS übermittelt?

**Comment by ampaze** [comment]
> 1. Wie bekommt man Zugriff auf die Response-Daten beim SEPA-Transfer und welche Informationen sind dort enthalten? Etwa nach dieser Stelle aus dem Sample transfer.php:

Dort sind keine weiteren Informationen enthalten, nur die Rückmeldung dass der Auftrag angenommen wurde oder eben nicht.

> 2. Gibt es bei den Banken ein Limit für Auftragserteilungen (z.B. pro Stunde 1000 Überweisungen) und falls ja, kann man dieses Limit über die FinTS Schnittstelle abfragen?

Weiß ich nicht, die Antwort findest du aber in [der Spezifikation](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf)

> 3. Wenn sonstige Beschränkungen bestehen (z.B. tägliches Überweisungslimit in EUR für Bankkonto / Dispo erreicht etc.): Wird diese Information bei fehlgeschlagenen Überweisungen über FinTS übermittelt?

Das ist dann eine ganz normale Fehlermeldung.

**Comment by wienen-it-dev** [comment]
Hi ampaze,

vielen Dank für Deine Antworten.

Mittlerweile konnten wir eine erfolgreiche Überweisung durchführen, allerdings sind die Test-Möglichkeiten sehr eingeschränkt, insbesondere was Fehlerfälle betrifft. Daher noch Nachfragen hierzu:



> > 1. Wie bekommt man Zugriff auf die Response-Daten beim SEPA-Transfer und welche Informationen sind dort enthalten? Etwa nach dieser Stelle aus dem Sample transfer.php:
> 
> Dort sind keine weiteren Informationen enthalten, nur die Rückmeldung dass der Auftrag angenommen wurde oder eben nicht.
> 

Die execute()-Funktion liefert vermutlich keinen Rückgabewert? Wird SendSEPATransfer->processResponse() ausgeführt oder muss dies noch nach execute() ausgeführt werden?

> 
> > 3. Wenn sonstige Beschränkungen bestehen (z.B. tägliches Überweisungslimit in EUR für Bankkonto / Dispo erreicht etc.): Wird diese Information bei fehlgeschlagenen Überweisungen über FinTS übermittelt?
> 
> Das ist dann eine ganz normale Fehlermeldung.

Wird dies dann als Exception geworfen oder muss wie in Punkt 1. verarbeitet werden?

**Comment by ampaze** [comment]
So machen wir es

```php
try
{
  $fints->execute($action);
  $action->ensureDone();
} catch (TanRequiredException $e) {
// Handle Tan
} catch (ServerException $e) {
// Handle Error Case aka Inform User
}
```

**Comment by wienen-it-dev** [comment]
Hi ampaze,

vielen Dank für Deine Hilfe, dies haben wir nun bei uns implementiert.

Eine weitere Frage ist noch aufgetaucht, betrifft jedoch den Import von Kontoauszugsdaten (GetStatementOfAccount):

Gibt es bei den einzelnen Transaktionen einen Identifier, anhand dem die Buchung eindeutig erkannt werden kann?

Hintergrund: Wir importieren einzelne Buchungstage zum Teil mehrfach und müssen bereits importierte Buchungen herausfiltern.

Falls keine ID verfügbar, gibt es eine andere Möglichkeit bei den Transaktionen, z.B. über einen timestamp (ist bei bookingDate nur Datum oder auch Uhrzeit verfügbar?).

**Comment by ampaze** [comment]
Es gibt keine ID, die Reihenfolge der Buchungen ist pro Buchungsdatum aber immer gleich. D.h. pro Tag durchzählen. Dann wäre die ID = Datum + Nummer der Buchung an dem Tag.

**Comment by wienen-it-dev** [comment]
Vielen Dank für die schnelle Hilfe!
