### ISSUE TITLE
DKB funktioniert nicht (9160, 9050, 9800)

### ISSUE THREAD

**Issue by nQk2** [nemiah/phpFinTS#42]
Ich kann nicht bestätigen, dass die DKB funktioniert, obwohl sie ja bei COMPATIBILITY.md gelistet ist.
Ich erhalte folgenden Fehler:
"Request Failed: Pflichtfeld nicht gefunden (9160); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)".

Mach ich etwas falsch?

**Comment by dennobaby** [comment]
Du übergibst vermutlich nicht die RegistrierungsId/ProduktId. 

Die kannst du hier anfordern: https://www.hbci-zka.de
