### ISSUE TITLE
Fehler Sparkasse PushTAN-Verfahren FinTS

### ISSUE THREAD

**Issue by wienen-it-dev** [nemiah/phpFinTS#423]
Hallo zusammen,

ich wäre sehr dankbar für Hilfe bei diesem Fehler:

Nach Update der TAN-App (Sparkasse) funktioniert die SEPA-Überweisung nicht mehr, was bisher zuverlässig funktionierte.
Von der Sparkasse gab es folgende Auskunft: "die Geräte werden in einem Pool zusammengefasst und es gibt eine ZAS-Schnittstelle"

Fehlermeldung:

FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9955 (wrt seg
3): Auftrag nicht ausgeführt - Die Gerätebezeichnung ist unbekannt.
(MBV07390100255) FinTS warnings: 3905 (global): Es wurde keine Challenge
erzeugt. Request segments:
HKCCS:3:1+DEXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXX:XXXXXXXXX::280:XXXXXXXX+urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.001.03+@1715@
XXXXXXXXXX XXXX-XX-XXTXX:XX:XX 1 XXX.XX XXXXXXXXX XXXXXXXXXX TRF 1
XXX.XX SEPA 1999-01-01 XXXXXXXXX DEXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX SLEV
NOTPROVIDED XXX.XX XXXXXXXXXXX XXXXXX GmbH DEXXXXXXXXXXXXXXXXXXXX RE-Nr
XXXXXXXXX Knd-Nr XXXXXXXX

**Comment by wienen-it-dev** [comment]
Weitere Informationen:

Als TanMode Auswahloption liefert die Bank "pushTAN 2.0", als TanMedium "Alle Geräte" (zuvor war noch als TanMedium das verwendete Android-Gerät auswählbar).

**Comment by wienen-it-dev** [comment]
Hi mmnasir,

thank you very much for your comment.

Yes the tanMode pushTAN 2.0 (ID: 923) was selected first.

Then the bank returns as available tanMedium only "Alle Geräte" (all devices).

When selected "Alle Geräte" the error occurs.

I found this additional information, does ist help to find a solution:

Sparkassenkunden haben ebenfalls Probleme mit proficash und dem neuen Verfahren. Offenbar ruft proficash keinen HKTAB ab und hat so keine TAN-Medienbezeichnung bei den Zugängen mit Verfahren pushTAN ZAS (923). Hier müsste per HKTAB die Standardbezeichnung "Alle Geräte" abgerufen werden und ansonsten wäre alles genau wie bei Verfahren 922 zu bedienen.

**Comment by wienen-it-dev** [comment]
The error occured because of a problem with encoding of "Alle Geräte".

After fixing the encoding problem it is working again.

Thanks again mmnasir

**Comment by CasparKrog** [comment]
I have kind of the same problem. But for me it is not even showing "Alle Geräte".
If I set this manually to "Alle Geräte", the code won't work. How did u encode the "Alle Geräte" right?

**Comment by wienen-it-dev** [comment]
In my case, this worked:

```
$tanMediumNames = array_map(function (\Fhp\Model\TanMedium $tanMedium) {
    return mb_convert_encoding($tanMedium->getName(), "Windows-1252", "UTF-8");
}, $tanMedia);
```

If your application uses a different encoding, you might have to change the code.
