### ISSUE TITLE
Wie teste ich das TAN-Verfahren, wenn meine Bank mich immer ohne einloggt?

### ISSUE THREAD

**Issue by fso2404** [nemiah/phpFinTS#430]
Hallo zusammen,

ich implementiere gerade den Flow für meine App, habe jedoch ein interessantes Problem:
Die Bank lässt mich immer ohne TAN weitermachen. So kann ich den Klickpfad für die TAN-Generierung gar nicht durchspielen.
Gibt es eine Möglichkeit, den TAN-Login zu erzwingen? $fints->close() hat diesen Effekt leider nicht. Ob ich FinTs Object persistiere oder nicht, hat darauf wohl auch keinen Einfluss.

Hoffe Ihr versteht was ich meine.
Danke für eure Hilfe!

---
Hello everyone,

I am currently implementing the flow for my app, but I have an interesting problem:
The bank always lets me continue without a TAN. So I can't go through the click path for TAN generation at all.
Is there a way to force the TAN login? $fints->close() unfortunately does not have this effect. Whether I persist FinTs Object or not probably has no influence on this either.

I hope you understand what I mean.
Thanks for your help!

**Comment by flexcom** [comment]
Hi, eine Möglichkeit wäre eine Transaktionsabfrage für einen großen Zeitraum (> 90 Tage). Die meisten Banken machen dann eine starke Kundenauthentifizierung nach meiner Erfahrung.Am 02.04.2024 um 17:46 schrieb fso2404 ***@***.***>:﻿
Hallo zusammen,
ich implementiere gerade den Flow für meine App, habe jedoch ein interessantes Problem:
Die Bank lässt mich immer ohne TAN weitermachen. So kann ich den Klickpfad für die TAN-Generierung gar nicht durchspielen.
Gibt es eine Möglichkeit, den TAN-Login zu erzwingen? $fints->close() hat diesen Effekt leider nicht. Ob ich FinTs Object persistiere oder nicht, hat darauf wohl auch keinen Einfluss.
Hoffe Ihr versteht was ich meine.
Danke für eure Hilfe!

Hello everyone,
I am currently implementing the flow for my app, but I have an interesting problem:
The bank always lets me continue without a TAN. So I can't go through the click path for TAN generation at all.
Is there a way to force the TAN login? $fints->close() unfortunately does not have this effect. Whether I persist FinTs Object or not probably has no influence on this either.
I hope you understand what I mean.
Thanks for your help!

**Comment by fso2404** [comment]
Das hat funktioniert, vielen Dank für den Hinweis!
