### ISSUE TITLE
Sparkasse asks for TAN on every $fints->login()

### ISSUE THREAD

**Issue by peukerjonathan** [nemiah/phpFinTS#431]
I ran into a problem this week with to accounts from the bank "Sparkasse Pforzheim-Calw".
While everything was running smoothly until last week the bank started to ask for a TAN on every ->login() request since the beginning of this week.
(After providing a TAN I can successfully communicate with the bank and get transactions, the account balance, etc)
To make this even worse I have antoher account with the same bank which continued working fine, without having to provide a TAN on every request.

So I thought this would be an issue with the bank (some kind of misconfiguration) and gave them a call. Turns out it is not. Back in May 2023 the Sparkasse introduced a "device recognition mechanism" which enables the bank to store "trusted devices".
If you login as a non trusted device you will have to enter a TAN every time. Only "trusted devices" can login without providing a TAN.
This mechanism is allegedly already there since one year but now the Sparkasse is starting to enforce this mechanism and rolling out on all of their accounts one by one. The enforcement rollout will allegedly be finished on May 14 2024. So every Sparkasse account will be subject to this problem within the next weeks.

The phone contact unfortunately was unable to elaborate how this works on a technical level and was unable to point me to a technical documentation. However I think that some additional request parameters will have to be sent to the server during login procedure and some additional response parameters will be needed to store on client side so we can "authenticate as trusted device" upon the next call to login().

Has anyone else encountered this problem and how could I be of assitance in debugging this?

**Comment by peukerjonathan** [comment]
I could provide logs of the login and tan procedure of an affected account, but would rather not post them here in the public. So if anyone is interested please let me know.

**Comment by Philipp91** [comment]
We do store the Kundensystem-ID [here](https://github.com/nemiah/phpFinTS/blob/182f8c0d741eceda1b32263b982fa74cb699b027/lib/Fhp/FinTs.php#L160).

Do you correctly persist and restore the `FinTs` instance after every usage (not only persist once after login and then reuse the same persisted data forever)?

As you can see [here](https://github.com/nemiah/phpFinTS/blob/182f8c0d741eceda1b32263b982fa74cb699b027/lib/Fhp/FinTs.php#L800-L802), that ID can be updated anytime the server sends a response. I presume that many banks map this to a session token.

If you think there's still an issue, I'll take time to read that whole email from them.

**Comment by peukerjonathan** [comment]
Thanks for the clarification! I was indeed persisting the fints instance, but it seems that I wasn't flushing my updated record to the database consistently.
Which was working fine until now and only started to act up now when the Sparkasse implemented their changes. So I guess I just assumed this was simply not implemented yet...

My apologies - after I started to store the persiteted instance properly in my database everything started to work fine again.

Thanks for the excellent support and pointing me in the right direction. It is highly appreciated!
