### ISSUE TITLE
Add parameter to checkDecoupledSubmission to not execute action

### ISSUE THREAD

**Issue by Cugar15** [nemiah/phpFinTS#435]
The function checkDecoupledSubmission will include the result into the response based on success.

```
// The decoupled submission is complete and the action's result is included in the response.
        $action->setTanRequest(null);
        // Process the response normally, and maybe keep going for more pages.
        $this->processActionResponse($action, $response->filterByReferenceSegments($action->getRequestSegmentNumbers()));
        if ($action instanceof PaginateableAction && $action->hasMorePages()) {
            $this->execute($action);
        }


```

If polling is implemented with an ajax function, only waiting or success is expected as return value:

```
case 'poll':
        if (!isset($fints)) { 
            $action = createFinTs();  // $fints is set here and is global
        } 
 
        if ($fints->checkDecoupledSubmission($action)) {
	       echo "success";
	} else {
               echo "waiting"; 
        }
        storeFinTs($action);
        break;
```

Based on a success, the control is handed back to the main routine which is then pulling the results and executes:

```
$action->setTanRequest(null);
$fints->execute($action);

```

This will require a persisted $fints which can be read by the main routine.

However with the current implementation of checkDecoupledSubmission in case of success the results are pulled already. There will be no tanmode required anymore. From there, $fints cannot be persisted and above polling routine will fail on success.

Suggestion is to add a parameter to checkDecoupledSubmission(BaseAction $action, $execute[true|false]) to avoid pulling the results and just return fail or success.

Hope, above makes sense - happy to discuss.

**Comment by Philipp91** [comment]
I don't think it's possible. The [specification](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2020-07-10_final_version.pdf) in section B.4.2.2.1 says:

```
Mit der Kreditinstitutsantwort werden ggf. erzeugte Antwortsegmente sowie die Rückmeldungen zum Auftrag selbst
zum Kundenprodukt gesendet.
```

Meaning: Once auth succeeds, the bank sends the results in the same response. phpFinTS is only a library and not a stateful system itself, so it hands back those responses to you.

If that AJAX request isn't a convenient place in your application to deal with the response (why not though?) then you need to persist it somewhere in your database, so that your "main routine" can then pick it up from there. Though I wonder what that "main routine" is: Just another AJAX request or HTTP request? Or some kind of daemon job on your server? Or a cronjob?

**Comment by Cugar15** [comment]
Correct, the bank sends response. 

The real problem is, that after executing the following marked statements in checkDecoupledSubmission:

```
        $action->setTanRequest(null);         <----
        // Process the response normally, and maybe keep going for more pages.
        $this->processActionResponse($action, $response->filterByReferenceSegments($action->getRequestSegmentNumbers()));
        if ($action instanceof PaginateableAction && $action->hasMorePages()) {
           $this->execute($action);    <----
        }
```

it is not longer possible to persist. The following message is issued:
```
Fatal error:  Uncaught RuntimeException: Cannot serialize this action, because it is not waiting for a TAN.
```

Eliminating the marked statements, the logic works fine. The logic is a http script which is opening up a html page asking the user to go about the PushTan challange in the Sparkassen APP. The html page is then issuing a periodic polling as described.
The return is right now the persisted $fints structure stored in a database.

It will be also possible to return the result of the action - however, I honestly do not know how to do this.
In theory, $action needs to be returned, but it cannot be serialized :(
Any pointer to this is welcome.

**Comment by Cugar15** [comment]
Closing this since the explanation of Philipp is correct.
