### ISSUE TITLE
Gerätebezeichnung ist unbekannt

### ISSUE THREAD

**Issue by tabsl** [nemiah/phpFinTS#436]
bei der sparkasse berlin gabs für 2-3 wochen eine umstellung und man muss jetzt das gerät hinterlegen.

das konto hat eigentlich folgenden modi

```
$tanMode = 923; // This is just a placeholder you need to fill!
$tanMedium = 'pushTAN 2.0'; // This is just a placeholder you may need to fill.
```

jedoch kommt hier immer die meldung dass das gerät nicht bekannt ist (wurde auch noch nicht hinzugefügt)

```
9050 (global): Die Nachricht enthält Fehler.
9800 (global): Dialog abgebrochen
9955 (wrt seg 4): Auftrag nicht ausgeführt - Die Gerätebezeichnung ist unbekannt. (MBV07390100255)
FinTS warnings:
3905 (global): Es wurde keine Challenge erzeugt.
3920 (wrt seg 4): Zugelassene Zwei-Schritt-Verfahren für den Benutzer. [923]
```

aber es kommt nicht mal eine pushtan.

nehme ich die standardwerte, kommt eine pushtan die man bestätigen kann, aber es passiert nichts. beim nächsten mal kommt wieder eine pushtan ...

```
$tanMode = 900; // This is just a placeholder you need to fill!
$tanMedium = 'null'; // This is just a placeholder you may need to fill.
```
es steht dann immer hier dass man die tan eingeben soll, aber man hat ja gar keine ...

hat einer idee?

**Comment by tomedar** [comment]
Ich hatte das Problem auch. Das Gerät wurde nicht mehr akzeptiert. Bisher musste ich nur ganz selten per Push-TAN bestätigen und sonst lief die Abfrage immer ohne Push-TAN mit entsprechendem TAN-Medium.
Ich habe mir dann die verfügbaren TAN-Medien ausgeben lassen und hier gibt es nur noch "Alle Geräte". Vorher hatte ich hier ein Gerät mit Namen "iPhone <Zeitstempel>".
Wenn ich als TAN-Medium nun "Alle Geräte" hinterlege, funktioniert die Abfrage wieder. Aber ich muss jedes mal per TAN bestätigen. Und seit gestern erhalte ich nun jedesmal auch eine E-Mail nach der TAN-Bestätigung, dass ein neues Gerät gespeichert wurde. Aber an den verfügbaren TAN-Medien ändert sich leider nichts, hier gibt es nach wie vor nur "Alle Geräte".
Ich bin froh dass es wieder geht, aber hätte lieber ein "eigenes" Gerät ohne ständige Push-TAN. Hat hier jemand eine Idee woran es liegt? Am Code oder an der Bank?

**Comment by tabsl** [comment]
eine wirkliche lösung habe ich zwar nicht. jedoch kann die bank (spk berlin) das neue merkmal für die geräteauthentifizierung deaktivieren und nun klappts wieder, ohne tan-eingabe. es gibt wohl noch des öfteren probleme damit.
