### ISSUE TITLE
Wiederholte Abrufe im Hintergrund - will Auftrag nicht immer in App freigeben

### ISSUE THREAD

**Issue by nQk2** [nemiah/phpFinTS#437]
Ich habe ein phpFinTs-Skript, welches im Hintergrund alle 15 Minuten die neuesten Transaktionen vom Konto holt.
Bis letzte Woche war dies ohne Probleme möglich - ich musste nur alle paar Wochen mal eine TAN eingeben.
Jetzt hat die Bank (Sparkasse) umgestellt auf 923. Das habe ich soweit implementiert. Doch ich muss jetzt jedes Mal, d.h. alle 15 Minuten, in der App den Auftrag freigeben.
Kann man das irgendwie umgehen oder ist das einfach die Sicherheitseinstellung der Sparkasse?

**Comment by peukerjonathan** [comment]
Das klingt so, als würdest du die Kundensystem-ID nicht über die Requests hinweg persistieren.
Schau mal hier: #431 
Das hat das Problem bei mir gelöst.

**Comment by nQk2** [comment]
Danke, das war es!
