### ISSUE TITLE
Lohnt ein Pull Request für Echtzeitüberweisung?

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#438]
Moin,

ich habe die Echtzeitüberweisung implementiert, lohnt sich ein Pull Request dafür noch? Es ist ja schon länger nichts mehr gemerged worden?

**Comment by nemiah** [comment]
Huhu,

ui, ich bekomme es nur nicht immer mit :grin: 

Immer her damit, dann mache ich sie auf einmal.
