### ISSUE TITLE
Fehler in getSaldo()-Funktion

### ISSUE THREAD

**Issue by micronax** [nemiah/phpFinTS#44]
Beim Aufrufen der `FinTs::getSaldo()`-Funktion werfen die Sparkassen folgenden Fehler:

```
[Fhp\Dialog\Exception\FailedRequestException]
  Request Failed: Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.(Die angegebene Bankreferenz/
  Dialog-ID ist nicht gültig.) (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)
```

**Comment by nemiah** [comment]
@micronax meine Sparkasse funktioniert natürlich. Wie sieht dein Code aus?

**Comment by micronax** [comment]
Danke fürs Kümmern! :) Hier mein Code:

```
$sepaAccounts = $this->finTs->getSEPAAccounts();

/** @var SEPAAccount $account */
foreach ($sepaAccounts as $sepaAccount) {
    $hbciAccount = $accountRepo->findOneBy(array('iban' => $sepaAccount->getIban()));

    if ( ! $hbciAccount) {
        $hbciAccount = HbciAccount::fromFinTsSepaAccount($sepaAccount, $this->finTs->getBankName());
    }

    // FIXME: Disabled due to Bug in library
    // $saldo = $this->finTs->getSaldo($sepaAccount)->getAmount();
    // $hbciAccount->setLastAccountSaldo($saldo);

    $this->entityManager->persist($hbciAccount);
}
```

**Comment by nemiah** [comment]
Hmm, hast du die ganz aktuelle Version von phpFinTS? Bei mir läuft es genau so und die Meldung lässt darauf schließen, dass nur der Dialog irgendwo beendet wurde. Schau mal bitte das HBCI log an, was da so passiert.

**Comment by micronax** [comment]
Hatte es auf `dev-master#bf0f7adc30db2aa8b66b13bc412fcc0c49863afc` gelockt. Mit der ganz neusten Version passt es :) Well done!

In welchen Zyklen machst du eig Releases? Müsste es auf einen commit locken, solange es keinen funktionierenden Release gibt 🙈

**Comment by nemiah** [comment]
Aktuell gibt es keinen Release, weil großes Chaos herrscht und das möchte ich nicht unbedingt festschreiben :grin: 

Wenn sich alles beruhigt hat, dann mache ich wieder ein composer-Release.

**Comment by micronax** [comment]
Alles klar! Vielen Dank! 😃
