### ISSUE TITLE
Got neither 3956 nor HITAN with tanProzess=2

### ISSUE THREAD

**Issue by nemiah** [nemiah/phpFinTS#442]
Hi all,

my first customer needs to use decoupled authentication and after he confirms the login in the app, checkDecoupledSubmission throws the error "Got neither 3956 nor HITAN with tanProzess=2".

Does anyone have an idea as to what's the problem?

Nena

**Comment by Philipp91** [comment]
Sounds like https://github.com/nemiah/phpFinTS/issues/412. There's a patch. If it works for you as well, I can send a PR or you can merge it yourself.

**Comment by nemiah** [comment]
Your patch works for my customer also. I'd ask that you send a PR, it is your work.

**Comment by Masegi** [comment]
Is this already merged into release build? I just updated by composer to 3.5.0 and got the error "Got neither 3956 nor HITAN with tanProzess=2" on Sparkasse. Or how can I install a fixed version please?

**Comment by ticktoo** [comment]
Also get this issue with recent phpFinTS at Sparkasse. Verified with vanilla code from your samples-Folder.
