### ISSUE TITLE
Ungültige Auftragsnachricht (9110/9059) in finishStatementOfAccount

### ISSUE THREAD

**Issue by micronax** [nemiah/phpFinTS#46]
Ich versuche gerade, die TAN-Bestätigung bei der Abfrage der Statements zu implementieren. Dabei erhalte ich folgende Fehler:

```
Request Failed: Ungültige Auftragsnachricht? (9110); Die Nachricht enthält Fehler. (9050)
```

**Meine Implementierung:**
```
$this->io->title('HBCI Testing');

$this->hbciService->syncBankAccounts();

$accountRepo = $this->entityManager->getRepository(HbciAccount::class);
$account     = $accountRepo->find(2);

$this->finTs->setTANMechanism(910); // Chip-TAN manuell

$soa = $this->finTs->getStatementOfAccount($account->toFinTsSepaAccount(), new \DateTime('2010-09-01'), new \DateTime());

if ($soa->isTANRequest()) {
    $this->io->error('TAN IS REQUIRED');
    $startCode = $this->getStartCodeFromSoa($soa);

    $this->io->text('Startcode: '.$startCode);

    $tan = $this->io->ask('Enter TAN');

    $soa = $this->finTs->finishStatementOfAccount($soa, $account->toFinTsSepaAccount(), new \DateTime('2019-09-15'), new \DateTime(), $tan);
}

/** @var Statement $statement */
foreach ($soa->getStatements() as $statement) {
    foreach ($statement->getTransactions() as $transaction) {
        $referenceText = substr($transaction->getDescription1(), strpos($transaction->getDescription1(), 'SVWZ+') + 5);

        $this->io->text($referenceText);
    }
}
```

**Debug-Log:**
```
11:16:34 INFO      [app] [HIRMS] 0030: Auftrag empfangen - Bitte die TAN eingeben.(MBT61970200002)

[ERROR] TAN IS REQUIRED

 Startcode: 80044216

 Enter TAN:
 > 912945

11:16:53 INFO      [app]
11:16:53 INFO      [app] HKTAN (Zwei-Schritt-TAN-Einreichung) initialize
11:16:53 DEBUG     [app] > HNHBK:1:3+000000000422+300+[removed]=[removed]=+8'HNVSK:998:3+PIN:2+998+1+1::FEf/[removed]+1:20190919:111653+2:2:13:@8@00000000:5:1+280:[BLZ]:[username]:V:0:0+0'HNVSD:999:1+@207@HNSHK:2:4+PIN:2+910+6856580+1+1+1::FEf/[removed]+1+1:20190919:111653+1:999:1+6:10:16+280:[BLZ]:[username]:S:0:0'HKTAN:3:6+2++++9159-09-19-11.16.34.500839++N++++'HNSHA:4:2+6856580++[password]:924921''HNHBS:5:1+8'
11:16:53 DEBUG     [app] < HNHBK:1:3+000000000507+300+[removed]=[removed]=+8+[removed]=[removed]=:8'HNVSK:998:3+PIN:2+998+1+2::FEf/[removed]+1:20190919:111653+2:2:13:@8@00000000:5:1+280:[BLZ]:[username]:V:0:0+0'HNVSD:999:1+@259@HNSHK:2:4+PIN:2+910+6856580+1+1+2::FEf/[removed]+1+1:20190919:111653+1:999:1+6:10:16+280:[BLZ]:[username]:S:0:0'HIRMG:3:2+9050::Die Nachricht enthält Fehler.'HIRMS:4:2:2+9110:7:Ungültige Auftragsnachricht?: Unbekannter Aufbau.'HNSHA:5:2+6856580''HNHBS:6:1+8'
11:16:53 ERROR     [app] [HIRMG] 9050: Die Nachricht enthält Fehler.
11:16:53 ERROR     [app] [HIRMS] 9110: Ungültige Auftragsnachricht?
11:16:53 ERROR     [app] Request Failed: Ungültige Auftragsnachricht? (9110); Die Nachricht enthält Fehler. (9050)
11:16:53 CRITICAL  [app] Request Failed: Ungültige Auftragsnachricht? (9110); Die Nachricht enthält Fehler. (9050)
11:16:53 ERROR     [console] Error thrown while running command "app:hbci:test -vvv". Message: "Request Failed: Ungültige Auftragsnachricht? (9110); Die Nachricht enthält Fehler. (9050)"
```

**Comment by nemiah** [comment]
Bitte mach das gleiche doch mal mit Hibiscus und vergleiche die Logs

**Comment by interose** [comment]
@micronax konntest du die Logs schon vergleichen bzw. dein Problem lösen?
Ich habe bei einer Überweisung bei der DKB das gleiche Problem.

**Comment by interose** [comment]
@nemiah Mein Account wurde wieder entsperrt und ich konnte eine Überweisung mit Hibiscus durchführen und das Log speichern. Hättest du einen Hinweis für mich auf was ich achten soll da ich jetzt in dem Protokoll nicht so fit bin.

**Comment by nemiah** [comment]
@interose Ich würde in dem Log mit dem Fehler die Nachricht vor der Fehlermeldung mit der entsprechenden Nachricht aus dem funktionierenden Log vergleichen.
Das Problem dürfte in einer Nachricht sein, die du gesendet hast.
ein `str_replace("'", "'\n" $log);` wirkt wunder, was die Übersichtlichkeit angeht :blush:

**Comment by interose** [comment]
@nemiah  Also in beiden Logs bekomme ich eine Antwort der Bank mit der Meldung "Auftrag empfangen - Bitte die empfangene TAN eingeben.". Die Antwort schaut zwar im Hibiscus Log etwas anders aus aber da das Antriggern der Push-Tan App funktioniert würde ich mal annehmen dass bis zu diesem Zeitpunkt noch alles passt.
Erst nach dem Versender der TAN zur Bank kommt die Antwort "Ungültige Auftragsnachricht"

Hier mal die beiden Logs. Da das Log ja persönliche Daten enthält habe ich versucht diese zu Entfernen.

Hibiscus
```
HNHBK:1:3+000000000435+300+[removed]=[removed]=+3'
HNVSK:998:3+PIN:2+998+1+1::[removed]+1:20190930:143129+2:2:13:@8@00000000:5:1+280:[BLZ]:[username]:V:0:0+0'
HNVSD:999:1+@214@HNSHK:2:4+PIN:2+921+1930432223+1+1+1::[removed]+1+1:20190930:143053+1:999:1+6:10:16+280:[BLZ]:[username]:S:0:0'
HKTAN:3:6+2++++6404-09-30-14.30.53.311109+N'
HNSHA:4:2+1930432223++[removed]:[tan]'
'
HNHBS:5:1+3'
```
FinTS
```
HNHBK:1:3+000000000434+300+[removed]=[removed]=+4'
HNVSK:998:3+PIN:2+998+1+1::[removed]+1:20190930:144219+2:2:13:@8@00000000:5:1+280:[BLZ]:[username]:V:0:0+0'
HNVSD:999:1+@213@HNSHK:2:4+PIN:2+921+9553203+1+1+1::[removed]+1+1:20190930:144219+1:999:1+6:10:16+280:[BLZ]:[username]:S:0:0'
HKTAN:3:6+2++++4839-09-30-14.41.40.311189++N++++'
HNSHA:4:2+9553203++[removed]:[tan]'
'
HNHBS:5:1+4'
```

Vielleicht sieht jemand mit Erfahrung im HBCI Protokoll den Fehler.

**Comment by nemiah** [comment]
Hmm, ich denke, das Hauptproblem ist der unterschiedliche Aufbau des HKTAN-Teils in der 4.Zeile.
Du kannst das Array in der Segment/HKTAN.php mal anpassen, bis sie übereinstimmen. Es dürfte um das `++N++++` gehen.

**Comment by interose** [comment]
Jap, wenn ich das Array anpasse, dann geht die Überweisung durch. 

Ich hab mal versucht den Aufbau des Arrays irgendwie mit Hilfe der Spezifikation nachzuvollziehen aber ich werde nicht schlau daraus. In diesem Dokument [pdf](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2018-02-23_final_version.pdf) auf der Seite 45 sind die Felder beschrieben und es sind ja definitiv mehr Felder als im Hibiscus Log.

**Comment by nemiah** [comment]
Ich versuche nie, es zu verstehen :wink: 
Die Frage ist, welches Kriterium sagt uns, wie wir die HKTAN aufbauen müssen…
Was wird als $version an die Methode übergeben?
Schau mal hier in die HKTAN-Klasse, ob es so ähnlich ist: c02a242d21c813ca1568c60eef24e325c666c6da

**Comment by interose** [comment]
OK - auch eine Möglichkeit :D!
Die Variable `$version` enthält bei mir den Wert 6.
Ja genau - ich hab mir deine Änderungen der Datei HKTAN.php aus dem Commit kopiert und damit funktioniert es ebenfalls. 👍

**Comment by nemiah** [comment]
Hmm, ok, dann müssen wir versuchen, herauszufinden, was im neuen Code anders ist…

**Comment by interose** [comment]
Also ich habe jetzt nochmal ein paar Tests gemacht und etwas in der Spec gestöbert, bzw. @nemiah du hast es ja schon richtig implementiert. Es geht um das Array in der HKTAN Klasse, bzw. genauer um die Position des "N".
Wie man [hier](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2018-02-23_final_version.pdf) auf der Seite 45 bzw. Seite 46 sieht, muss das "N" bei einer Einzelüberweisung an der Stelle 7 stehen. Im Master wird es an die 8. Stelle gepackt. Hier nochmal die entsprechenden Logs dazu:

    master - geht nicht:
    HKTAN:3:6+2++++4839-09-30-14.41.40.311189++N++++' 

    experimental branch - geht:
    HKTAN:3:6+2++++6404-09-30-14.30.53.311109+N'

    eigener Test - geht:
    HKTAN:3:6+2++++4839-09-30-14.41.40.311189++N++++'

Man sieht, nicht die Anzahl der Elemente in dem Array sind für den Fehler verantwortlich, sondern die Postion des N, die ja (zumindest verstehe ich es so) kennzeichnen soll, dass keine weitere TAN folgt. Ein N an Position 8 steht lt. Spec für Auftrag stornieren.

Was ich mich jetzt nur frage, die Spec ist vom Februar 2018. Warum hat das bisher funktioniert? Kommt das jetzt durch die Umstellung des TAN Verfahrens oder haben bisher so wenig User dieses Feature genutzt?

**Comment by ampaze** [comment]
@interose Die Position des N hat sich erst mit dem PR #40 vor einigen Tagen verschoben, darum ging es vorher auch. Es gab erst Probleme als bestimmte Banken einen (leeren) String im tanMediaName erwarteten, siehe PR #40.

Im aktuellen master ist die Position des N korrigiert, es sollte also wieder funktionieren.
