### ISSUE TITLE
What getter to use to retreive message from UnexpectedResponseException|CurlException|\Exception

### ISSUE THREAD

**Issue by Cugar15** [nemiah/phpFinTS#461]
I am trying to figure out what the correct getter is to retrieve the protected message when an UnexpectedResponseException|CurlException|\Exception is thrown.

Any pointers appreciated.

**Comment by Philipp91** [comment]
I don't understand the question. What is "the protected message"? And where is that exception thrown from?

**Comment by Cugar15** [comment]
Sending a SEPADirectDebit with the wrong format throws an Fhp\UnsupportedException:

```
Fhp\UnsupportedException Object
(
    [message:protected] => The bank does not support the XML schema urn:iso:std:iso:20022:tech:xsd:pain.008.003.02, but only urn:iso:std:iso:20022:tech:xsd:pain.001.001.03, urn:iso:std:iso:20022:tech:xsd:pain.001.001.09, urn:iso:std:iso:20022:tech:xsd:pain.008.001.02, urn:iso:std:iso:20022:tech:xsd:pain.008.001.08
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\Action\SendSEPADirectDebit.php
    [line:protected] => 152
    [trace:Exception:private] => Array
```

How to get the message? Just $e->message won't work since "message" is protected.

**Comment by Philipp91** [comment]
https://www.php.net/manual/en/exception.getmessage.php

**Comment by Philipp91** [comment]
I recommend you use some kind of IDE (like VS Code with some PHP extensions) that is capable of auto-completing `$e->getMessage()`. Even the 90s-style IntelliSense can do that after you've typed `$e->mess...`. Modern AI-based suggestion tools can probably even do it after just `$e`.

**Comment by Cugar15** [comment]
Mistakes, your best teacher are!
