### ISSUE TITLE
Fehler Login TAN-Verfahren SecureGo (Plus)

### ISSUE THREAD

**Issue by wienen-it-dev** [nemiah/phpFinTS#465]
Hallo zusammen,

bitte nochmals um Hilfe beim FinTS Login:

Bei Volksbank / Raiffeisenbank hatte der Login mit SecureGo / SecureGo plus (Direktfreigabe) mit php-fints Version 3.3 funktioniert.

Seit Update auf php-fints dev-master funktioniert dies leider nicht mehr, folgende Fehlermeldung tritt auf:

tanMedium not allowed for this tanMode

Hat jemand eine Idee, was geändert werden muss?

Vielen Dank

stack trace:

#0 vendor/nemiah/php-fints/lib/Fhp/FinTs.php(830): Fhp\FinTs->getSelectedTanMode()
#1 vendor/nemiah/php-fints/lib/Fhp/FinTs.php(564): Fhp\FinTs->executeWeakDialogInitialization()
#2 fints_import.php(736): Fhp\FinTs->getTanMedia()

**Comment by Philipp91** [comment]
> Seit Update auf php-fints dev-master

Liegt es wirklich daran? (Es könnte auch eine Bank-seitige Änderung sein.) Wenn du zu 3.3 zurück wechselst, geht es dann wieder?

Wenn man [diesem Diff](https://github.com/nemiah/phpFinTS/compare/3.3...master) glauben darf, haben wir an der Stelle um `getSelectedTanMode()` herum nicht wirklich was verändert. Höchstens die Änderung in `getTanModes()` könnte relevant sein, wenn du das aufrufst befor der Fehler auftritt.

----

Vermutlich rufst du `selectTanMode()` mit einem `$tanMedium` auf, das nicht zum `$tanMode` passt, weil dein `$tanMode->needsTanMedium()===false` ist.

**Comment by wienen-it-dev** [comment]
@Philipp91 Vielen Dank für Deine Hilfe. Die Fehlerursache war doch nicht das Update auf dev-master. An der Stelle selectTanMode() war noch ein Fehler in unserer Applikation vorhanden, wenn tanMedium nicht required ist.

Erfolgreich getestet mit Raiffeisenbank
