### ISSUE TITLE
Vorgemerkte Umsätze werden als gebucht behandelt

### ISSUE THREAD

**Issue by DoctorMorris** [nemiah/phpFinTS#47]
Beim Abruf von Kontoumsätzen bei der Sparkasse Düren wird der Trenner zwischen gebuchten und vorgemerkten Umsätzen nicht erkannt.

$this->rawData:

> :20:STARTUMSE
> ...
> :62F:C190919EURXXX,XX
> -+\@1073\@
> :20:STARTDISPE
> ...
> \-

https://github.com/nemiah/phpFinTS/blob/1cbbf0d758b9088222983092846f9947405bf810/lib/Fhp/Parser/MT940.php#L58

$cleanedRawData:

> :20:STARTUMSE
> ...
> :62F:C190919EURXXX,XX-+\@1073\@
> :20:STARTDISPE
> ...
> :90D:3EURXX,XX
> :90C:0EURXX,XX-

https://github.com/nemiah/phpFinTS/blob/1cbbf0d758b9088222983092846f9947405bf810/lib/Fhp/Parser/MT940.php#L65

$day[$i]:

> 62F:C190919EURXXX,XX-+\@1073\@

Dies wird dann hier leider nicht erkannt:

https://github.com/nemiah/phpFinTS/blob/1cbbf0d758b9088222983092846f9947405bf810/lib/Fhp/Parser/MT940.php#L68

Ich kenne die Spezifikation leider zu wenig, so dass ich hier keinen vernünftigen Verbesserungsvorschlag machen kann.

**Comment by nemiah** [comment]
Probier mal bitte :wink:

**Comment by DoctorMorris** [comment]
Das funktioniert. :-) Ich dachte, dass eine Änderung evtl. schon in einem der vorangegangen Parsing Schritte hätte erfolgen müssen. Temporär hatte ich `if (trim($day[$i]) == '20:STARTDISPE') {` bei mir im Einsatz, das hatte auch funktioniert, das war aber natürlich keine universelle Lösung.

**Comment by nemiah** [comment]
Ja, sie haben wohl den Aufbau der Nachricht geändert, weswegen das `^` raus musste :boom:
