### ISSUE TITLE
Uncaught TypeError: Return value of testLogger::log() must be an instance of void, none returned 

### ISSUE THREAD

**Issue by nQk2** [nemiah/phpFinTS#49]
Uncaught TypeError: Return value of testLogger::log() must be an instance of void, none returned 

Was mach ich falsch?

**Comment by nQk2** [comment]
Offenbar ein < PHP 7.1 Problem. Musste :void entfernen.

**Comment by MKHSKY** [comment]
Das Ding ist, PHP Versionen unter 7.1 werden nicht mehr supportet (Und auch 7.1 bald nicht mehr). Soll PHP < 7.1 weiterhin unterstützt werden @nemiah?

https://www.php.net/supported-versions.php

**Comment by nemiah** [comment]
Ja, zumindest ich brauche noch die 5.6 für eine Weile und kann deswegen im Moment noch keine nicht abwärtskompatiblen Änderungen einbauen.
