### ISSUE TITLE
Es ist unnötigt kompliziert den timeout-Wert des Curl-Adapters zu ändern.

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#5]
Hoffe es ist ok wenn ich hier auf Deutsch schreibe. Kann es auch auf Englisch schreiben wenn gewünscht.

Vielen Dank für deine Arbeit an diesem vielversprechenden Fork :smile:. 
*mschindler83/fints-hbci-php* scheint mir nicht mehr weitergeführt zu werden, daher halte ich es für sinnvoller Verbesserungen hier zu pflegen.

Da der Server unserer Bank sich manchmal sehr viel Zeit beim Antworten lässt, muss ich den Timeout auf mehr als 30 Sekunden erhöhen. Dies ist momentan nur mit einigem Copy und Paste möglich.

Am einfachsten wäre es die Methode `\Fhp\Adapter\Curl::connect` auf protected zu ändern. Dann kann man die Klasse bzw. Methode ableiten und den Timeout setzen. Alternativ wäre natürlich ein neuer Parameter $timeout in den Klassen FinTs und Curl noch besser.

**Comment by nemiah** [comment]
Hallo @ampaze ,

ich finde es ok, denn FinTS ist sowieso ein deutsches Protokoll ;)

Ich würde den Curl-Adapter komplett auflösen und den Code mit in die Connection-Klasse übernehmen. Es wird ja wohl bis auf weiteres bei curl bleiben.

Dann müssten wir nur noch die Instanzierung der Connection-Klasse aus dem Konstruktor nehmen und dann können wir eine neue Methode setConnectionTimeout in die FinTS-Klasse einbauen. Der Timeout wird dann bei new Connection() mit übergeben. Ich denke, das wäre eine saubere Lösung.

Was denkst du?

Liebe Grüße
Nena

**Comment by ampaze** [comment]
Hi Nena,

klingt sehr gut! Es wäre aber durchaus sinnvoll auch irgendwie an den curl-Handle zu kommen, falls man mal doch eigene Curl Optionen setzen muss. 

Gruß
Tim

**Comment by nemiah** [comment]
Ok, ich habe die Adapter-Inftrastruktur mal rausgeschmissen.

Es sollte soweit noch alles laufen ;)

Man kann jetzt die Timeouts über setTimeouts setzen und im Moment kommt man über FinTs->connection->getCurlHandle() an den curl handle.

Liebe Grüße
Nena

**Comment by ampaze** [comment]
Funktioniert bestens. Vielen Dank!
