### ISSUE TITLE
DKB funktioniert nicht

### ISSUE THREAD

**Issue by nQk2** [nemiah/phpFinTS#50]
Mein Aufruf ist wie folgt:

  $fints = new FinTs(
      FHP_BANK_URL_DKB,
      FHP_BANK_PORT_DKB,
      FHP_BANK_CODE_DKB,
      FHP_ONLINE_BANKING_USERNAME_DKB,
      FHP_ONLINE_BANKING_PIN_DKB,
        new testLogger(),
      FHP_REGISTRATION_NO,
      FHP_SOFTWARE_VERSION
  );

  $fints->setTANMechanism(921); // die Nummer 921 stand irgendwo in einer Response der DKB...

  $accounts = $fints->getSEPAAccounts();

Aber ich erhalte:
<b>Fatal error</b>:  Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Aufrufe ohne PSD2-Modus nicht mehr erlaubt, Dialog abgebrochen (9075); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Banking-Programm muss zum 14.09.2019 auf PSD2 umgestellt werden. (3075) in /var/www/html/vendor/nemiah/php-fints/lib/Fhp/Dialog/Dialog.php:165

Danke für eure Hilfe.

**Comment by nemiah** [comment]
Mit getVariables() solltest du die möglichen TAN-Verfahren bekommen.
Funktioniert das?

**Comment by nQk2** [comment]
getVariables() bringt:
stdClass Object
(
    [tanModes] => Array
        (
            [0] => 6
            [J] => 
            [910] => chipTAN manuell
            [6] => 2
            [1] => N
            [N] => 1
            [2] => 6
            [iTAN] => 3
            [HHD1.3.2USB] => 1
            [Secoder_UC] => TAN-Nummer
            [] => 3
            [TAN2go] => J
        )

)

Dann habe ich versucht
$fints->setTANMechanism('TAN2go');
und
$fints->setTANMechanism('J');

=> Selber Fehler.

**Comment by nemiah** [comment]
Hmm, diese Ausgabe ist auch falsch, da klappt der Parser wohl bei dir noch nicht.
Probiers mal mit `$fints->setTANMechanism(910);`

**Comment by Philipp91** [comment]
> diese Ausgabe ist auch falsch, da klappt der Parser wohl bei dir noch nicht

+1 @nQk2 Funktioniert es mit dem neuen Parser in #53? Das `tanModes` Array sollte in etwa so aussehen: `[920 => 'smsTAN', 900 => 'iTAN', ..., 921 => 'TAN2go']`, also Integer-Schlüssel und String-Werte.

**Comment by nQk2** [comment]
Bin jetzt auf dev-master und erhalte:
```
[HIRMG] 3060: Bitte beachten Sie die enthaltenen Warnungen/Hinweise.
[HIRMS] 3050: BPD nicht mehr aktuell, aktuelle Version enthalten.
[HIRMS] 3920: Zugelassene Zwei-Schritt-Verfahren für den Benutzer.
[HIRMS] 0020: Der Auftrag wurde ausgeführt.
[HIRMS] 3076: Starke Kundenauthentifizierung nicht notwendig.
...
[HIRMG] 9050: Die Nachricht enthält Fehler.
[HIRMG] 9800: Dialog abgebrochen
[HIRMG] 9930: Kein gültiges Sicherheitsprofil.
[HIRMS] 9010: Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.
Request Failed: Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Kein gültiges Sicherheitsprofil. (9930)
Request Failed: Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Kein gültiges Sicherheitsprofil. (9930)
```

**Comment by interose** [comment]
Hallo zusammen,
ich habe mir heute den dev-master geholt und ebenfalls einen Test mit der DKB gemacht.
Ein getVariables liefert mir folgendes Array zurück:

`Array
(
    [920] => smsTAN
    [900] => iTAN
    [910] => chipTAN manuell
    [911] => chipTAN optisch
    [912] => chipTAN-USB
    [913] => chipTAN-QR
    [921] => TAN2go
)`

Beim Versuch den Kontostand abzufragen bekomme ich ebenfalls die Meldung

`Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800); Kein gültiges Sicherheitsprofil. (9930)`

Ich benutze den TAN Mechanismus TAN2go also die 921. Interessanterweise wird mir smsTAN und iTAN gar nicht mehr im Backend der DKB als mögliches TAN Verfahren angeboten. Hat jemand chipTAN schon mal versucht?

Wenn ich noch etwas debuggen, testen oder noch Infos liefern soll, bitte einfache Bescheid geben.

**Comment by interose** [comment]
Sorry jetzt muss ich mich nochmal melden.
Ich hab mir jetzt leider erst danach den Issue #43 angeschaut bzw. durchgelesen. Ich kann bestätigen dass bei der DKB das gleiche Problem besteht.
Das Erstellen des Arrays für den options Parameter des Message Objekts unterscheidet sich zwischen initDialog und syncDialog. Setzte ich in der Methode initDialog die Option `AbstractMessage::OPT_PINTAN_MECH` statisch auf meine TAN Methode dann funktioniert es.

**Comment by na-oma** [comment]
@interose Mein Fix aus #43 sollte seit ca. 7 Tagen im master sein, geht das bei dir?

**Comment by interose** [comment]
Hallo @na-oma, ja funktioniert top. Vielen Dank!
Sorry hätte ich schreiben müssen, aber ich hab mir mit Hibiscus meinen DKB Zugang gebrickt und jetzt war ich so genervt dass ich alles liegen gelassen hab.

**Comment by nQk2** [comment]
Alles funktioniert wieder! Danke!

**Comment by Philipp91** [comment]
> Setze ich in der Methode initDialog die Option AbstractMessage::OPT_PINTAN_MECH statisch auf meine TAN Methode dann funktioniert es.

Ich mache `$fints->setTANMechanism(921);` und dann gleich `$fints->getStatementOfAccount(...);`. Dabei wird `initDialog()` gar nie aufgerufen -- unter anderem ist es in `getStatementOfAccount()` auskommentiert. Sollte das so sein?

Wenn ich vorher `$fints->getSEPAAccounts()` ausführe, dann funktioniert es -- selbst wenn ich das Ergebnis davon ignoriere. Das ist natürlich kein stabiler Zustand für `phpFinTS` -- API-Aufrufe sollten unabhängig davon funktionieren, was man vorher gemacht hat. Es funktioniert ebenfalls wenn ich [diesen ganzen Abschnitt hier](https://github.com/nemiah/phpFinTS/blob/master/lib/Fhp/FinTs.php#L216-L220) in die `getStatementOfAccount()` rein kopiere.

Da scheint also ein ganz eigener Dialog notwendig zu sein bevor man die eigentliche Abfrage machen kann. Was sich zwischenzeitlich im Zustand von `FinTs` ändert, ist: `hksalVersion` und `hksalVersion` wechseln von Version `6` zu `5`, und `systemId` und `bankName` werden gefüllt. Diese Felder würde ich alle zu den "Bankparamterdaten (BPD)" zählen.

Meiner Ansicht nach sollte `phpFinTS` eine Möglichkeit bereitstellen, wie die BPD und die UPD zwischengespeichert werden können. Das sollte zwar nicht _notwendig_ sein, aber möglich. Wenn BPD und UPD nicht verfügbar sind (und momentan sind sie das nie, weil `phpFinTS` immer von null startet, dann müssen sie systematisch abgeholt werden (das schreibt die Spezifikation vor). Das ist nicht wirklich auf dem Level eines "Dialogs" der initialisiert werden muss, sondern auf dem Level einer `FinTs`-Instanz, die sich erstmal mit der Bank bekannt machen muss. Wenn noch niemand eine sauberere Lösung in der Richtung hat, werde ich eine implementieren.

**Comment by nemiah** [comment]
Ich habe es noch nie ohne `getSEPAAccounts()` benutzt, deswegen ist es mir wohl nicht aufgefallen. Wenn die Daten nicht vorhanden sind, dann würde ich sie einfach vorher abfragen, ja.
