### ISSUE TITLE
Verwendungszweck wird in speziellen Fällen nicht korrekt geparst

### ISSUE THREAD

**Issue by DoctorMorris** [nemiah/phpFinTS#54]
Der folgende Fall wird nicht korrekt geparst:

> :86:171(...)?20EREF+TedyHz.1568781920
> 13439?210?22KREF+(...)

EREF müsste "TedyHz.1568781920134390" sein, die "0" am Ende wird jedoch abgeschnitten.

Ich schlage vor, die Zeile

https://github.com/nemiah/phpFinTS/blob/63c821ff4cea2ba6bf637398e83310aad0e5f7fc/lib/Fhp/Parser/MT940.php#L186

zu

`if ($m[2] != '') {`

zu ändern.

**Comment by nemiah** [comment]
@DoctorMorris Hört sich gut an, ich bitte um einen PR :blush:
