### ISSUE TITLE
Volksbank Emmerich-Rees funktioniert nicht mehr

### ISSUE THREAD

**Issue by mmeinesz** [nemiah/phpFinTS#55]
Seit der Umstellung am 11.09.19 funktioniert unser Import von neuen Bank-Transaktionen leider nicht mehr. Wir sind bei der Volksbank Emmerich-Rees.
Wir benutzen phpFinTS seit einigen Monaten erfolgreich in unserer eigenen Firmensoftware. Diese ist auf Apache/PHP/MySQL basiert. Der Abgleich erfolgt z.Zt noch über einen Cronjob. Möglicherweise müsste dieser in Zukunft interaktiv manuell aufgerufen werden (?)

Hätte jemand Interesse sich des Problems anzunehmen? Es handelt sich um eine vergütete Arbeit, möglichst auf Rechnung. Dank & Gruß an die Gemeinschaft.
M.Meinesz

**Comment by nemiah** [comment]
@mmeinesz Meine Erfahrung ist, dass die Banken erst einen zweiten Faktor (TAN) abfragen, wenn die Umsätze von mehr als den letzten 90 Tagen angefordert werden.

**Comment by mmeinesz** [comment]
OK. Man könnte den cronjob laufen lassen, und ggf. manuel eine interactive Verbindung aufbauen.
