### ISSUE TITLE
FinTs::getVariable breaks communication

### ISSUE THREAD

**Issue by fbett** [nemiah/phpFinTS#66]
Hi,

while my reviews (see pull request #65 ) i discovered some issues if "FinTs::getVariable" gets called on the way to receive transactions.

Trace:
- fints = new FinTS\FinTS(...)
- fints->getSEPAAccounts()
- fints->getVariables()
- fints->getStatementOfAccount <-- Here will the error be logged

I could produce this problem with these banks:

Deutsche Bank:
Auftrag ausgeführt. (0020); Auftrag abgelehnt - Zwei-Schritt-TAN inkonsistent. Eingereichter Auftrag gelösch (9210); Teilweise fehlerhaft. (9050)

Volksbank:
Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet.(Die angegebene Bankreferenz ist nicht gültig.) (9010); Die Nachricht enthält Fehler. (9050); Dialog abgebrochen (9800)

Without calling "getVariables", the result is fine.

After some tests, I'm pretty sure, it has nothing to with HKTAN (especially the segementIdent) or the given Pin/Tan method in generally.

**Comment by nemiah** [comment]
Hi @fbett,

it is possible that `getVariables` causes a break in the communication, I never tested it in this combination.

The Volksbank-error suggests that some id is reset. Maybe it's because of the `syncDialog`-call.
Can you call `getVariables` twice right after each other?

**Comment by ampaze** [comment]
Es sollten m.M. nach die Parameter beim $dialog->sync() mitgespeichert werden und nicht erneut sync aufgerufen werden. 

Seit #95 machen wir genau das ja auch. Man könnte also statt getVariables einfach sowas wie getBpd() benutzen und sich von dort alle Infos holen. Die Methode getVariables könnte eigentlich weg dann genau wie die GetVariables Klasse.
