### ISSUE TITLE
Consorsbank funktioniert nicht

### ISSUE THREAD

**Issue by Philipp91** [nemiah/phpFinTS#67]
Code von master a9a13c6. `$fints->getVariables()` liefert `tanModes=[900=SecurePlus]`. Also `$fints->setTANMechanism(900);`. `$fints->getSEPAAccounts()`, aber die Antwort auf `HKSPA` ist `HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9120::Unerwartete Nachricht.`.

Laut dem Forum der Consorsbank (und meinem Test mit Banking4) brauchen andere Programme eine von der App generierte TAN für jede Aktion. Vermutlich hätte `phpFinTS` also eine TAN mitsenden müssen. Ich versuche, das mal vorübergehend einzubauen.

**Comment by nemiah** [comment]
:+1:

**Comment by Philipp91** [comment]
Funktioniert jetzt mit `FinTsNew`.
