### ISSUE TITLE
VR Bank - Eine Challenge-Anfrage wurde abgebrochen, der Auftrag wird nicht ausgeführt. (9260)

### ISSUE THREAD

**Issue by DenisBrenner** [nemiah/phpFinTS#69]
Hallo beim ausführen von $fints->executeSEPADirectDebit(...) bekomme ich folgende Fehlermeldung:
Request Failed:
Die Nachricht enthält Fehler. (9050);
Dialog abgebrochen (9800);
Eine Challenge-Anfrage wurde abgebrochen, der Auftrag wird nicht ausgeführt. (9260)

kann jemand damit etwas anfangen und hat einen Tipp?

Vielen Dank im Voraus.

**Comment by nemiah** [comment]
Hallo @DenisBrenner,

vergleiche bitte das Log von phpFinTS mit dem Log von Hibiscus.

**Comment by Heart1010** [comment]
> Eine Challenge-Anfrage...
deutet oft daraufhin, dass Dein TAN-Verfahren gesperrt ist (3x falsche TAN eingegeben oder schlichtweg durch Tests 3 TAN-Anforderungen losgeschickt und nie eine TAN eingegeben). Führt beides zur sm@rt-TAN Sperre. Musst bei Bank anrufen und deinen ATC-Wert der girocard durchgeben, damit sie wieder entsperrt werden kann. (ATC-Wert bekommst, wenn Du Karte in den Generator steckst > TAN-Taste > Startcode "08" > OK)

**Comment by DenisBrenner** [comment]
Ok vielen Dank für die Infos,
es ist aber SMSTan beim Konto hinterlegt. Kann das da dann auch sein?

Hat jemand das aktuell lauffähig mit SMSTan und VRBank-Freiburg und kann eventuell seine Konfiguration posten?

**Comment by Heart1010** [comment]
@DenisBrenner Mit o.g. Fehler findet sich auch folgendes:

> Hier wird versucht, eine Sammelzahlung mit nur einer Zahlung am Bankrechner einzureichen. Der betreffende Bankrechner verlangt bei Sammelzahlungen aber mind. zwei Zahlungen.
Lösung
Diese Zahlung muss als Einzelauftrag an die Bank gesendet werden.

**Comment by DenisBrenner** [comment]
Ich habe es jetzt geändert. Nun bekomme ich aber das hier:

Die Nachricht enthält Fehler. (9050);
Dialog abgebrochen (9800);
Kein gültiges Sicherheitsprofil. (9930)

Echt komisch.

**Comment by DenisBrenner** [comment]
Danke für die Hilfe. Ich habe nun herausgefunden woran es liegt. Ich versuche eine Sammellastschrift zu machen, es scheint aber nur mit einer einzelnen zu gehen.

Weiß jemand, was man ändern muss,, damit es mit Sammellastschriften geht?

**Comment by nemiah** [comment]
Funktionieren Sammellastschriften mit einer anderen Anwendung?

**Comment by DenisBrenner** [comment]
ja, das klappt da.

**Comment by nemiah** [comment]
Ok, dann vergleiche doch bitte das Log von Hibiscus (https://www.willuhn.de/products/hibiscus/) mit dem Log von phpFinTS :relaxed:

**Comment by DenisBrenner** [comment]
So wie ich das sehe ist in der executeSEPADirectDebit(...) funktion HKDSE und HKDSC angelegt.

Das sind beides Einzellastschriften-Vorgänge so wie ich das sehe müsste man HKDME implementieren wenn es um mehrere Vorgänge geht, oder bin ich da falsch?

**Comment by nemiah** [comment]
Ich habe mich damit nicht beschäftigt, aber es ist gut möglich, dass eine andere Nachricht dafür vorgesehen ist, ja.

**Comment by ampaze** [comment]
> So wie ich das sehe ist in der executeSEPADirectDebit(...) funktion HKDSE und HKDSC angelegt.
> 
> Das sind beides Einzellastschriften-Vorgänge so wie ich das sehe müsste man HKDME implementieren wenn es um mehrere Vorgänge geht, oder bin ich da falsch?

Ja das ist korrekt. HKDME habe ich bei uns implementiert, allerdings nützt dir das nicht viel wenn du das nötige XML dafür nicht auch generieren kannst. Für das HKDME Segment kann ich aber einen PR machen.
