### ISSUE TITLE
Die Zeichensatzkonvertierung sollte abhängig vom Segment Typ sein

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#7]
Momentan wird jede Antwort vom Server in Connection.php via

```
return iconv('ISO-8859-1', 'UTF-8', $this->adapter->send($message));
```

nach UTF-8 konvertiert. Dies führt zu Kodierungsfehlern, wenn die Payload schon UTF-8 ist, wie z.B. Kontoumsätze im CAMT XML Format.

Meine erste Idee dies zu fixen wäre, die allgemeine Konvertierung (siehe oben) rauszunehmen und in der Methode Response::findSegments abhängig nach Segment zu kodieren.

```
$split = explode(':', $segment, 2);

if ($name != 'HICAZ') {
    $segment = iconv('ISO-8859-1', 'UTF-8', $segment);
}
```

**Comment by nemiah** [comment]
Hallo @ampaze,

das klingt gut, ich freue mich über einen PR ;)

Liebe Grüße,
Nena
