### ISSUE TITLE
DKB Umsätze abholen schlägt fehl wegen HKTAN syntax error

### ISSUE THREAD

**Issue by ddbxx** [nemiah/phpFinTS#72]
Wenn man bei DKB Umsätze für mehrere Monate abholt, wird eine TAN abgefragt. Beim Senden der TAN ist das Segment HKTAN fehlerhaft. Hier die Log:

    HNHBK:1:3+000000000434+300+838777019240=915521646312BLDW=+4'
    HNVSK:998:3+PIN:2+998+1+1::JjfQADhssW0BAAAaHkKx0lkXrAQA+1:20191009:130913+2:2:13:@8@00000000:5:1+280:12030000:1234567890:V:0:0+0'
    HNVSD:999:1+@213@HNSHK:2:4+PIN:2+921+6094421+1+1+1::JjfQADhssW0BAAAaHkKx0lkXrAQA+1+1:20191009:130913+1:999:1+6:10:16+280:12030000:1234567890:S:0:0'
    HKTAN:3:6+2++++6446-10-09-19.08.47.211169++N++++'
    HNSHA:4:2+6094421++123456:123456'
    '
    HNHBS:5:1+4'

    HNHBK:1:3+000000000519+300+838777019240=915521646312BLDW=+4+838777019240=915521646312BLDW=:4'
    HNVSK:998:3+PIN:2+998+1+2::JjfQADhssW0BAAAaHkKx0lkXrAQA+1:20191009:190914+2:2:13:@8@00000000:5:1+280:12030000:1234567890:V:0:0+0'
    HNVSD:999:1+@265@HNSHK:2:4+PIN:2+921+6094421+1+1+2::JjfQADhssW0BAAAaHkKx0lkXrAQA+1+1:20191009:190914+1:999:1+6:10:16+280:12030000:1234567890:S:0:0'
    HIRMG:3:2+9050::Die Nachricht enthält Fehler.'
    HIRMS:4:2:2+9110:7:Ungültige Auftragsnachricht?: Unbekannter Aufbau.'
    HNSHA:5:2+6094421'
    '
    HNHBS:6:1+4'

So funktioniert es:

    HNHBK:1:3+000000000429+300+869099164116=310616646312BLDW=+4'
    HNVSK:998:3+PIN:2+998+1+1::NCrxADhssW0BAAAaHkKx0lkXrAQA+1:20191009:131721+2:2:13:@8@00000000:5:1+280:12030000:1234567890:V:0:0+0'
    HNVSD:999:1+@208@HNSHK:2:4+PIN:2+921+7593837+1+1+1::NCrxADhssW0BAAAaHkKx0lkXrAQA+1+1:20191009:131721+1:999:1+6:10:16+280:12030000:1234567890:S:0:0'
    HKTAN:3:6+2++++7760-10-09-19.16.57.711109+N'
    HNSHA:4:2+7593837++123456:123456'
    '
    HNHBS:5:1+4'

    HNHBK:1:3+000000026628+300+869099164116=310616646312BLDW=+4+869099164116=310616646312BLDW=:4'
    HNVSK:998:3+PIN:2+998+1+2::NCrxADhssW0BAAAaHkKx0lkXrAQA+1:20191009:191721+2:2:13:@8@00000000:5:1+280:12030000:1234567890:V:0:0+0'
    HNVSD:999:1+@26372@HNSHK:2:4+PIN:2+921+7593837+1+1+2::NCrxADhssW0BAAAaHkKx0lkXrAQA+1+1:20191009:191721+1:999:1+6:10:16+280:12030000:1234567890:S:0:0'
    HIRMG:3:2+3060::Bitte beachten Sie die enthaltenen Warnungen/Hinweise.'
    HIRMS:4:2:3+0020::Der Auftrag wurde ausgeführt.+0020::Die gebuchten Umsätze wurden übermittelt.+3040::Es liegen weitere Informationen vor.:3855-10-09-19.17.21.638552'
    HITAN:5:6:3+2++7760-10-09-19.16.57.711109'
    HIKAZ:6:5:3+@25923@

Der Unterschied liegt im HKTAN-Segment

    HKTAN:3:6+2++++6446-10-09-19.08.47.211169++N++++'
    HKTAN:3:6+2++++7760-10-09-19.16.57.711109+N'

**Comment by nemiah** [comment]
Vermutlich ein ähnliches Problem wie in #40

**Comment by ampaze** [comment]
@ddbxx Kannst du es mit neuesten Master nochmal probieren?

**Comment by ddbxx** [comment]
funktioniert ;)
