### ISSUE TITLE
SSL-Fehler mit Sparkassen

### ISSUE THREAD

**Issue by okj579** [nemiah/phpFinTS#75]
Seit kurzem unterstützen die Server für einige Sparkassen _nur_ TLSv1.2
https://www.ssllabs.com/ssltest/analyze.html?d=banking-bw3.s-fints-pt-bw.de

Gibt es einen Grund, warum phpFinTS auf SSLv1 eingeschränkt ist?
https://github.com/nemiah/phpFinTS/blob/c505635b250ae85d2d38c9c57a6318323a55a2b9/lib/Fhp/Connection.php#L52
Wenn ich diese Zeile auskommentier, funktionierts wieder.

**Comment by nemiah** [comment]
:heavy_check_mark:
