### ISSUE TITLE
Postbank, Gewähltes Zwei-Schritt-Verfahren nicht unterstützt. (9200)

### ISSUE THREAD

**Issue by 1manfactory** [nemiah/phpFinTS#78]
Hallo.

Erstmal vielen Dank für die Mühen aller in dieses Projekt eingebundenen Leute.

Bis zur pösen Umstellung funktionierte der Zugriff auf mein Postbank-Konto per HBCI problemlos.

Jetzt habe ich fleißig meine FinTS-Registrierungsnummer beantragt und (wie ich hoffe) auch richtig eingetragen.

Allerdings bekomme ich bei statement_of_account.php folgende Fehlermeldung:

Sth. went wrong - Request Failed: Gewähltes Zwei-Schritt-Verfahren nicht unterstützt. (9200); Dialogabbruch. (9800)

Noch zur Info: Ich habe unter meinem Alias/Username bei der Bank drei verschiedene Girokonten. Kann es daher zu Problemen kommen?

Ich weiß jetzt leider nicht mehr weiter. Wer kann mich netterweise in die richtige Richtung schubsen.

Danke
Jürgen

**Comment by nemiah** [comment]
Hallo @1manfactory!

Normalerweise sollten mehrere Konten kein Problem sein. Die Postbank hat sich aber auch was spezielles ausgedacht. Hast du mit `getVariables()` die verfügbaren TAN-Mechnismen abgefragt und eines mit `setTANMechanism()` gesetzt? Ich glaube bei der Postbank musste man auch das TAN-Gerät noch auswählen. Dazu müsste aber jemand etwas sagen, der auch ein Postbank-Konto hat.

**Comment by 1manfactory** [comment]
Danke für die Antwort.

Kleine Zwischen-Statement für Interessierte. Ja, bei der Postbank hat man die Wahl zwischen mehreren TAN-Geräten. Ich nutze zwei verschiedene: Hardware-Generator und App. Diese muss man explizit (natürlich) mit den Konten verbinden und benennen.

Das kommt bei getVariables heraus:

```
stdClass Object
(
    [tanModes] => Array
        (
            [912] => chipTAN optisch HHD1.4
            [913] => chipTAN manuell HHD1.4
            [920] => BestSign
            [930] => mobileTAN
        )

)
```

912 und 913 stehen für den TAN-Generator, der die Barcodes am Bildschirm ablesen kann (optisch) oder bei dem man die Parameter eintippen muss (manuell).

920 bezeichnet die App

930 steht immer noch (komischerweise) für mobile Tans

Habe jetzt in _statement_of_account.php_ die Zeile angepasst:

`$fints->setTANMechanism(920);`

Ausgabe:

> Sth. went wrong - Request Failed: Auftrag ausgeführt. (0020); BPD nicht mehr aktuell. Aktuelle Version folgt. (1040); Meldung unterstützter Ein- und Zwei-Schritt-Verfahren (912, 913, 920, 930) (3920); UPD nicht mehr aktuell. Aktuelle Version folgt. (1050); Name des TAN-Medium erforderlich. (9210); Keine starke Authentifizierung erforderlich. (3076); Teilweise fehlerhaft. (9050)

Es scheint mir, wir tasten uns gerade näher heran.

**Comment by ddbxx** [comment]
Ich habe das selbe Verhalten, und ich denke die Postbank hat BestSign noch nicht vollständig in FinTS eingebaut. Wähle 
`$fints->setTANMechanism(912);`
dann wirst du deine Statements ohne eine TAN Abfrage abrufen können.

**Comment by dtvmedia** [comment]
Ich hatte das jetzt auch mal mit 2 Postbank Konten getestet und war erst irritiert warum das Ganze nicht funktioniert. Und es lag in der Tat am fehlenden `setTANMechanism()`. 

Aber ist diese Funktion bei anderen Banken für den reinen Read-Only Zugriff nicht erforderlich? Weil in den Beispielen davon auch nix drin ist (zumindest bei den einfachen Connect und Saldoabfragen Beispielen)

**Comment by ddbxx** [comment]
Bei `setTANMechanism()` wird ja die Nummer der TAN-Methode und der Name des Geräts festgelegt. Wenn du diese Funktion nicht aufrufst, dann nimmt die Bibliothek eine Nummer aus der Liste (bestimmt 912), lässt aber den Namen des Geräts frei. Das akzeptieren manche Banken, Postbank will da einen (beliebigen nicht-leeren) Wert stehen haben (deswegen das 'A').

**Comment by 1manfactory** [comment]
> Ich habe das selbe Verhalten, und ich denke die Postbank hat BestSign noch nicht vollständig in FinTS eingebaut.

Ich denke doch, dass die Postbank das hat. Denn ich nutze die Desktop-Software Haushaltsbuch (http://www.softwarenetz.de/), um meine verschiedenen Postbankkonten abzufragen. Dazu ist FinTS 3.0 angegeben. Und ich musste bisher nur einmal eine TAN bei der Abfrage generieren (vor ca. 2 Wochen) seitdem läuft die Abfrage ohne erneute TAN-Abfrage. Es muss also irgendwie funktionieren.

**Comment by 1manfactory** [comment]
Interessant. Ich habe jetzt nur einen regulären Namen angegeben und schon geht es.

`$fints->setTANMechanism(920, 'RegulärerName');`

Es scheint, als würde die Postbank darauf verzichten, eine TAN (nochmals?) abzufragen, wenn man nur die Umsätze prüfen will.

Ich bedanke mich erstmal an alle – in der Hoffnung, mein Problem damit gelöst zu haben.

**Comment by dtvmedia** [comment]
> Es scheint, als würde die Postbank darauf verzichten, eine TAN (nochmals?) abzufragen, wenn man nur die Umsätze prüfen will.

Das hat mich auch etwas verwundert. Bei mir wurde bis jetzt noch **nie** eine TAN abgefragt beim Holen der Transaktionen.

Ich möchte allerdings das ganze in eine eigene Anwendung einbauen und stehe damit jetzt vor dem Problem das ich nicht weiß ob das nur ein Postbank Spezialfall ist oder das für alle Banken genauso funktioniert (wobei ich mir das nicht vorstellen kann). Leider besitze ich nur 2 Postbank Konten zum testen. 
Könnte jemand mit einem Konto bei einer anderen Bank mir da eine kurze Auskunft darüber geben? :)

**Comment by nemiah** [comment]
Also ich habe Konten bei drei Banken (Sparkasse, VR, Deutsche Bank) und bei allen ist es so, dass die TAN nur abgefragt wird, wenn ich Umsätze von mehr als den letzten 90 Tagen abfrage.

**Comment by 1manfactory** [comment]
> Also ich habe Konten bei drei Banken (Sparkasse, VR, Deutsche Bank) und bei allen ist es so, dass die TAN nur abgefragt wird, wenn ich Umsätze von mehr als den letzten 90 Tagen abfrage.

Von älter als 90 Tagen? Ich dachte, das würde gar nicht gehen. Ich dachte Banken halten nur 90 Tage vor? … Die Postbank jedenfalls hat online nur 90 Tage vorrätig.

**Comment by ampaze** [comment]
Meines wissen hängt die Abfrage daran wann zuletzt eine TAN übermittelt wurde. Egal ob dies per Webseite bei z.B. einer Überweisung oder in einem anderen Programm gemacht wurde.

In dem Falle kommt dann

> 3076: Starke Kundenauthentifizierung nicht notwendig.

Eine Info von der GLS dazu ist z.B.

> Bei PIN & TAN muss eigentlich täglich auch bei der Anmeldung eine TAN eingegeben werden. Wir werden aber diesen Zwang auf 90 Tage ausweiten.
