### ISSUE TITLE
Unterstützung von Schlüsseldateien bspw. für Direct debit

### ISSUE THREAD

**Issue by refda** [nemiah/phpFinTS#8]
Hey,
besteht die Möglichkeit, diese Funktionalität mit einzubinden?

Ich könnte dabei auch behilflich sein hinsichtlich der Programmierung und Testung. Vielleicht lässt sich dies gemeinsam realisieren?

**Comment by nemiah** [comment]
Hallo @refda,

soweit ich informiert bin, wird die Unterstützung von Schlüsseldateien im Zuge von PSD2 eingestellt, da sie nicht sicher genug sind (sie können ja kopiert werden). Wenn es so ist, dann weiß ich nicht, ob sich die Arbeit lohnt.

Liebe Grüße
Nena

**Comment by ampaze** [comment]
Das wäre ein Killer-Feature. Wir benutzen momentan AqBanking mit Sicherheitsprofil RDH-10, d.h. Schlüsseldatei. Also abgeschafft ist das meines Wissens nach nicht.

**Comment by refda** [comment]
Hallo @nemiah,
vielen Dank für die Rückmeldung!

Ich habe auch gehört, dass vereinzelt Banken dieses Verfahren einstellen möchten. Allerdings gerade im Businessbereich wird dieses Verfahren gerne genutzt. Ich habe gerade mit einer Bank aus dem VR-Netzwerk telefoniert und die Rückmeldung erhalten, dass dort die Abschaltung **nicht** geplant ist!

**Comment by refda** [comment]
> Das wäre ein Killer-Feature. Wir benutzen momentan AqBanking mit Sicherheitsprofil RDH-10, d.h. Schlüsseldatei. Also abgeschafft ist das meines Wissens nach nicht.

Ja, es wäre echt ein super Feature! Vielleicht kann man hier gemeinsam einen Lösungsweg erarbeiten und testen.

**Comment by nemiah** [comment]
Hmm, ok, das wäre super, weil damit könnte man automatisch Lastschriften ausführen.

Ich habe gerade bei meiner Bank nachgefragt, ob das noch unterstützt wird. Mal sehen…

Ansonsten bräuchten wir eine funktionierende Implementierung, ich denke bei hbci4java: https://github.com/hbci4j/hbci4java

**Comment by ampaze** [comment]
Fyi: Nach Rücksprache mit unserer Bank, ist die Frage über die Fortführung des Zugriffs via Schlüsseldatei in der Tat noch ungeklärt ☹️. Eine Antwort wird es vermutlich frühestens in 6 Monaten geben.

**Comment by nemiah** [comment]
Ich habe ja bei meiner Bank nachgefragt und sie bieten die Schlüsseldateien schon nicht mehr an.

**Comment by refda** [comment]
Entsprechende Ressourcen sind bspw. hier benannt: 

- https://github.com/marcelbuesing/FinTS/blob/74ce03766e11e27174c2534b96f106d5d6fd3f08/src/FinTS/Data/FinTS3.hs

- https://github.com/hbci4j/hbci4java/blob/master/src/main/java/org/kapott/hbci/passport/rdhXfile/RDHXFile.java

- https://github.com/cstim/aqbanking/blob/798a07be7aaa403996cd9d41fda7e5b1cb0b1a90/src/libs/plugins/backends/aqhbci/banking/provider_keys.c

Sprich aqbanking, hbci4java oder FinTS Haskell.

Interessant wäre es, wenn man erst einmal das Senden eines Auftrags mit einer vorhandenen RDH-Schlüsseldatei implementieren könnte. Also eine minimale Implementation. Wie ich das momentan überblicken kann, ist aber selbst das Vorhaben etwas aufwendiger zu realisieren.

**Comment by nemiah** [comment]
Hmm, was gibt es denn zu tun?
