### ISSUE TITLE
Exception thrown in wrong namespace

### ISSUE THREAD

**Issue by cseifert** [nemiah/phpFinTS#85]
If you provide an empty product name, an exception is thrown in nemiah\php-fints\lib\Fhp\FinTs.php on line 91.

There must be added a backslash in order to avoid the namespace conflicts:

		if(trim($productName) == '')
			throw new **\**Exception ("Product name required!");
		
		if(trim($productVersion) == '')
			throw new **\**Exception ("Product version required!");

**Comment by nemiah** [comment]
Thanks :+1:
