### ISSUE TITLE
Nachrichten sollten je nach den Informationen in HIPINS (automatisch) ein HKTAN Segment bekommen

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#95]
Beim Abruf der Kontoumsätze bei Sparda, kommt die Fehlermeldung

Der gewünschte Auftrag kann nicht verteilt signiert werden.

Was mir leider nicht viel sagt, hat einer eine Idee?

> [info] HKKAZ (statement of accounts) initialize
[info] Start date: 2019-10-28
[info] End date  : 2019-10-28
[debug] >
HNHBK:1:3+000000000447+300+[dialogid]+3'
HNVSK:998:3+PIN:2+998+1+1::[systemid]+1:20191028:103010+2:2:13:@8@00000000:5:1+280:[blz]:[xxx]:V:0:0+0'
HNVSD:999:1+@234@HNSHK:2:4+PIN:2+996+4805100+1+1+1::[systemid]+1+1:20191028:103010+1:999:1+6:10:16+280:[blz]:[xxx]:S:0:0'
HKKAZ:3:5+[xxx]::280:[blz]+N+20191028+20191028++'
HKTAN:4:6+4+HKIDN++++N++++++'
HNSHA:5:2+4805100++[xxx]''
HNHBS:6:1+3'
[debug] < 
HNHBK:1:3+000000000561+300+[dialogid]+3+[dialogid]:3'
HNVSK:998:3+PIN:2+998+1+2::[systemid]+1:20191028:113010+2:2:13:@8@00000000:5:1+280:[blz]:[xxx]:V:0:0+0'
HNVSD:999:1+@317@HNSHK:2:4+PIN:2+996+4805100+1+1+2::[systemid]+1+1:20191028:113010+1:999:1+6:10:16+280:[blz]:[xxx]:S:0:0'
HIRMG:3:2+9050::Die Nachricht enth?lt Fehler.+3905::Antwortliste konnte nicht signiert werden.'
HIRMS:4:2:3+9010::Der gew?nschte Auftrag kann nicht verteilt signiert werden.'
HNSHA:5:2+4805100''
HNHBS:6:1+3'

**Comment by ampaze** [comment]
Ok es liegt daran, dass HKTAN mitgeschickt wird. Scheinbar hängt es von einem Bank Parameter ab ob man diese mitschicken darf/muss oder nicht. Wenn ich den weglassen geht es bei Sparda ohne Probleme. Für GLS allerdings wiederum nicht.

**Comment by ampaze** [comment]
Ich warte mit der Umsetzung bis @Philipp91 HIPINS implementiert hat.

**Comment by Philipp91** [comment]
Hier kommt HIPINS: https://github.com/nemiah/phpFinTS/pull/102
