### ISSUE TITLE
FinTs vs FinTsInternal

### ISSUE THREAD

**Issue by ampaze** [nemiah/phpFinTS#96]
Was genau entscheidet ob eine Methode in FinTs oder FinTsInternal implementiert ist? Ist das nur historisch so gewachsen oder gibt es eine Methodik?

Einige konkrete Geschäftsvorfälle stehen in FinTs andere sind in FinTsInternal. Hilfsfunktionen würde ich in FinTsInternal sehen, konkrete Geschäftsvorfälle in FinTs.

Dadurch wäre es z.B. möglich eine Alternativ-FinTs-Klasse zu haben deren Methoden einheitlicher benannt sind oder die TAN nicht via Callback behandelt.

**Comment by nemiah** [comment]
Ich habe die FinTsInternal gemacht, um die FinTs ein bisschen aufräumen zu können. In der Internal ist hauptsächlich Zeug, das nicht direkt vom Benutzer aufgerufen wird.

**Comment by Philipp91** [comment]
Wenn wir auf `FinTsNew` umsteigen, sprich diese dann zu `FinTs` umbenennen, dürfte sich dieses Problem erledigt haben.

**Comment by ampaze** [comment]
Stimmt.
