### ISSUE TITLE
Tan Number

### ISSUE THREAD

**Issue by waaawoooi** [nemiah/phpFinTS#99]
Vielleicht eine dumme Frage. wie gebe ich die TanNummer ein. Ich selber finde das keine Lösung. and i need some help, please.

**Comment by Metabor** [comment]
Ich hab dafür aktuell Symfony Console verwendet und rufe meine Umsätze damit ab, so kann ich einfach über die console die TAN eingeben.
Es sollte aber auch über den Browser gehen, aber dann brauchst Du eine Zwischenseite auf der Du nach der TAN fragst und musst die ursprüngliche Rückmeldung speichern (z.B. in der Session oder wo auch immer du ein serialisiertes PHP Objekt zwischenspeichern kannst).
Hoffe das hilft Dir.

**Comment by fischmi** [comment]
Und wie funktioniert die Tan-Abfrage aktuell mit photoTan? Geht dies aktuell noch nicht?

**Comment by nemiah** [comment]
Nee, photoTan funktioniert leider nicht :disappointed:

**Comment by herrleinIT** [comment]
wie schaut das mit chipTan aus? Da muss ich die "App" zumindest einmal registrieren damit die Tan in Zukunft entfällt, aber dafür braucht man eine Tan :)
Hat da schon jemand eine Lösung?

**Comment by nemiah** [comment]
Sorry, auch kein chipTAN :cry:

**Comment by nemiah** [comment]
Ach ja, photoTAN funktioniert inzwischen und chipTAN sollte damit auch gehen :blush:
